### ISSUE TITLE
onnxruntime infer, the same input occasionally has different output

### ISSUE THREAD

**Issue by BChunlei** [microsoft/onnxruntime#9704] opened 2021-11-09 03:27 UTC
**Describe the bug**
I convert yolov3 model from pytorch to onnx. When I use onnxruntime to do infer with c++ api, I find the same input occasionally has different output. I test the faster-rcnn model that has the same issue. The result is like that:
1.) 364.738 370.296 452.347 452.397 0.930632 7
2.) 364.732 370.294 452.347 452.404 0.930677 7
3.) 364.737 370.292 452.347 452.398 0.930689 7
4.) 364.74 370.285 452.351 452.401 0.930678 7

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.9.0
- CUDA/cuDNN version: 11.2

**To Reproduce**
the c++ code:
```
#include <assert.h>
#include <vector>
#include <iostream>
#include <onnxruntime_cxx_api.h>
#include <opencv2/core/core.hpp>
#include <opencv2/opencv.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <ctime>
#include <sys/time.h>


using namespace cv;

void preProcess(cv::Mat &img, float *output)
{
    cv::cvtColor(img, img, COLOR_BGR2RGB);
    
    int input_w = 800;
    int input_h = 800;
    float scale = cv::min(float(input_w) / img.cols, float(input_h) / img.rows);
    auto scaleSize = cv::Size(img.cols * scale, img.rows * scale);
 
    cv::Mat resized;
    cv::resize(img, resized, scaleSize, 0, 0);
    cv::Mat cropped = cv::Mat::zeros(input_h, input_w, CV_8UC3);
    cv::Rect rect((input_w - scaleSize.width) / 2, (input_h - scaleSize.height) / 2, scaleSize.width, scaleSize.height);
 
    resized.copyTo(cropped(rect));
    imwrite("/home/faster_process.jpg", cropped); 
 
    constexpr static float mean[] = {123.675, 116.28, 103.53};
    constexpr static float std[] = {58.395, 57.12, 57.375};
    
    for (int c = 0; c < 3; c++)
    {
        for (int i = 0; i < input_h; i++)
        {
            for (int j = 0; j < input_w; j++)
            {
                float pix = cropped.ptr<uchar>(i)[j * 3 + c];
                output[c * input_h * input_w + i * input_w + j] = (pix - mean[c]) / std[c];
                
            }
        }
    }
}

int main(int argc, char* argv[]) {
 
  Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "");
  Ort::SessionOptions session_options;
  session_options.SetIntraOpNumThreads(1);
  //session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
  session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);
  
  //OrtStatus* ort_st = OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0);
  int device_id = 0;
  Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, device_id));

  const char* model_path = "./faster_dianlan3.onnx";
  std::string image_file = "./dianlan.jpg";
  
  timeval start,end;
  gettimeofday(&start,NULL);
  
  Ort::Session session(env, model_path, session_options); 
  
  gettimeofday(&end,NULL);
  double timeuse = end.tv_sec - start.tv_sec + (end.tv_usec - start.tv_usec)/1000000.0;
  std::cout << "load time:" << timeuse << std::endl;		//s为单位
  
  // print model input layer (node names, types, shape etc.)
  Ort::AllocatorWithDefaultOptions allocator;
  
  const char* input_names[] = {"input"};
  const char* output_names[] = {"dets","labels"};
  
  const int width_ = 800;
  const int height_ = 800;
  const int channel_ = 3;
  
  std::array<int64_t, 4> input_shape{1, channel_, width_, height_};
  std::vector<float> input_tensor_values(channel_ * width_ * height_);
  
  auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeCPU);
  
  Ort::Value input_tensor = Ort::Value::CreateTensor<float>(memory_info, input_tensor_values.data(), input_tensor_values.size(), input_shape.data(), input_shape.size());
  //Ort::Value output_tensor_ = Ort::Value::CreateTensor<float>(memory_info, results_.data(), results_.size(), output_shape_.data(), output_shape_.size());
  
  float *input_float = input_tensor_values.data();
  fill(input_tensor_values.begin(), input_tensor_values.end(), 0.f);
  
  Mat img = imread(image_file);
  
  gettimeofday(&start,NULL);
  preProcess(img, input_float);
  gettimeofday(&end,NULL);
  timeuse = end.tv_sec - start.tv_sec + (end.tv_usec - start.tv_usec)/1000000.0;
  std::cout << "preProcess time:" << timeuse << std::endl;		//s为单位
  
  std::vector<Ort::Value> output_tensors;
  gettimeofday(&start,NULL);
  for (unsigned int i = 0; i < 1; i++)
  {
    output_tensors = session.Run(Ort::RunOptions{nullptr}, input_names, &input_tensor, 1, output_names, 2);
  }
  gettimeofday(&end,NULL);
  timeuse = end.tv_sec - start.tv_sec + (end.tv_usec - start.tv_usec)/1000000.0;
  std::cout << "infer time:" << timeuse << std::endl;		//s为单位
  
  const auto boxes = output_tensors[0].GetTensorMutableData<float>();
  const auto labels = output_tensors[1].GetTensorMutableData<int>();
  
  //std::cout << output_tensors[1].GetValue(0) << std::endl;
  //std::cout << output_tensors[1].GetTypeInfo() << std::endl;
  
  
  for (unsigned int i = 0; i < 10; i++)
  {
    std::cout << boxes[i*5+0] << " ";
    std::cout << boxes[i*5+1] << " ";
    std::cout << boxes[i*5+2] << " ";
    std::cout << boxes[i*5+3] << " ";
    std::cout << boxes[i*5+4] << " ";
    std::cout << labels[i] << std::endl;
  }

  printf("Done!\n");
  return 0;
}
```

onnx model:
[https://github.com/BChunlei/faster-rcnn-onnx](url)

jpg file:
![dianlan](https://user-images.githubusercontent.com/44046955/140856092-e63a26e6-eaa1-4f39-ac1a-b487c4a8a6fe.jpg)

**Expected behavior**
the same input should have the same output.

**Comment by hariharans29** [comment] 2021-11-10 23:49
Is this a dupe of https://github.com/microsoft/onnxruntime/issues/4611 ?

ORT's results are not guaranteed to be deterministic and what really matters is if the results are significantly off. Looking at the below results you had shown they don't look significantly off

1.) 364.738 370.296 452.347 452.397 0.930632 7
2.) 364.732 370.294 452.347 452.404 0.930677 7
3.) 364.737 370.292 452.347 452.398 0.930689 7
4.) 364.74 370.285 452.351 452.401 0.930678 7

**Comment by BChunlei** [comment] 2021-11-12 03:20
OK. Is it possible to be solved in the future?

**Comment by hariharans29** [comment] 2021-11-12 18:08
No, we do not plan to provide any idempotency guarantees, results may vary within a certain tolerance level. Please re-open if you find a case where results "significantly off".

**Closed by hariharans29** 2021-11-12 18:08 UTC
Labels: ep:CUDA

**Comment by jcdatin** [comment] 2024-09-19 12:40
on my faster-rcnnn network inference , I fixed my non determinism by replacing GraphOptimizationLevel::ORT_ENABLE_ALL with GraphOptimizationLevel::ORT_DISABLE_ALL (variability was very small though with GraphOptimizationLevel::ORT_ENABLE_ALL : 10e-7 for confidence score and 10-e4 for box coordinates. Got a inference exeution time regression of <5%
