### ISSUE TITLE
v1.1.1 cant' load certain onnx file

### ISSUE THREAD

**Issue by notogawa** [microsoft/onnxruntime#3029] opened 2020-02-17 04:59 UTC
**Describe the bug**

Some onnx model which can be loaded by onnxruntime-1.1.0 are can't be loaded by onnxruntime-1.1.1.

**System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 1.1.1
- Python version: 3.7.4

**To Reproduce**

Try [this model](https://gist.github.com/notogawa/84a62313cd7ffe1d4fb66a6b1d47724b/raw/c996f35ec515f871cc23d15d8200d1092e548593/mnv2.onnx), like `InferenceSession("mnv2.onnx")`.

**Expected behavior**

InferenceSession is created without error.

**Screenshots**

~~~
>>> import onnxruntime as rt
>>> rt.__version__
'1.1.1'
>>> rt.InferenceSession('mnv2.onnx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/notogawa/.pyenv/versions/3.7.4/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 25, in __init__
    self._load_model(providers)
  File "/Users/notogawa/.pyenv/versions/3.7.4/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 43, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : This is an invalid model. Graph output (mobilenetv20_features_pool0_fwd) does not exist in the graph.
~~~

~~~
>>> import onnxruntime as rt
>>> rt.__version__
'1.1.0'
>>> rt.InferenceSession('mnv2.onnx')
<onnxruntime.capi.session.InferenceSession object at 0x10adfb250>
~~~

**Comment by tracysh** [comment] 2020-02-17 09:01
Thanks for the report. The bug is caused by the NCHWc layout optimizer. This graph has every internal node output also be a graph output. The optimizer wasn't accounting for this. I have a fix I've tested out and the graph loads successfully. I'll push that PR out tomorrow.

With this though, there will be extra CPU cycles spent to reorder buffers for each of the convolution and pooling nodes. If the graph outputs could be reduced to just the needed output, that would improve inference time when using this optimization.

**Comment by notogawa** [comment] 2020-02-17 13:21
I intentionally convert a source graph to a new graph which outputs all internal nodes for a special purpose. The graph in this issue is one of such converted graph.

**Comment by tracysh** [comment] 2020-02-17 22:56
The fix for this has been merged into master. Thanks again for the report.

**Closed by tracysh** 2020-02-17 22:56 UTC
