### ISSUE TITLE
Error when exluding nodes from quantization: "ValueError: list.remove(x): x not in list"

### ISSUE THREAD

**Issue by vvolhejn** [microsoft/onnxruntime#12556] opened 2022-08-11 14:16 UTC
When quantizing a 1D CNN, I found that excluding normalization (layer norm followed by learnable scale and shift) from quantization improves the accuracy quite a bit. Then I tried to do the same with a slightly different network ([.onnx here](https://drive.google.com/file/d/1D7o5pRScm6eiWCbT35JIFTmN3w8wHU4B/view?usp=sharing)) but ORT crashed when quantizing this network.

**Urgency**: A fast resolution would allow me to include the results in my Master's thesis (deadline 31.8.) but I can also not use this network.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian GNU/Linux 11 (bullseye)
- ONNX Runtime installed from (source or binary): binary (nightly through pip)
- ONNX Runtime version: 1.12.0.dev20220708003
- Python version: 3.8.12
- CUDA/cuDNN version: not relevant
- GPU model and memory: not relevant

I am using the nightly version because it fixes a different bug that I encountered earlier.

**To Reproduce**

This code is not quite self-contained, but hopefully gives enough information:

```python
import re

import onnx
import onnxruntime.quantization as ortq

model = onnx.load(save_path)

nodes = [n.name for n in model.graph.node]
normalization_nodes = [
    n for n in nodes if re.search(r"/normalize_?[0-9]*/", n)
]

ortq.quantize_static(
    save_path,
    output_path,
    data_reader,
    activation_type=ortq.QuantType.QInt8,
    weight_type=ortq.QuantType.QInt8,
    per_channel=True,
    reduce_range=True,
    quant_format=ortq.QuantFormat.QDQ,
    extra_options={
        "WeightSymmetric": True,
        "ActivationSymmetric": False,
        "CalibMovingAverage": True,
    },
    calibrate_method=ortq.CalibrationMethod.MinMax,
    nodes_to_exclude=normalization_nodes,
)
```

[.onnx available here.](https://drive.google.com/file/d/1D7o5pRScm6eiWCbT35JIFTmN3w8wHU4B/view?usp=sharing)

I also tried digging into this a bit and found that the problem is in the "add" nodes: If I remove them from `nodes_to_exclude` (so that they *are* quantized), quantization doesn't crash. But this increases loss again, defeating the original purpose of excluding the nodes.

**Comment by yufenglee** [comment] 2022-08-12 20:54
The issue is fixed with the PR.

**Closed by yufenglee** 2022-08-12 20:54 UTC
Labels: quantization
