### ISSUE TITLE
GPU Memory Release Problem ONNRuntime C++

### ISSUE THREAD

**Issue by anirudha16101** [microsoft/onnxruntime#4506] opened 2020-07-14 13:27 UTC
Hi, Currently I am using ONNX C++ Api and when I analysis the GPU Memory Usage.  I find that Onnx is not Releasing the Whole memory until its .exe got killed. Can Somebody Explain me why it is not releasing the memory completely. I have used gort->ReleaseSession(session);, g_ort->ReleaseSessionOptions(session_options); g_ort->ReleaseEnv(env);
 code at the last to release the memory.

For Reference:---
Here memory is not released It is still occupying 7% of GPU Memory. but after some time when I close the exe it goes down to 0
Please Help!! me How can I release the memory completely without killing the .exe.
![github](https://user-images.githubusercontent.com/46598161/87430844-6a5e7c00-c603-11ea-9e21-56e08ca186e1.PNG)

**Comment by pranavsharma** [comment] 2020-07-15 08:14
Which execution provider are you using?

**Comment by anirudha16101** [comment] 2020-07-15 08:20
Thanks @pranavSharma  I am using  CUDA, GraphOptimizationLevel- ORT_ENABLE_BASIC ,ExecutionMode- ORT_SEQUENTIAL
  Code For Reference:-
    g_ort->SetIntraOpNumThreads(session_options, 1);
    g_ort->SetSessionGraphOptimizationLevel(session_options, ORT_ENABLE_BASIC);
    OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0);

**Comment by pranavsharma** [comment] 2020-07-16 18:25
We'll get back to you after doing some investigation.

**Comment by anirudha16101** [comment] 2020-07-17 05:50
Okay @pranavsharma Thanks for the help!!

**Comment by anirudha16101** [comment] 2020-07-21 10:11
Hi, @pranavsharma  Did You find Anything?

**Comment by HectorSVC** [comment] 2020-07-28 17:51
@anirudha16101, I can reproduce this now. I'm still digging into it. I can see there's 0.3 GB occupied. I'm testing with yolov3 model.
Could you provide more information of your usage scenarios? Are you trying to re-create the session then release it frequently? What kind of model are you using?

**Comment by anirudha16101** [comment] 2020-07-28 19:36
@HectorSVC Hi, I am currently using Deeplab Model for Segmentation. So  Firstly I converted the model from pb format to Onnx Format Now I have created the Session at Once and running for Multiple Images in loop. So Suppose If I take 4 images after running Session for 4 images Sequentially in Loop. I am releasing the Session Memory and environments at the end.
For your test case Please create the session for yolov3 model at once and run for multiple times. Thanks!!

**Comment by anirudha16101** [comment] 2020-07-28 19:45
Usage Scenario::--My pipeline contains different models for e.g I take two Models A first then result of A is used as input for Model B. Both uses GPU Memory So First A will run in this A I can  run Session at once or multiple Times. If A is taking 20% of GPU and it is not releasing the memory then there will be poor memory usage because may be B can use 40% of GPU. But what if I took 10 Models so there is possibility at the end that last model cannot get sufficient Memory So I need to remove this Unnecessary Memory Consumption. and It should work because I am manually releasing the Session at the end of Pipeline Model.

**Comment by HectorSVC** [comment] 2020-08-07 06:23
@anirudha16101, I still can't repo the case you encountered. I run with different models, like the FasterRCNN, ssd, tf_inception_resnet_v2, etc. I also use one session for multiple input data. I also dumped the cudaMalloc vs cudaFree withe the addresses, and found out that there's no memory leak for the memory allocated from our allocator. I'm not sure whether it related to your model, maybe some for some special operators. Is it possible to share your model with us?
You can also have a try with our test tool onnxruntime_perf_test.exe if you build it from source. Here's a guide for the tool: https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_Perf_Tuning.md
Last, for your model A & B, is it possible it merge it into one model? It could save data copy across device.

**Comment by anirudha16101** [comment] 2020-08-10 13:19
@HectorSVC  First of all sorry I can't share my model right now,but I can say that it is based on DeepLab and second you have mentioned in previous comment that you are also facing the same issue while running the session multiple times for YOLO are you able to solve the issue, If possible can you share the code. I am currently using this model Inferencing in python and Checking if same issue  are coming in Python onnxruntime-gpu Api or not. But I am not sure if python have this code equivalent
gort->ReleaseSession(session);, g_ort->ReleaseSessionOptions(session_options); g_ort->ReleaseEnv(env);
Manually releasing the session is available or not. Can You guide me How can I do this in python.
In  https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/session.py I find _reset_session() At first I thought this may help but still after using this Session._reset_session() it is not releasing the memory. After executing the code the memory is released.
At last I am currently using already available Binaries from Nuget So I need some time to Build it from source and test with your tool
and off-course you are right I can merge two models into single model I think I am not able to properly communicate my usage scenario:
Suppose I have 4 Models A,B,C,D  A and C uses GPU. B and D does not uses GPU. 
Execution order   A->B->C->D if A does not releases the memory than it may cause issue for C. Hence for this situation we cannot merge the models. 
I hope You understand my Problem If not I can share the pseudo code. and once again Thanks for Help!!

**Comment by HectorSVC** [comment] 2020-08-13 01:17
The one I mentioned (GPU memory usage not go back to it's original state) is actually because the CUDA context(https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#context), it hold some resource on GPU. Normally, call cudaDeviceReset() as part of application shutdown will release it. We can't make it part of SessionRelease because cudaDeviceReset() works for the process scope. https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1gef69dd5c6d0206c2b8d099abac61f217. User could have multiple session running in different threads. It's difficult to find a right place in the Ort framework to make this happen as we don't have a control for the User application code. The context will be force destroyed after application shutdown.

For your case, I don't see any impact with this. Even we call cudaDeviceReset to clear the CUDA context on GPU during session release, the next session for model C still need to create it which will take some cost also.

**Comment by HectorSVC** [comment] 2020-08-19 06:17
@anirudha16101, Can we close the issue if no further questions?

**Comment by anirudha16101** [comment] 2020-08-19 06:41
@HectorSVC  Yeah Sure!! Thanks for Help Most Probably I will try to remove this CUDA Problem asap.

**Closed** 2020-08-19 06:42 UTC
Labels: type:performance
