### ISSUE TITLE
Problem loading Scikit-Learn Pipeline With DictVectorizer

### ISSUE THREAD

**Issue by dafajon** [microsoft/onnxruntime#10098] opened 2021-12-21 15:07 UTC
**Describe the bug**
I have a pipeline serialized via `skl2onnx` converter.
```python
pipeline = Pipeline([('feat', DictVectorizer(sparse=False)), ('dt', RandomForestClassifier())])
```

Which ingests span based features to work as a sentence boundary detection model as follows:
```python
 [{'ALL_LOWER': True, 'NEXT_ALL_LOWER': True}, {'PREV_ALL_LOWER': True, 'ALL_LOWER': True, 'NEXT_ALL_LOWER': True}, {'PREV_ALL_LOWER': True, 'ALL_LOWER': True, 'NEXT_ALL_LOWER': True}, ... ,{'PREV_ALL_LOWER': True, 'ALL_LOWER': True, 'NEXT_ALL_LOWER': True}]
```

Keys are of type `string` and values are `bool`.

The model is serialized with `skl2onnx` as follows.

```python
initial_type = [('boolean_input', DictionaryType(StringTensorType([1]), BooleanTensorType([1])))]
onx = convert_sklearn(pipeline, initial_types=initial_type)
```

Upon loading, I have the following error:

```bash
InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from /Users/dorukhanafacan/sadedegel/sadedegel/ml/model/sbd.onnx failed:This is an invalid model. Type Error: Type 'map(string,tensor(bool))' of input parameter (boolean_input) of operator (DictVectorizer) in node (DictVectorizer) is invalid.
```

I tried again also with `StringType` for key but had the same issue. Loading models with `DictionaryType` initilalized with other key, value types returned different issues since they are not compatible with the input type the model is trained on. However `InvalidGraph` is not encountered with them.

**Urgency**
Delaying the next release of our [library](https://github.com/GlobalMaksimum/sadedegel)

**System information**
- OS Platform and Distribution: MacOS 10.14.2
- ONNX Runtime installed from (source or binary): PyPI 1.10.0
- ONNX Runtime version: 1.10.0
- Python version: 3.8.12
- Visual Studio version (if applicable): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: None
- GPU model and memory: None

**Comment by garymm** [comment] 2021-12-21 18:20
Does the [ONNXchecker](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#checking-an-onnx-model) consider the model valid?
If not then this is likely a bug in the sklearn-onnx converter and you should file it there: https://github.com/onnx/sklearn-onnx

If yes, then this is either a bug in ONNX Runtime, or the ONNX checker needs to become more strict.

**Comment by dafajon** [comment] 2021-12-21 22:03
The model checks out as valid from the "onnx_checker" snippet on the provided link.

**Comment by skottmckay** [comment] 2021-12-22 01:09
ONNX checker may have a gap.

The spec for [DictVectorizer](https://github.com/onnx/onnx/blob/master/docs/Operators-ml.md#aionnxmldictvectorizer) says map(string,bool) is supported but your model seems to have `map(string,tensor(bool))`

I don't know why the model is generated with tensor(bool) instead of bool for the value. @xadupre may be able to help with that.

**Comment by dafajon** [comment] 2021-12-22 09:15
I checked [this](https://github.com/onnx/sklearn-onnx/blob/master/skl2onnx/common/data_types.py) link. There is `BooleanTensorType` but I could not see `BooleanType`. 

By the way the type constraints for [DictVectorizer](https://github.com/onnx/onnx/blob/master/docs/Operators-ml.md#aionnxmldictvectorizer) are stated as

`T1 : map(string, int64), map(int64, string), map(int64, float), map(int64, double), map(string, float), map(string, double)`

I could not see `map(string, bool)`

**Comment by xadupre** [comment] 2021-12-22 11:31
I created a PR to investigate. It works if you replace the BooleanTensorType with FloatTensorType. It should not impact your performance. onnxruntime only supports float values and int64, string keys. See https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/onnxruntime_pybind_mlvalue.cc#L648.

**Comment by garymm** [comment] 2021-12-22 18:19
@dafajon if you'd be so generous, please file an issue in onnx/onnx about the ONNX checker not failing. If you can upload the .onnx file that would be helpful.

**Comment by dafajon** [comment] 2021-12-27 15:35
@garymm Thank you I am on it.
@xadupre Thank you I am going to try that way. I will let you know if there are any issues.

**Comment by dafajon** [comment] 2021-12-28 16:57
I have completed my work with the `onnx` model by using your suggested workaround. You can close this issue if that is all. Will there be any support of `BooleanTensorType` in the future? 

Best.

**Comment by skottmckay** [comment] 2021-12-29 01:32
> Will there be any support of `BooleanTensorType` in the future?

That would require an update to the ONNX spec for the operator. If you can make a case that the implementation cost of adding support for bool provides enough benefit please request any spec update via https://github.com/onnx/onnx/issues. As the existing supported types can be used to represent a bool the benefit seems limited to me.

**Comment by garymm** [comment] 2022-01-19 19:21
Seems the issue is resolved, so closing. Please comment if I'm mistaken.

**Closed by garymm** 2022-01-19 19:21 UTC
Labels: component:converter
