### ISSUE TITLE
Batch inference in Python with onnxruntime 1.0.0

### ISSUE THREAD

**Issue by eladior** [microsoft/onnxruntime#2468] opened 2019-11-22 21:33 UTC
Hi, I'm running into an issue with version 1.0.0. 

I was able to do batch inference with version 0.5.0 by changing the first dimension of the array. For example, if the input size was [1,3,64,64], I could send as input an array of size [x,3,64,64] without issues and get prediction for the x samples.
However, in version 1.0.0. with the same model, this results in the following error: InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: input for the following indices
 index: 0 Got: 311 Expected: 1
 Please fix either the inputs or the model.

What changed from v0.5.0 to v1.0.0? Is there a way to do batch inference in v1.0.0?

Thanks in advance.

**Comment by pranavsharma** [comment] 2019-11-23 02:09
Looks like your model has the batch dimension hardcoded to 1. Until 0.5 we were less strict. Check [here](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/session/inference_session.cc#L664) for more details. Can you change the model to introduce a symbolic dimension for batch size? We don't validate symbolic dimensions.

**Comment by eladior** [comment] 2019-11-26 14:25
Thanks for the clarification. I understand the difference now, in 0.5 the shape check gave a warning but returned an ok status. 

I'm not sure I'll be able to change the models with symbolic dimensions.  Could I change CheckShapes in v.1.0 to the one in v.0.5 and rebuild? Any chance this particular check could be reverted to warning instead of an error?

Thanks!

**Comment by pranavsharma** [comment] 2019-11-27 08:58
> Thanks for the clarification. I understand the difference now, in 0.5 the shape check gave a warning but returned an ok status.
> 
> I'm not sure I'll be able to change the models with symbolic dimensions. Could I change CheckShapes in v.1.0 to the one in v.0.5 and rebuild? Any chance this particular check could be reverted to warning instead of an error?
> 
> Thanks!

Of course, you should be able to change the implementation of CheckShapes to your liking in your fork and rebuild. 
By "reverting to warning" do you mean just log it as a warning and not return an error? If so, sorry, we don't intend to do this.

**Comment by hariharans29** [comment] 2019-11-28 20:37
Closing this out as this action is by design. Please re-open for further clarifications.

**Closed by hariharans29** 2019-11-28 20:37 UTC
