### ISSUE TITLE
data_ptr is 0 for io_binding in gpt2_helper

### ISSUE THREAD

**Issue by marksein07** [microsoft/onnxruntime#6204] opened 2020-12-23 03:29 UTC
**Describe the bug**
Hi, 
I tried to run the jupyter script below, and there is a error raising in "Cell 10"
 
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/notebooks/Inference_GPT2_with_OnnxRuntime_on_CPU.ipynb

There are a little problem in inference gpt2.opt.onnx with Gpt2Helper.prepare_io_binding

if there is no past_sequence, the empty_past array shape is (12, 2, batch_size, 12, 0, 64) as usual, the empty_past data_ptr is 0 if any shape size is zero, and there is
 no valid address for binding.

the error is  

![13250965353319](https://user-images.githubusercontent.com/4708597/102955110-15a72180-4510-11eb-8b6c-d662fc0e185c.png)

And I confirm all the data_ptr is zero in empty_past 

![13250982874148 (1)](https://user-images.githubusercontent.com/4708597/102955354-aa118400-4510-11eb-95df-cf72242f7503.png)

if I random produce a none zero sequence length tensor, it works well.

Is that what you expect ? or in inference stage, I should use io_binding after the first token generated ?

in case it's caused by version :
- OS Platform and Distribution:                                    Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary):     pip install
- onnx                                                                          1.8.0
- onnxuntime                                                               1.6.0
- onnxruntime-tools                                                     1.5.2
                          

thanks,

**Comment by tianleiwu** [comment] 2021-02-12 03:56
Please use onnxruntime 1.5.2 for the notebook, or wait for next release 1.7.0.

It is caused by a change in IO Binding in 1.6.0. The bug is fixed in https://github.com/microsoft/onnxruntime/pull/6284 in master branch.

**Closed** 2021-02-12 03:58 UTC
Labels: model:GPT2
