### ISSUE TITLE
CPU runtime inference speed  slow

### ISSUE THREAD

**Issue by SherL0cked** [Microsoft/onnxruntime#167] opened 2018-12-13 09:55 UTC
**Describe the bug**
Inference speed in CPU build for ONNX(converted from Keras) is nearly 6x slower than CPU Keras(TensorFlow with Intel® MKL DNN backend) on same model. 
Have we integrated MKL in the runtime, or else can we expect an approach to speed up inference?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 0.1.4
- Python version: 3.6.0
- GCC/Compiler version (if compiling from source): 5.4.0 20160609
- CUDA/cuDNN version: No
- GPU model and memory: No

**To Reproduce**
```
import time
import numpy as np

x = np.random.random((1,416, 416, 3))
iters = 20

import onnxruntime as rt

sess = rt.InferenceSession("image.onnx")

input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name

_start_time = time.time()
for i in range(iters):
    sess.run([label_name], {input_name: x.astype(np.float32)})[0]
duration = time.time() - _start_time

print("ONNX prediction total duration is %s, per round is %.3f" %
              (duration, duration / iters))

from keras.models import load_model

model = load_model("image.h5")

_start_time = time.time()

for i in range(iters):
    model.predict(x.astype(np.float32))

duration = time.time() - _start_time

print("Keras prediction total duration is %s, per round is %.3f" %
              (duration, duration / iters))
```

**Screenshots**
![image](https://user-images.githubusercontent.com/26664961/49930190-080d3900-feff-11e8-8991-7d47c6373fa4.png)

**Comment by souptc** [comment] 2018-12-13 23:18
The root cause is your keras model is in NHWC, while onnx only support NCHW in conv, so if you open the onnx model, you will find there is a lot of transpose inserted, which result very bad performance. Our converter has some optimization for that but unfortunately we can't eliminate all the transposes...  do you set your keras to channel_first format and train it again?

**Comment by yuanbyu** [comment] 2018-12-13 23:20
My understanding is that those optimizations are not in the Keras converter. @wenbingl.

**Comment by yufenglee** [comment] 2018-12-13 23:43
Nathan and I discussed to create a ONNX to ONNX optimization tool a couple weeks agon. We can put common optimizers (e.g., tranpose optimizers, const folder, back to back reshape optimization and etc.) to this tool. All converters call it after finishing converting.

**Comment by gramalingam** [comment] 2018-12-14 00:59
ONNX itself has a similar ONNX to ONNX optimization tool (https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#optimizing-an-onnx-model ). Is there any plan to combine the optimizations in onnxruntime with those in onnx into one uniform framework?

**Comment by weixingzhang** [comment] 2018-12-14 03:04
We prefer not to make Lotus depend on these ONNX optimization. But, we do want to implement some in Lotus if they are really valuable.

**Comment by SherL0cked** [comment] 2018-12-17 06:47
@souptc thanks for the root cause, actually what i was expecting is able to use same model for both CPU and GPU runtimes, optimization during runtime will be very helpful!

**Comment by souptc** [comment] 2018-12-17 23:58
@SherL0cked , based on the comment above, we already have some optimization in tensorflow converter. a quick trick you can try is to export the keras model's underline tf model, then convert it with TF converter.

**Comment by pengwa** [comment] 2019-01-03 02:02
I made a change in tf converter, allowing users to load an existing onnx file and call the optimizer directly. Feel free to have a try on that. Simple usage:

https://github.com/onnx/tensorflow-onnx/blob/ff36c8eb446af935c3c07bcf0fd9110a863e66bb/tests/test_optimizers.py#L26 

It's just one line, besides loading the onnx file.
 `new_proto = GraphUtil.opt_transposes_with_model_proto(origin_proto) `

**Comment by faxu** [comment] 2019-03-05 19:21
@SherL0cked The Keras converter (https://github.com/onnx/keras-onnx) now has the optimizer...can you try your model to see if this issue is resolved?

**Comment by SherL0cked** [comment] 2019-03-14 07:17
@faxu I believe this solved issue!
Appreciate all for the efforts.

**Comment by pranavsharma** [comment] 2019-03-14 07:29
Closing as per previous comment.

**Closed by pranavsharma** 2019-03-14 07:29 UTC
Labels: Converter, enhancement
