### ISSUE TITLE
Unexpected behavior when set RunOption.run_log_verbosity_level to "warning"

### ISSUE THREAD

**Issue by NonStatic2014** [microsoft/onnxruntime#856] opened 2019-04-17 23:01 UTC
**Describe the bug**
When set the RunOption.run_log_verbosity_level to 2 (warning), I expect to see log in fatal+error+warning levels, but actually I see logs in verbose+info+warning levels.

**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- ONNX Runtime installed from: source
- ONNX Runtime version: master branch
- Python version: N/A
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source):g++-5, the default one in Ubuntu 16.04
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**
```C++
OrtRunOptions run_options{};
run_options.run_log_verbosity_level = 2;
run_options.run_tag = some_request_id;
auto status = session->Run(run_options, name_ml_value_map, output_names, &outputs);
```

**Expected behavior**
I expect to see log in fatal+error+warning levels, but actually I see logs in verbose+info+warning levels.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by NonStatic2014** [comment] 2019-04-17 23:05
Potential Fix: [inference_session.cc](https://github.com/Microsoft/onnxruntime/blob/54e04cb8bb99d749550aa83d577220c00837ad1b/onnxruntime/core/session/inference_session.cc#L868), set the `vlog_level` to `fatal`, and set `severity` as what we get from `RunOptions`.

**Comment by pranavsharma** [comment] 2019-04-22 23:28
@NonStatic2014 would you like to contribute?

**Comment by skottmckay** [comment] 2019-05-02 23:18
This is maybe a badly named property in the RunOptions. The original intention of the property was to allow the vlog level to be set, not the overall logger level. For vlog output to occur, the severity needs to be verbose, hence the current behaviour.

The logger severity would normally be set when creating the LoggingManager (either directly or via OrtCreateEnv).

**Comment by skottmckay** [comment] 2019-05-15 01:11
@NonStatic2014 Is this best fixed by improving documentation about what the expected usage of run_log_verbosity_level is? Or does your scenario require being able to set the severity at the inference session or run level so we need to add an additional value in the session and/or run options?

**Comment by jim-meyer** [comment] 2019-05-17 18:31
I'm trying to set the logging level from the python bindings for onnxruntime to avoid the default behavior of logging warnings.  The docs at https://microsoft.github.io/onnxruntime/api_summary.html don't describe what different values mean though.
Within the python bindings we have no control over how the LoggingManager gets created as @skottmckay noted. So I'm left (afaik) with just using SessionOptions and RunOptions.
From trial and error RunOptions.run_log_verbosity_level = 0 (zero) evidently means "log warnings and worse" (ie. warnings and errors).
And 1 (one) means "log info and worse" (ie. info, warnings and errors).
Is this right? Seems pretty odd to not have a "log errors only" mode.

**Comment by skottmckay** [comment] 2019-05-29 09:05
The log verbosity level was intended to set the VLOG level not the logging severity level. I will look at adding a log severity level to the session and run options, as I think that will provide what you're looking for.

I'll also see if I can expose the default logging severity to the python bindings as well.

**Comment by skottmckay** [comment] 2019-06-12 01:02
You can now change the default logging severity, and this is exposed via the python bindings. This will be used for inference sessions created after the call though - existing session will not have their severity updated.

>>> import onnxruntime
>>> onnxruntime.set_default_logger_severity(3)

Additionally the log severity for the inference session can be set in SessionOptions via the new session_log_severity_level option, and the log severity for an individual call to Run can be set in the RunOptions via the new run_log_severity_level. Help text is also updated to hopefully make the usage clearer.

>>> help(onnxruntime.SessionOptions)
...
 |  session_log_severity_level
 |      Log severity level. Applies to session load, initialization, etc.
 |      0:Verbose, 1:Info, 2:Warning. 3:Error, 4:Fatal. Default is 2.
 |
 |  session_log_verbosity_level
 |      VLOG level if DEBUG build and session_log_verbosity_level is 0.
 |      Applies to session load, initialization, etc. Default is 0.

>>> help(onnxruntime.RunOptions)
...
 |  run_log_severity_level
 |      Log severity level for a particular Run() invocation. 0:Verbose, 1:Info, 2:Warning. 3:Error, 4:Fatal. Default is 2.
 |
 |  run_log_verbosity_level
 |      VLOG level if DEBUG build and run_log_severity_level is 0.
 |      Applies to a particular Run() invocation. Default is 0.

**Closed** 2019-06-12 01:02 UTC
Labels: contributions are welcome, enhancement
