### ISSUE TITLE
[BUG] ScatterElements' Status Message: indices element out of data bounds, idx=433 must be within the inclusive range [-420,419]

### ISSUE THREAD

**Issue by SkylerHuang** [microsoft/onnxruntime#17653] opened 2023-09-21 13:54 UTC
### Describe the issue

It seems that ScatterElements does not support dynamic dimensions? 
I can successfully torch.onnx.export() a model that contains torch.scatter, but when I run it with onnxruntime, 
it can only run the sample that the exported model. 
If I run another sample, it will fail.
 It seems that the sample dimensions are hard-coded into the onnx model when it is exported, which seems unreasonable.

### To reproduce

torch.scatter_reduce(x, dim=0, index=cluster, src=x, reduce='max', include_self=False)

If the dimensions of the exported sample x and cluster do not match the dimensions of the next sample, an error will occur.

### Platform

Linux

### OS Version

20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

onnxruntime-gpu           1.15.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

**Comment by hariharans29** [comment] 2023-09-27 06:04
I believe there is a flag to be turned on while doing the torch export in order to export with dynamic shapes. Please check the documentation of the torch exporter for this. If you think you have configured it correctly, but the model still isn't exported as you expected it to (i.e.) not supporting dynamic shapes - please file an issue with Torch for this. 

Closing as this seems like an issue with the exported model and not the runtime. Please re-open if you get confirmation that the model is fine and running it with ORT is where the issue is.

**Closed by hariharans29** 2023-09-27 06:04 UTC
Labels: ep:CUDA
