### ISSUE TITLE
Complete example to use yolov3.onnx model for inference

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [microsoft/onnxruntime#5765] opened 2020-11-11 02:31 UTC
Hi, 
     I have a yolov3.onnx model and now I want to use this model for inference on the input image.  
I have tried to use the yolov3 example (https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov3) but that only describes image pre and post-processing steps. So is there any complete example to use yolov3.onnx for inference? 

Thanks

**Comment by edgchen1** [comment] 2020-11-11 18:38
duplicate of https://github.com/onnx/models/issues/396

**Closed** 2021-03-19 00:06 UTC
Labels: status:duplicate, type:support
