### ISSUE TITLE
Python MacOS arm64 release binaries

### ISSUE THREAD

**Issue by lutzroeder** [microsoft/onnxruntime#6633] opened 2021-02-10 04:01 UTC
**Describe the bug**

ONNX Runtime does not install using pip on M1.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 11.2.1
- ONNX Runtime installed from (source or binary): pip
- Python version: 3.9.1

**To Reproduce**

```
~: uname -v
Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101
~: which python3
/opt/homebrew/bin/python3
~: which pip
/opt/homebrew/bin/pip
~: python3 --version
Python 3.9.1
~: pip install onnxruntime
ERROR: Could not find a version that satisfies the requirement onnxruntime
ERROR: No matching distribution found for onnxruntime
```

**Comment by snnn** [comment] 2021-02-10 05:25
What kind of tag we should publish? Does pypi have a standard for that?

**Comment by lutzroeder** [comment] 2021-02-10 06:03
@ronaldoussoren is there some official guidance? Guessing that `macosx_v_universal2` would be more convenient vs. `macosx_v_arm64` and `macosx_v_x64_86`? See also pypa/packaging#319.

**Comment by snnn** [comment] 2021-02-10 06:19
Is it in the latest pip release? What's the version requirement of pip to support it?

**Comment by ronaldoussoren** [comment] 2021-02-10 09:22
pip 21.0.1 can install universal2 wheels (I've just verified this on my machine).   For my own projects I currently publish an x86_64 wheel as before and a universal2 wheel for folks with M1 systems. I intend to drop the x86_64 wheels from releases later this year.

My personal preference is to have universal2 wheels. That reduces the amount of different wheels needed, and more importantly makes it a lot easier to build applications that can be used on both Intel and M1 Macs using tools like py2app and pyinstaller. 

For projects with huge wheels such as tensorflow (which wheels well over 150MB) having per-architecture wheels is likely better due to disk usage considerations.

**Comment by snnn** [comment] 2021-02-10 17:37
@ronaldoussoren  Thank you for the information, it is really helpful. We will look into it. 

Currently we are preparing the release for 1.7. The deadline is soon. Likely this feature won't be in that release. Sorry.

**Comment by lutzroeder** [comment] 2021-03-13 08:15
onnx/onnx#3129

**Comment by sarim-zafar** [comment] 2021-07-08 14:59
any update on this?

**Comment by snnn** [comment] 2021-07-08 20:40
I'm working on it.

**Comment by snnn** [comment] 2021-07-14 00:59
Reference: 

1. https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary
2. https://github.com/pypa/packaging/pull/319 

I think we can do cross-compiling on a Mac X86 hardware. Anybody knows more details? What should I do?

**Comment by snnn** [comment] 2021-07-14 01:04
Let me try to leverage https://cibuildwheel.readthedocs.io/en/stable/options/

**Comment by hossein1387** [comment] 2021-07-16 16:58
what is the plan to support Onnxruntime on M1 chip?

**Comment by OlegTheCat** [comment] 2021-08-13 10:33
Being able to run ONNX on M1 Macs is very desired. Currently, there's no ability to do development with ONNX on these laptops. So instead, I have to use a virtual machine or rent a cloud x64 instance, which impedes productivity or creates additional costs.

**Comment by snnn** [comment] 2021-08-15 17:05
I will submit a PR and publish a test package tomorrow.

**Comment by snnn** [comment] 2021-08-16 22:37
https://test.pypi.org/project/onnxruntime/1.8.2.dev20210816004/
To install it:
```
pip3 install --upgrade pip
pip3 install numpy
pip3 install -i https://test.pypi.org/simple/ onnxruntime==1.8.2.dev20210816004
```

**Comment by hossein1387** [comment] 2021-08-17 02:09
I followed your instructions and I am getting the following error:

```
>>> import onnxruntime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hossein/miniforge3/lib/python3.9/site-packages/onnxruntime/__init__.py", line 34, in <module>
    raise import_capi_exception
  File "/Users/hossein/miniforge3/lib/python3.9/site-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
  File "/Users/hossein/miniforge3/lib/python3.9/site-packages/onnxruntime/capi/_pybind_state.py", line 21, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
ImportError: dlopen(/Users/hossein/miniforge3/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so, 2): no suitable image found.  Did find:
	/Users/hossein/miniforge3/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so: mach-o, but wrong architecture
	/Users/hossein/miniforge3/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so: mach-o, but wrong architecture
```

**Comment by snnn** [comment] 2021-08-17 02:10
What's your pip version?

**Comment by hossein1387** [comment] 2021-08-17 02:10
`->pip --version`
`
pip 21.2.4 from /Users/hossein/miniforge3/lib/python3.9/site-packages/pip (python 3.9)
`

**Comment by snnn** [comment] 2021-08-17 02:12
Looks like something is wrong. Let me debug it.

**Comment by snnn** [comment] 2021-08-17 03:46
I found the problem. Fixing.

**Comment by snnn** [comment] 2021-08-17 05:40
It needs quite a lot code changes. CMAKE_OSX_ARCHITECTURES is a list, we shouldn't use it in a way like:
```cmake
if (CMAKE_OSX_ARCHITECTURES STREQUAL "arm64")
```

**Comment by snnn** [comment] 2021-08-18 19:33
Now I got a new one, please try:
https://test.pypi.org/project/ort-nightly/1.8.2.dev169944/

Currently it only has python 3.8 and 3.9.

**Comment by hossein1387** [comment] 2021-08-19 04:06
Works perfectly! Thanks a lot!

**Comment by unbeatable-101** [comment] 2021-08-19 05:41
I'm getting 

```
ERROR: Could not find a version that satisfies the requirement numpy>=1.16.6 (from ort-nightly) (from versions: 1.9.3)
ERROR: No matching distribution found for numpy>=1.16.6
```
I have `numpy-1.21.2` installed

**Comment by snnn** [comment] 2021-08-19 06:26
But the log shows it was trying to install numpy from http://test.pypi.org/, and there isn't one for us. 
So I ask everyone run 
```
pip3 install numpy flatbuffers
```
Before using the 
```
pip3 install -i https://test.pypi.org/simple/ ort-nightly==1.8.2.dev169944
```
command.

**Comment by unbeatable-101** [comment] 2021-08-19 14:21
I did that, and it still errored

```
williamdavis@Williams-Air NeuralHash % pip3 install numpy flatbuffers --upgrade
Collecting numpy
  Using cached numpy-1.21.2-cp39-cp39-macosx_11_0_arm64.whl (12.4 MB)
Collecting flatbuffers
  Using cached flatbuffers-2.0-py2.py3-none-any.whl (26 kB)
Installing collected packages: numpy, flatbuffers
Successfully installed flatbuffers-2.0 numpy-1.21.2
williamdavis@Williams-Air NeuralHash % pip3 install -i https://test.pypi.org/simple/ ort-nightly==1.8.2.dev169944
Looking in indexes: https://test.pypi.org/simple/
Collecting ort-nightly==1.8.2.dev169944
  Downloading https://test-files.pythonhosted.org/packages/0f/ff/2f17ed3344784273501fad2247dbc4542c744e191575ef44a7a71eab6de6/ort_nightly-1.8.2.dev169944-cp39-cp39-macosx_10_14_universal2.whl (9.6 MB)
     |████████████████████████████████| 9.6 MB 3.0 MB/s 
ERROR: Could not find a version that satisfies the requirement flatbuffers (from ort-nightly) (from versions: none)
ERROR: No matching distribution found for flatbuffers
```

**Comment by snnn** [comment] 2021-08-19 16:48
That's strange... 

How about this one: 
```
pip3 install -i https://test.pypi.org/simple/ ort-nightly==1.8.2.dev170114
```

**Comment by snnn** [comment] 2021-08-19 16:53
Ah, so you are using conda and miniforge3. I'm using CPython 3.8 from the operating system. That could be the cause.

**Comment by hossein1387** [comment] 2021-08-19 17:02
@snnn @unbeatable-101 I also used `miniforge3` and ran into your issue, but I installed `flabuffers` with pip i.e `pip install flatbuffers' and had no issue running the build. Can you try to uninstall `numpy, flatbuffers` and `onnxrt` and start by installing `flatbuffers` and `numpy` and then try to install `onnxrt`?

**Comment by unbeatable-101** [comment] 2021-08-19 18:24
Just did that and still had an issue, so I ran the command with `-v -v -v`

[Terminal Saved Output.txt](https://github.com/microsoft/onnxruntime/files/7016989/Terminal.Saved.Output.txt)

**Comment by hossein1387** [comment] 2021-08-19 18:34
your numpy version is different from mine. I am using Python 3.9.5 with the following libs:

```
Package                Version            
---------------------- -------------------
flatbuffers            2.0
numpy                  1.21.0
onnx                   1.9.0
ort-nightly            1.8.2.dev169944
pip                    21.2.4
protobuf               3.17.3
setuptools             49.6.0.post20210108
six                    1.16.0

```

**Comment by mjamei** [comment] 2021-08-20 18:15
I have the same issue with `onnx` and `onnxmltools` packages. How did you install `onnx` on M1 @hossein1387 ?

**Comment by snnn** [comment] 2021-08-20 18:57
ONNX can be built from source. 

Try this command from onnx runtime source dir:
```
pushd .
cd cmake/external/protobuf
cmake ./cmake -DCMAKE_INSTALL_PREFIX=/tmp/protobuf -DCMAKE_POSITION_INDEPENDENT_CODE=ON -Dprotobuf_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Relwithdebinfo
make -j$(getconf _NPROCESSORS_ONLN)
make install
popd
export PATH=/tmp/protobuf/bin:$PATH
export ONNX_ML=1
export CMAKE_ARGS="-DONNX_GEN_PB_TYPE_STUBS=OFF -DONNX_WERROR=OFF"
python3 -m pip install numpy==1.16.6
popd
python3 -m pip install cmake/external/onnx
```

**Comment by hossein1387** [comment] 2021-08-20 19:00
@mjamei  I actually installed everything with `pypi`

**Comment by arielelkin** [comment] 2021-11-15 11:10
@snnn can you provide the arm64 binary of onnx runtime as a [release asset](https://github.com/microsoft/onnxruntime/releases) ?

**Comment by snnn** [comment] 2021-11-16 17:43
Nuget package and tarballs will be available there in the next release. Python... probably later.

**Comment by OlegTheCat** [comment] 2021-11-17 12:10
@snnn, thanks for working on this! Do you have any plans for adding arm64 binary to java assets?

**Comment by snnn** [comment] 2021-11-17 17:31
Will be available there in the next release

**Comment by Fohlen** [comment] 2021-11-30 21:37
Hey @snn when can we expect this to be regularly available at least in the nightly? (right now only very specific commits have the arm64)

**Comment by OlegTheCat** [comment] 2021-12-29 12:21
Hi @snnn! It seems that universal binary has not been added to the Java package in this (1.10) release:

```
$ jar xf ~/.m2/repository/com/microsoft/onnxruntime/onnxruntime/1.10.0/onnxruntime-1.10.0.jar

$ ls ai/onnxruntime/native
linux-x64 osx-x64   win-x64

$ lipo -archs ai/onnxruntime/native/osx-x64/libonnxruntime.dylib
x86_64
```

Is it something that has been missed?

**Comment by snnn** [comment] 2022-01-01 05:41
Yes, I should update https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/windows/jar_packaging.ps1.

**Comment by jinfagang** [comment] 2022-01-29 10:43
@snnn Does onnxruntime m1 version ready to publish to pypi?

**Comment by snnn** [comment] 2022-02-01 00:23
Not yet.

**Comment by jinfagang** [comment] 2022-02-01 08:45
@snnn I found ARM build version on my own side even slower than x86 version (Conda x86 python vs Miniforge amr64 python).

I don't know why

**Comment by aressem** [comment] 2022-02-17 08:04
Any ETA when `linux-aarch64` / `osx-aarch64` can be included in a released version of onnxruntime ?

**Comment by ZetiMente** [comment] 2022-03-10 17:25
> https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/windows/jar_packaging.ps1

Hi, it's now one month later. Is there any chance this will be soon? Please. 😀

**Comment by jinfagang** [comment] 2022-03-11 01:49
Hi, first quarter of 2022 are coming to end, is there any updates on arm M1 version?

**Comment by XavierGeerinck** [comment] 2022-03-16 12:38
I would also love to see an updated ARM M1 version on PyPi

**Comment by damienrj** [comment] 2022-04-01 17:33
Same, a lot of errors trying to install on m1.

**Comment by NiuGeng-SEU** [comment] 2022-04-08 11:50
Same, cannot find a way to deal with it.

**Comment by jinfagang** [comment] 2022-04-20 15:09
Hi, 100 years later, any m1 version onnxruntime? If not, how to build on my self? I don't know what's the command line to build with cmake enable arm64

**Comment by snnn** [comment] 2022-04-20 16:39
https://github.com/microsoft/onnxruntime/pull/8710/files 

f you want to cross-compile for Apple Silicon in an Intel-based MacOS machine, please add the argument `--cmake_extra_defines CMAKE_OSX_ARCHITECTURES=arm64` with cmake > 3.19

if you want to generate a [Universal2 Binary](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary), please use `--cmake_extra_defines CMAKE_OSX_ARCHITECTURES=x86_64;arm64`

**Comment by Fohlen** [comment] 2022-04-20 16:50
> Hi, 100 years later, any m1 version onnxruntime? If not, how to build on my self? I don't know what's the command line to build with cmake enable arm64

Please bear in mind that OSS in general, and ONNX in particular, is a project run by volunteers (in this case Microsoft volunteering their resources) and is available freely to the world. Smirky comments like '100 years later' are not only rude, they will discourage others from contributing, essentially harming everyone including yourself. Please refrain from such an attitude in the future.

That being said @snnn there are working wheels on the nightly version of this repository. What would be necessary to include them in ALL of the future nightly releases? Can we help by adding a PR? Once the coverage is sufficient it can then go from the nightly to stable.. what's preventing this from happening? A little insight here would be much appreciated

**Comment by snnn** [comment] 2022-04-20 17:35
Thanks for the understanding. I just had a discussion with our product team. The feature will be included in ONNX Runtime 1.12 release. @[mszhanyi](https://github.com/mszhanyi) will work on it. He will update the "MacOS_py_Wheels" build job in https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/azure-pipelines/templates/py-packaging-stage.yml  to include arm64. We should provide two types of wheels: one for x86_64, another for universal2.

**Comment by snnn** [comment] 2022-04-20 17:36
@faxu , would you please create a 1.12 project at https://github.com/microsoft/onnxruntime/projects ?

**Comment by faxu** [comment] 2022-04-20 19:09
https://github.com/microsoft/onnxruntime/projects/9

**Comment by andreaferretti** [comment] 2022-05-30 11:42
@snnn The packages you linked do not exist anymore, is there another way to install onnxruntime? Or maybe could you please provide updated packages?

**Comment by cansik** [comment] 2022-05-30 12:23
If you are interested in pre-built onnxruntime wheels for Mac M1 (Apple Silicon), I have created a replacement package called [onnxruntime-silicon](https://github.com/cansik/onnxruntime-silicon).

```
pip install onnxruntime-silicon
```

**Closed** 2022-06-07 15:58 UTC
Labels: type:enhancement, api:Python

**Comment by fxmarty** [comment] 2022-06-21 13:57
@cansik Out of curiosity, do you have any idea if this can be leveraged for quantization on Apple M1 chip? Or there is still an execution provider missing for this kind of hardware? Thanks!
