### ISSUE TITLE
Switch between providers

### ISSUE THREAD

**Issue by fumihwh** [microsoft/onnxruntime#486] opened 2019-02-17 08:46 UTC
Is there any way to run op in specific provider? or does priority of provider exist?

**Comment by snnn** [comment] 2019-02-19 19:00
Which API you are using? C/C++/Python?

**Comment by fumihwh** [comment] 2019-02-25 02:49
@snnn Python.

**Comment by linkerzhang** [comment] 2019-04-18 03:03
@fumihwh ONNXRUNTIME provides APIs to set execution provider in C/C++. Python does not have. Should be added. Will keep this open to track this task.

**Comment by faxu** [comment] 2019-05-15 23:40
@fumihwh : can you share some more details on your usage scenario? The python packages that are released are only built for single execution providers right now.

**Comment by jinfagang** [comment] 2019-09-17 05:42
Does specific providers available now in onnxruntime python?

Otherwise we have to installed 2 different environments in order to switch between CPU and GPU as backend.

**Comment by snnn** [comment] 2019-09-17 05:44
@jinfagang, sorry, not yet. we are working on that.

**Comment by pranavsharma** [comment] 2019-09-17 05:51
[This commit](https://github.com/microsoft/onnxruntime/commit/634f554471b5b838dcc52e0a00237a27fb718620) attempts to fix this.

**Comment by jinfagang** [comment] 2019-09-17 06:24
@pranavsharma this PR is good, will it merge?

**Comment by pranavsharma** [comment] 2019-09-17 06:39
This was merged 4 days back.

**Closed** 2019-10-11 21:52 UTC
Labels: enhancement

**Comment by leimao** [comment] 2019-10-25 17:54
Is there any documentation on how to switch between CPU and GPU runtime?

**Comment by ShaiBet** [comment] 2020-01-20 13:37
Is there a support from python to use GPU runtime at all?

**Comment by vladbph** [comment] 2020-09-14 23:07
> @fumihwh ONNXRUNTIME provides APIs to set execution provider in C/C++. Python does not have. Should be added. Will keep this open to track this task.

The issue is closed - does this mean API already supports switching between providers CPU and GPU?. Does python API supports it?

**Comment by bminixhofer** [comment] 2020-09-19 11:47
Yes, the Python API supports it:

https://github.com/microsoft/onnxruntime/blob/78a29aebbcbd0c3b6dab734f221e0f3bf1e24c97/onnxruntime/python/session.py#L49-L86

I just tried it. Before installing `onnxruntime-gpu`:

```python
In [1]: session.get_providers()                                                                                                                      
Out[1]: ['CPUExecutionProvider']
```

afterwards:

```python
In [1]: session.get_providers()                                                                                                                      
Out[1]: ['CUDAExecutionProvider', 'CPUExecutionProvider']
```

`"CUDAExecutionProvider"` being before CPU in the array means that onnxruntime will execute nodes with CUDA if capable and fallback to CPU if not. You can change the priority with `session.set_providers`.

**Comment by vladbph** [comment] 2020-09-20 05:05
Great, thank you!

**Comment by vladbph** [comment] 2020-09-23 17:49
> ```python
> session.get_providers()   
> ```

Well, the thing is the fallback must(?) happen regardless of presence/availability of GPU. But it is not.. It throws an exception if GPU is busy, thus cannot be allocated.
`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-19-3a7c99177e28> in <module>()
      1 # onnxruntime.SessionOptions()
----> 2 session = onnxruntime.InferenceSession( name )

1 frames
/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py in _load_model(self, providers)
    175             raise TypeError("Unable to load from type '{0}'".format(type(self._path_or_bytes)))
    176 
--> 177         self._sess.load_model(providers)
    178 
    179         self._sess_options = self._sess.session_options

RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:123 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:117 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 100: no CUDA-capable device is detected ; GPU=0 ; hostname=84fa395ab43d ; expr=cudaSetDevice(device_id_); `

**Comment by bminixhofer** [comment] 2020-09-25 11:34
Good point, that should probably be a separate issue.

**Comment by 9lan9** [comment] 2021-05-23 01:55
If I have 4 GPUS and run onnx in gunicorn, all 4 workers would run in just one GPU, how to allocate these GPUs to workers?

**Comment by hurun** [comment] 2021-06-27 08:49
> If I have 4 GPUS and run onnx in gunicorn, all 4 workers would run in just one GPU, how to allocate these GPUs to workers?

hello, could you share how to run onnx in gunicorn. i can run onnx in flask, but in gunicorn is error.thanks
