### ISSUE TITLE
Handle the case where there is only one core in the machine.

### ISSUE THREAD

**Issue by HarryVancao** [microsoft/onnxruntime#1135] opened 2019-05-30 19:31 UTC
**Describe the bug**
I get a floating exception whenever I run a simple model that is just one convolution layer. I am running an onnx file generated by MATLAB. 

I was able to view the stacktrace of the exception with gdb. It seems to crash in a function called MlasSgemmTryMultithread

Since this points to something relating to concurrency, I tried running the same model while setting the session_thread_pool_size parameter to 1. This allows the model to run to completion without problems. 

Is this a known issue? I couldn't find any open issue relating to this crash. 

**System information**
- OS Platform and Distribution: Linux Debian 9 
- ONNX Runtime installed from: Binary
- ONNX Runtime version: 0.4.0
- Python version: 3.5

**To Reproduce**
Python script: 
import onnxruntime as rt
import numpy as np

sessionOptions = rt.SessionOptions()
#sessionOptions.session_thread_pool_size = 1 # uncomment to successfully run. 
session = rt.InferenceSession("convOnly.onnx", sess_options=sessionOptions);
input_name = session.get_inputs()[0].name 
input = 10 * np.ones((1, 3, 5, 5), dtype = "single")
print("starting prediction: ")
prediction = session.run(None, {input_name : input} )
print(prediction)

I am attaching the script and the onnx file to this issue:
[floatingExceptionReproduction.zip](https://github.com/microsoft/onnxruntime/files/3238462/floatingExceptionReproduction.zip)

**Expected behavior**
I would expect the session to run inference without any crash. In addition, according to the Python API [documentation](https://microsoft.github.io/onnxruntime/api_summary.html#onnxruntime.SessionOptions.enable_sequential_execution) I would think sequential execution is enabled by default.

**Comment by pranavsharma** [comment] 2019-05-31 03:16
Can't seem to reproduce this. See below.

```
pranav@pranav-HP-Z440-Workstation:~/floatingExceptionReproduction$ ls
convOnly.onnx  runConvOnly.py
pranav@pranav-HP-Z440-Workstation:~/floatingExceptionReproduction$ python runConvOnly.py
starting prediction:
[array([[1.0144626 , 0.9901579 , 0.999256  , 0.9900844 , 0.9937369 ,
        1.0026965 , 0.99749196, 1.0054768 , 1.0004812 , 0.97975045,
        0.9988375 , 0.9821757 , 1.0064821 , 1.0099634 , 1.0035425 ,
        1.0028011 , 1.0231298 , 1.0103304 , 0.9999087 , 0.98822653,
        1.0022982 , 0.995719  , 1.0056947 , 0.9950074 , 1.0064964 ,
        0.99475616, 1.0123382 , 1.0112967 , 1.003298  , 0.99383736,
        1.0020671 , 0.99677026]], dtype=float32)]
pranav@pranav-HP-Z440-Workstation:~/floatingExceptionReproduction$ cat runConvOnly.py
import onnxruntime as rt
import numpy as np


sessionOptions = rt.SessionOptions()
#sessionOptions.session_thread_pool_size = 1 # uncomment to prevent crash
session = rt.InferenceSession("convOnly.onnx", sess_options=sessionOptions);
input_name = session.get_inputs()[0].name
input = 10 * np.ones((1, 3, 5, 5), dtype = "single")
print("starting prediction: ")
prediction = session.run(None, {input_name : input} )
print(prediction)
```

**Comment by HarryVancao** [comment] 2019-05-31 03:27
Hi Pranav, 

Thanks for investigating. However, that is a bit odd. I can try to investigate a little further on my end. Is there debugging step that I could try? One thing to note is that I am running Debian on a VM. Do you think that this could cause the issue? 

Harry

**Comment by pranavsharma** [comment] 2019-05-31 05:40
Something seems to be wrong in your VM. I tried on Debian 9 as well and it works just fine. See below.

```
pranav@debian:~$ uname -a
Linux debian 4.19.0-0.bpo.4-cloud-amd64 #1 SMP Debian 4.19.28-2~bpo9+1 (2019-03-27) x86_64 GNU/Linux

pranav@debian:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

pranav@debian:~$ python3 runConvOnly.py
starting prediction:
[array([[1.0144626 , 0.9901579 , 0.999256  , 0.9900844 , 0.9937369 ,
        1.0026965 , 0.99749196, 1.0054768 , 1.0004812 , 0.97975045,
        0.9988375 , 0.9821757 , 1.0064821 , 1.0099634 , 1.0035425 ,
        1.0028011 , 1.0231298 , 1.0103304 , 0.9999087 , 0.98822653,
        1.0022982 , 0.995719  , 1.0056947 , 0.9950074 , 1.0064964 ,
        0.99475616, 1.0123382 , 1.0112967 , 1.003298  , 0.99383736,
        1.0020671 , 0.99677026]], dtype=float32)]

pranav@debian:~$ ls
convOnly.onnx  floatingExceptionReproduction.zip  runConvOnly.py

pranav@debian:~$ cat runConvOnly.py
import onnxruntime as rt
import numpy as np


sessionOptions = rt.SessionOptions()
#sessionOptions.session_thread_pool_size = 1 # uncomment to prevent crash
session = rt.InferenceSession("convOnly.onnx", sess_options=sessionOptions);
input_name = session.get_inputs()[0].name
input = 10 * np.ones((1, 3, 5, 5), dtype = "single")
print("starting prediction: ")
prediction = session.run(None, {input_name : input} )
print(prediction)
```

**Comment by pranavsharma** [comment] 2019-05-31 05:41
Closing as per above comment.

**Comment by HarryVancao** [comment] 2019-05-31 12:50
Hi Pranav, 

Thanks for trying to reproduce again. As per your comment, I created a new VM running Debian 9 and it works now. Once difference that I noticed is that the new VM that I created has multiple CPU cores. Whereas my crashing VM only had one. I am speculating, but I this might be related. 

I will let you know if I have more time to investigate the issue. But for now, lets keep this closed until I can lock down better reproduction. 

Thanks, 
Harry

**Comment by HarryVancao** [comment] 2019-05-31 16:52
Hi  @pranavsharma 

I apologize for the continued comments in this issue. I am convinced that the floating point exception is caused by the VM having only one physical core available to it. I modified my existing VM to have 4 virtual processors (from 1) and inference runs without issue now. However, reverting back to 1 virtual processor restores the exception. 

Please let me know if you are able to reproduce this exception. 

Harry

**Comment by pranavsharma** [comment] 2019-05-31 20:31
I am able to reproduce on a 1-core machine. Will follow up with a fix.

**Comment by pranavsharma** [comment] 2019-06-04 05:47
@shschaefer mentioned today that he'll be taking care of this as part of his threading related PR.

**Comment by pranavsharma** [comment] 2019-06-19 07:07
This is being taken care of in this PR https://github.com/microsoft/onnxruntime/pull/1197

**Comment by HarryVancao** [comment] 2019-11-08 19:11
Any update on this?

**Comment by pranavsharma** [comment] 2019-11-08 20:09
This has already been resolved.

**Closed** 2019-12-17 18:22 UTC
Labels: bug, pending
