### ISSUE TITLE
Tensorflow BERT with onnxruntime is 338x slower than vanilla tensorflow on CPU.

### ISSUE THREAD

**Issue by mwakaba2** [microsoft/onnxruntime#8385] opened 2021-07-14 16:03 UTC
**Describe the bug**
Hi! I was running some benchmark tests to compare inference engine performances using multiple threads. More specifically, I was comparing the vanilla tensorflow BERT model's inference performance with onnx converted tensorflow BERT model's performance with the provided benchmark.py script, and I noticed the onnx converted model was significantly slower. I did not see this slowness for single thread inference, and onnxruntime is faster than vanilla in this case. 
However, inference is much slower when using multiple threads. I'd like to understand what may be happening here. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): [Google Cloud's n2-standard-16 instance with Intel Deep Learning Boost Instructions](https://cloud.google.com/compute/docs/general-purpose-machines#n2_machines)
- CPU count: 16 logical cores, 8 cpu cores
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: onnxruntime-openmp==1.7.0
- Python version: "3.7.10.final.0 (64 bit)"

**To Reproduce**
Dockerfile I'm using:
```Dockerfile
# Install TF entreprise
FROM gcr.io/deeplearning-platform-release/tf2-cpu.2-5:latest
WORKDIR /workspace
ENV OMP_ENABLED=true
ENV OMP_WAIT_POLICY='ACTIVE'

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --upgrade torch==1.8.1+cpu -f https://download.pytorch.org/whl/torch_stable.html && \
    pip install coloredlogs sympy onnx tf2onnx onnxruntime-openmp==1.7.0 transformers==4.6.0 py-cpuinfo py3nvml

COPY ./run_openmp_benchmark.sh /workspace/
COPY ./bert-base-uncased /workspace/bert-base-uncased

# Add onnxruntime customized benchmark scripts from https://github.com/mwakaba2/onnxruntime/tree/benchmark-bert-base-uncased
ADD onnxruntime_benchmark.tar.gz /workspace

CMD [ "./run_openmp_benchmark.sh" ]
```
Script I'm using to run the benchmark.py
https://gist.github.com/mwakaba2/7b88de0157a32f1edf23e058e061c945

**Expected behavior**
The onnx converted model will be faster than the vanilla tensorflow. I confirmed for onnx converted Pytorch BERT, it was faster than regular torchscript/torch BERT with multiple threads. 

**Benchmarks**
### Vanilla Tensorflow results
<google-sheets-html-origin><style type="text/css"></style>

engine | model_source | version | intra_op_num_threads | device | precision | optimizer | io_binding | model_name | inputs | batch_size | sequence_length | datetime | test_times | QPS | average_latency_ms | latency_variance | latency_90_percentile | latency_95_percentile | latency_99_percentile | OMP_NUM_THREADS | OMP_WAIT_POLICY | OMP_ENABLED | inter_op_num_threads
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
tensorflow | tf | 2.5.0 | 4 | cpu | fp32 |   |   | bert-base-uncased | 1 | 1 | 128 | 2021-06-17 20:09:19 | 100 | 10.58 | 94.56 | 0.01 | 98 | 99.46 | 101.39 | 4 | ACTIVE | TRUE | 1

### Onnx converted Tensorflow results

<google-sheets-html-origin><style type="text/css"></style>

engine | model_source | version | intra_op_num_threads | device | precision | optimizer | io_binding | model_name | inputs | batch_size | sequence_length | datetime | test_times | QPS | average_latency_ms | latency_variance | latency_90_percentile | latency_95_percentile | latency_99_percentile | OMP_NUM_THREADS | OMP_WAIT_POLICY | OMP_ENABLED | inter_op_num_threads
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
onnxruntime | tf | 1.7.0 | 4 | cpu | fp32 | TRUE | TRUE | bert-base-uncased | 1 | 1 | 128 | 2021-06-17 18:16:32 | 100 | 0.03 | 31918.44 | 5.17 | 32014.79 | 32035.27 | 32107.81 | 4 | ACTIVE | TRUE | 1

**Additional context**
The model is not a custom model and is "bert-base-uncased".
I modified the benchmark.py script, but I haven't made large changes to the onnxruntime conversion or runtime session area. 
https://github.com/mwakaba2/onnxruntime/tree/benchmark-bert-base-uncased

**Comment by wangyems** [comment] 2021-07-15 01:44
Hi @mwakaba2, Could you try the latest ORT(1.8)? the default package uses thread pool instead of OMP since 1.8.0 as it provides optimal performance for most of models.

**Comment by mwakaba2** [comment] 2021-07-15 15:27
Hi @wangyems ! Thanks for the quick reply. Sure! I can try that and report back.

**Comment by mwakaba2** [comment] 2021-07-19 15:47
Hi @wangyems I tested with the latest package and the slowdown is much less. 

However, onnxruntime is still slow compared to vanilla Tensorflow (2x - 14x slower). I'm comparing Google's v2.5 Enterprise tensorflow version (internally uses OMP) with onnx converted Tensorflow models (v1.8.1).  Is this expected?

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-ee281904-7fff-0da9-a427-90765aa36c5b"><div dir="ltr" style="margin-left:-57.75pt;" align="left">

Model Description | intra_op_num_threads | QPS | Average Latency (p50) | P90 Latency | P95 Latency | P99 Latency
-- | -- | -- | -- | -- | -- | --
Vanilla tensorflow | 4 | 10.29 | 97.22 | 0.02 | 102.62 | 103.41
Vanilla tensorflow | 8 | 9.62 | 103.92 | 0.04 | 113.77 | 115.77
Vanilla tensorflow | 2 | 7.29 | 137.21 | 0.02 | 144.09 | 145.23
Onnx conversion + dynamic quantization | 2 | 5.08 | 197.03 | 0.06 | 205.95 | 207.75
Onnx conversion + dynamic quantization | 4 | 2.57 | 389.68 | 0.27 | 409.97 | 416.14
Onnx conversion | 2 | 2.27 | 440.32 | 0.13 | 457.13 | 460.24
Onnx conversion + dynamic quantization | 8 | 1.25 | 799.33 | 0.63 | 832.22 | 836.45
Onnx conversion | 4 | 1.22 | 822.81 | 0.63 | 850.66 | 861.56
Tensorflow lite + dynamic quantization | 2 | 1.01 | 989.32 | 0.06 | 1000.73 | 1003.17
Tensorflow lite + dynamic quantization | 4 | 1.01 | 990.11 | 0.05 | 999.35 | 1003.44
Tensorflow lite + dynamic quantization | 8 | 1.01 | 994.06 | 0.09 | 1007.49 | 1013.89
Onnx conversion | 8 | 0.68 | 1471.27 | 3.52 | 1552.69 | 1563.76

</div></b>

**Comment by wangyems** [comment] 2021-07-19 18:16
Thanks @mwakaba2 for the report! I'll take a closer look

**Comment by wangyems** [comment] 2021-07-20 07:15
Hi @mwakaba2, here are something I found:

1. I was able to reproduce the bad performance using your docker with gcr.io/deeplearning-platform-release/tf2-cpu.2-5:latest. If you take a closer look, this docker image has some environment pre-installed:
       KMP_AFFINITY=granularity=fine,verbose,compact,1,0
       KMP_BLOCKTIME=0
       KMP_INIT_AT_FORK=FALSE
       KMP_SETTINGS=1
  What you can do is to unset those variables from your container(just for onnxruntime run) by:
       unset KMP_AFFINITY
       unset KMP_BLOCKTIME
       unset KMP_INIT_AT_FORK
       unset KMP_SETTINGS
  Then you should be able to get a better-than-tensorflow performance from onnxruntime

2. It's expected that pytorch-converted onnx has a better performance than tf-converted onnx. The reason is that our transformers optimizer misses some of the fusions in tf-converted onnx graph. We will support them in ORT 1.9 release.

3. I didn't notice that there is a perf regression in ORT 1.8 compared with 1.7 in my environment.

**Comment by mwakaba2** [comment] 2021-07-20 13:29
@wangyems Thanks so much for taking the time to reproduce the results!

1. I'll try unsetting the env variables for onnxruntime and share my results. Just curious, did you see the environment variables in the deep learning image Dockerfile? If so, do you have a link to it?

2. Makes sense. Thanks for the clarification! I look forward to the ORT 1.9 release!

3. To clarify, I have OMP_NUM_THREADS set to 8 threads and using N2 instances on GCP (n2-standard-16). These instances support Intel Advanced Vector Extensions 512 (Intel AVX-512) and Intel Deep Learning boost (Intel DL Boost) which boosts int8 performance. This might not be an issue if I unset the environment variables, so I'll check the pytorch results too.

**Comment by wangyems** [comment] 2021-07-20 18:39
> @wangyems Thanks so much for taking the time to reproduce the results!
> 
> 1. I'll try unsetting the env variables for onnxruntime and share my results. Just curious, did you see the environment variables in the deep learning image Dockerfile? If so, do you have a link to it?
> 2. Makes sense. Thanks for the clarification! I look forward to the ORT 1.9 release!
> 3. To clarify, I have OMP_NUM_THREADS set to 8 threads and using N2 instances on GCP (n2-standard-16). These instances support Intel Advanced Vector Extensions 512 (Intel AVX-512) and Intel Deep Learning boost (Intel DL Boost) which boosts int8 performance. This might not be an issue if I unset the environment variables, so I'll check the pytorch results too.

Regarding the your question in 1, I saw those variables during the tensorflow run, didn't attempt to find deep learning image Dockerfile. Those env variables catch my attentions since I was not able to reproduce the slow perf on onnx without using the docker.

**Comment by mwakaba2** [comment] 2021-07-20 21:29
@wangyems Unsetting the env variables fixed it! The onnxruntime is 2x faster than the vanilla tensorflow model. 🙂
As for the pytorch model performance, the latest onnxruntime is 1.17x slower than executing with the openmp package.

**Comment by wangyems** [comment] 2021-07-20 21:59
@mwakaba2 Cool! I'll dig a bit more with the 1.8 vs 1.7 openmp on pytorch-converted onnx. Thanks for reporting the performance. Closing this issue now, feel free to reopen if you have more questions.

**Closed by wangyems** 2021-07-20 21:59 UTC

**Comment by mwakaba2** [comment] 2021-07-21 14:07
Hi @wangyems
>Cool! I'll dig a bit more with the 1.8 vs 1.7 openmp on pytorch-converted onnx. 

Thank you! I'd appreciate that. 🙂 Is there a github issue I can watch for the onnx pytorch model performance on onnxruntime v1.8 vs v1.7?

**Comment by wangyems** [comment] 2021-07-21 16:57
> Hi @wangyems
> 
> > Cool! I'll dig a bit more with the 1.8 vs 1.7 openmp on pytorch-converted onnx.
> 
> Thank you! I'd appreciate that. 🙂 Is there a github issue I can watch for the onnx pytorch model performance on onnxruntime v1.8 vs v1.7?

You can track here: https://github.com/microsoft/onnxruntime/issues/8453
