### ISSUE TITLE
ONNX 1.12 causes test_dequantizelinear_cpu / test_quantizelinear_cpu to fail on DirectML EP

### ISSUE THREAD

**Issue by garymm** [microsoft/onnxruntime#11902] opened 2022-06-18 16:33 UTC
Updating the ONNX submodule to 1.12 causes `OnnxBackendNodeModelTest.test_quantizelinear_cpu` to fail on the DirectML EP.

See https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=672289&view=logs&jobId=3032dfba-5baf-5872-0871-2e69cb7f4b6a&j=3032dfba-5baf-5872-0871-2e69cb7f4b6a&t=be0c222b-b353-5c22-b68c-b60841755bcf

We need this fixed ASAP as we need to update to ONNX 1.12 for the ONNX Runtime 1.12 release.

@fdwr could you please take a look or help find someone who can?

**Comment by fdwr** [comment] 2022-06-19 00:47
@jeffbloo

**Comment by fdwr** [comment] 2022-06-19 01:27
@garymm We'll try to reproduce this locally. In the mean time, does the Python test suite support EP-specific exclusions to unblock you? I see some already excluded tests `['^test_(blackmanwindow|dft|hammingwindow..`, and I believe ORT's C++ based ONNX backend tests support EP-specific exclusions.

**Comment by fdwr** [comment] 2022-06-19 02:01
Seems ONNX changed its behavior between opsets, as the otherwise identical model passed previously. Opset 13 now returns `axis` = 1, even when the model doesn't actually contain an `axis` attribute and even when no per-tensor/layer broadcasting applies. See there is no `axis` attribute in the actual model file...

```
ir_version: 7
producer_name: "backend-test"
graph {
  node {
    input: "x"
    input: "y_scale"
    input: "y_zero_point"
    output: "y"
    op_type: "QuantizeLinear"
  }
  name: "test_quantizelinear"
  input {
    name: "x"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 6
          }
        }
      }
    }
  }
  input {
    name: "y_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  input {
    name: "y_zero_point"
    type {
      tensor_type {
        elem_type: 2
        shape {
        }
      }
    }
  }
  output {
    name: "y"
    type {
      tensor_type {
        elem_type: 2
        shape {
          dim {
            dim_value: 6
          }
        }
      }
    }
  }
}
opset_import {
  domain: ""
  version: 13
}
```

...but the DML EP validates the axis attribute for the 1D tensor, and since 1 >= 1, it fails.

**Comment by garymm** [comment] 2022-06-20 15:44
@fdwr because `y_scale` is a scalar, `axis` should be ignored:

From the [spec](https://github.com/onnx/onnx/blob/main/docs/Operators.md#QuantizeLinear):

> axis : int (default is 1)
(Optional) The axis of the quantization dimension of the input tensor. Ignored for per-tensor quantization.

And per-tensor quantization is indicated by a scalar value of `y_scale`:

> y_scale : tensor(float)
Scale for doing quantization to get 'y'. It can be a scalar, which means per-tensor/layer quantization, or a 1-D Tensor for per-axis quantization.

So the EP should not be checking `axis` in this case.

**Comment by fdwr** [comment] 2022-06-20 18:04
Fixed in https://github.com/microsoft/onnxruntime/pull/11906/files.

**Closed by fdwr** 2022-06-20 18:04 UTC
Labels: release:1.12
