### ISSUE TITLE
Installation issue in windows10 RS4 with py3.6 (both CPU and CUDA)

### ISSUE THREAD

**Issue by ssgwos** [Microsoft/onnxruntime#247] opened 2018-12-23 03:14 UTC
pip install onnxruntime
Requirement already satisfied: onnxruntime in c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages (0.1.4)

python -c "import onnxruntime"
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\onnxruntime\capi\_pybind_state.py:12: UserWarning: Cannot load onnxruntime.capi. Error: 'DLL load failed: The specified module could not be found.'
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'".format(str(e)))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\onnxruntime\__init__.py", line 21, in <module>
    from onnxruntime.capi._pybind_state import RunOptions, SessionOptions, get_device, NodeArg, ModelMetadata
ImportError: cannot import name 'RunOptions'

**Comment by pranavsharma** [comment] 2019-01-02 19:41
Duplicate of #251

**Closed by pranavsharma** 2019-01-02 19:41 UTC

**Comment by ssgwos** [comment] 2019-01-05 21:52
PATH=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;
