### ISSUE TITLE
Upsample not matching numbers in linear mode

### ISSUE THREAD

**Issue by lara-hdr** [microsoft/onnxruntime#1179] opened 2019-06-06 18:31 UTC
**Describe the bug**

Numbers are not matching with Upsample in "linear" mode ("nearest" mode works fine) in opset_version 9 (and might have the same issue with Resize for opset_version 10).

I have a simple ONNX graph with a single upsample node.

The input has a size of (1, 1, 2, 2):
input = [[[[1, 2], [3, 4]]]]

The scale is:
scale = [1, 1, 2, 2]

The mode is "linear".

the expected output is: 
expected_output = 
[[[[ 1, 1.25, 1.75, 2],
   [ 1.5, 1.75, 2.25, 2.5],
   [ 2.5, 2.75, 3.25, 3.5],
   [3, 3.25, 3.75, 4]]]]

The output I get with ONNXRuntime is:
output = 
[[[[ 1, 1.5, 2, 3],
   [ 2, 2.5, 3, 3],
   [ 3, 3.5, 4, 4],
   [2, 3.5, 4, 4]]]]

**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): build from source
- ONNX Runtime version:  commit id eda4c5cb47379e053e9a49caec5f1deba1181ad7
- Python version: 3.7.2

**Comment by lara-hdr** [comment] 2019-06-06 18:58
[model.zip](https://github.com/microsoft/onnxruntime/files/3263062/model.zip)

**Comment by hariharans29** [comment] 2019-06-06 20:09
Hi @lara-hdr ,

1) The input test data provided by you above seems to be the exact same as the `upsample_linear` test 
    here - https://github.com/onnx/onnx/blob/rel-1.5.0/docs/Operators.md#Resize. The expected output 
    there doesn't match your `expected_output`. Seems like there is a gap in expectation.

2) I ran separate unit tests for `Upsample (9)` and `Resize (10)` and they both aligned with the output in the ONNX spec (which is different from the ORT output pasted above). The actual output from ORT is - 

1.0f, 1.5f, 2.0f, *2.0f*,
2.0f, 2.5f, 3.0f, 3.0f,
3.0f, 3.5f, 4.0f, 4.0f,
*3.0f*, 3.5f, 4.0f, 4.0f

Closing this as this seems to be by design.

Thanks

**Closed by hariharans29** 2019-06-06 20:09 UTC
Labels: bug

**Comment by fdwr** [comment] 2019-08-17 02:32
@lara-hdr - your expected results are the proper ones [[1, 1.25, 1.75, 2], ...] from an imaging perspective, which should favor the pixel centers when resampling to reduce bias. ONNX runtime currently defaults to "asymmetric" mapping, which gives what Hari shows. Unfortunately the ONNX spec was ambiguous on this previously, but now the Resize operator specification (for ONNX 1.6, in master now) defaults more properly to "half_pixel" (which is also what DirectML defaults to).
