### ISSUE TITLE
 [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node BatchNormalization(6)

### ISSUE THREAD

**Issue by dashesy** [Microsoft/onnxruntime#967] opened 2019-05-03 18:28 UTC
**Describe the bug**
Try an inference session with older model

```python
sess = rt.InferenceSession("old_tag.onnx")
```

> RuntimeError: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node BatchNormalization(6)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu16
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 0.4.0
- Python version: 3.6

**To Reproduce**
Describe steps/code to reproduce the behavior:

**Expected behavior**
Backward compatibility, or update changelog tot mention breaking change

**Additional context**

**Comment by hariharans29** [comment] 2019-05-03 18:50
Hi @dashesy,

Is your model an opset 6 conformant model ? It seems to be looking for a BatchNormalization node with opset version 6. [Here](https://github.com/Microsoft/onnxruntime/blob/master/docs/Versioning.md), under the section "Backwards compatibility", it says "All versions of ONNX Runtime will support ONNX opsets all the way back to (and including) opset version 7". So, I think this is expected.

**Comment by hariharans29** [comment] 2019-05-03 19:14
Closing as it seems this is by design since opset 6 is not supported per the versioning doc. Please feel free to re-open if you feels this was incorrectly interpreted.

**Closed by hariharans29** 2019-05-03 19:14 UTC
