### ISSUE TITLE
Error running onnxruntime_training_mnist on CPU (possibly error in GemmGrad )

### ISSUE THREAD

**Issue by georgen117** [microsoft/onnxruntime#7506] opened 2021-04-29 21:10 UTC
**Describe the bug**
When running onnxruntime_training_mnist sample the training will fail with the following error:

```
Loading MNIST data from folder C:\Users\georgena\workspace\mnist\mnist_data\
Preparing data ...
Preparing data: done
#training set size = 60000
#test set size = 10000
2021-04-29 12:13:20.0880944 [W:onnxruntime:Default, graph.cc:84 onnxruntime::MergeShapeInfo] Error merging shape info for output. 'loss' source:{} target:{1}. Falling back to lenient merge.
Fail: This is an invalid model. Error in Node:Gemm_token_2_Grad/Gemm_1 : Node (Gemm_token_2_Grad/Gemm_1) has input size 2 not in range [min=3, max=3].
```

**Urgency**
This bug is hindering the development of training ops on the DnnlExecutionProvider.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04, and Windows 10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version:  HEAD of master (commit 34ebf7d3dd32e14295a409db08a667d6d236aeb6)
- Python version: python 3.8.3 
- Visual Studio version (if applicable): Visual C++ 2019 Version 16.7.7
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
- CUDA/cuDNN version: N/A
- GPU model and memory: mnist training model

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

Download the mnist model and training data:
Mnist 10K data set.
https://github.com/microsoft/onnxruntime/files/4553416/mnist.zip
unzip to known location `C:\mnist` or `~\mnist`

build onnxruntime for training CPU

on windows:
.\build.bat --config RelWithDebInfo --parallel  --build_shared_lib --cmake_generator "Visual Studio 16 2019" --enable_training

on linux:
./build.sh --config RelWithDebInfo --parallel  --build_shared_lib --enable_training 

goto build folder run the sample:
Windows:
```
.\onnxruntime_training_mnist.exe --model_name C:\mnist\mnist_gemm --train_data_dir C:\mnist\mnist_data\
```

Linux:
```
./onnxruntime_training_mnist.exe --model_name ~/mnist/mnist_gemm --train_data_dir ~/mnist/mnist_data/
 ```

Also fails with Convolution model:
```
.\onnxruntime_training_mnist.exe --model_name C:\mnist\mnist_conv --train_data_dir C:\mnist\mnist_data\ --model_type conv
```

**Expected behavior**
Run training to completion:
  - with approximately 90% accuracy for the Gemm model
  - with approximately 95% accuracy for the Conv model

**Screenshots**

**Additional context**

Issue did not exist at this commit:
```
commit 3b16afc0db90a676efef3ce270978a406b3855fa
Author: Pranav Prakash <pranav-prakash@users.noreply.github.com>
Date:   Mon Apr 5 17:05:20 2021 -0700

    Make dW optional for convgrad (#7083)
```

I have not had a chance to run a git bisect yet to identify the first commit that has the issue.

**Comment by mrry** [comment] 2021-04-29 21:11
@kit1980 This looks like exactly the same issue you just hit (and I believe have a fix for?).

**Comment by kit1980** [comment] 2021-04-29 21:19
@mrry I think my issue is different, but probably related.
I'll take a look.

**Comment by georgen117** [comment] 2021-04-29 22:55
I used git bisect to find the first instance of the bug and narrowed it down to the following commit.
```
commit 25e261f1961b968acb1d6e25f18699729707ccc1
Author: Derek Murray <Derek.Murray@microsoft.com>
Date:   Tue Apr 6 16:49:34 2021 -0700

    Avoid passing zero bias to Gemm in gradients (#7244)

    * Avoid passing zero bias to Gemm in gradients

    The bias argument to Gemm is optional and defaults to zero. Therefore we do not need to generate zero initializers and pass them to that argument.

    * Remove unused declaration.

 .../orttraining/core/graph/gradient_builder.cc     | 38 +++++++---------------
 1 file changed, 12 insertions(+), 26 deletions(-)
```

**Comment by georgen117** [comment] 2021-08-11 22:35
I think I may have inadvertently stumbled on the possible cause of this issue.

Gemm defines the 3rd input C as optional.

While doing some testing of a Gemm implementation I removed the C input.

The error I got was This is an invalid model. Error in Node:node1 : Node (node1) has input size 2 not in range [min=3, max=3].

It looks like the graph generation for Gemm may not be properly handling the optional input C.
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Gemm

I don't know if the graph generation would also affect the gradient op as well but I suspect it is possible.

**Comment by kit1980** [comment] 2021-08-12 23:15
@georgen117
Have you created the new issue?
What was the ONNX opset version for the model? For older opsets the 3rd Gemm input was mandatory.

**Comment by kit1980** [comment] 2021-08-12 23:28
@georgen117
OK, I think I figured this out.
The issue is that the model from https://github.com/microsoft/onnxruntime/files/4553416/mnist.zip has ONNX opset 10.
For Gemm, the 3rd input is optional only since opset 11.
PR https://github.com/microsoft/onnxruntime/pull/7244 assumes "The bias argument to Gemm is optional and defaults to zero", so it implicitly assumes that opset is greater or equal than 11.

One way to resolve this is to load ONNX models from https://github.com/microsoft/onnxruntime/files/4553416/mnist.zip via ONNX Python API and re-save with a newer opset.

**Comment by georgen117** [comment] 2021-08-13 16:10
@kit1980
> Have you created the new issue?

Not yet. I plan on doing it today.  I wanted to take the time to make clear reproduction steps

> What was the ONNX opset version for the model? For older opsets the 3rd Gemm input was mandatory.

The issue with Gemm was reproduced using the unit tests.  I assumed the unit tests are the latest opset version. (Please correct me if I am wrong) I just commented out the one of the C inputs in the unit test and that reproduced the issue.

>One way to resolve this is to load ONNX models from https://github.com/microsoft/onnxruntime/files/4553416/mnist.zip via ONNX Python API and re-save with a newer opset.

I will give this a try.  It would be really great to be able to use the mnist training sample again it was really valuable as we added backward ops to our execution provider.

**Comment by kit1980** [comment] 2021-08-13 23:28
I replied to https://github.com/microsoft/onnxruntime/issues/8737
The default opset for OpTester is 7, so the same cause.

**Comment by kit1980** [comment] 2021-09-01 21:37
@georgen117 
Do we share the understanding that the issue is cause by an old opset version?
What would be the best way to resolve/close this?

**Comment by kit1980** [comment] 2021-09-08 21:52
I'm closing this for now, feel free to re-open if needed.

**Closed by kit1980** 2021-09-08 21:52 UTC
Labels: component:training-core
