### ISSUE TITLE
TensorRT build failed.

### ISSUE THREAD

**Issue by xkszltl** [microsoft/onnxruntime#4625] opened 2020-07-26 23:23 UTC
**Describe the bug**

We have several "undefined reference" errors when building with TensorRT.
Seems cuBLAS is not added as a dependency of TensorRT, causing wrong order during link.
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/5203025/88491944-84bc3080-cfd9-11ea-93fa-1a4a274fc4ba.png">

Without TensorRT it builds fine.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.4.0
- Python version: 3.6.8
- GCC/Compiler version (if compiling from source): 8.3.1 (devtoolset-8)
- CUDA/cuDNN version: 11.0/8.0.0
- GPU model and memory: V100

**Comment by jywu-msft** [comment] 2020-07-28 14:29
Was this previously working and now you're hitting it with a new version of TensorRT/CUDA ? 
With onnxruntime latest master (which supports TensorRT 7.0), it doesn't hit this issue.

CMakeFiles/onnxruntime_test_all.dir/code/onnxruntime/onnxruntime/test/providers/cpu/tensor/unsqueeze_op_test.cc.o CMakeFiles/onnxruntime_test_all.dir/code/onnxruntime/onnxruntime/test/providers/cpu/tensor/upsample_op_test.cc.o CMakeFiles/onnxruntime_test_all.dir/code/onnxruntime/onnxruntime/test/providers/cpu/tensor/where_op_test.cc.o CMakeFiles/onnxruntime_test_all.dir/code/onnxruntime/onnxruntime/test/providers/dnnl/dnnl_execution_provider_test.cc.o CMakeFiles/onnxruntime_test_all.dir/code/onnxruntime/onnxruntime/test/shared_lib/test_inference.cc.o CMakeFiles/onnxruntime_test_all.dir/code/onnxruntime/onnxruntime/test/shared_lib/test_session_options.cc.o CMakeFiles/onnxruntime_test_all.dir/code/onnxruntime/onnxruntime/test/shared_lib/test_run_options.cc.o CMakeFiles/onnxruntime_test_all.dir/code/onnxruntime/onnxruntime/test/shared_lib/test_allocator.cc.o CMakeFiles/onnxruntime_test_all.dir/code/onnxruntime/onnxruntime/test/shared_lib/test_nontensor_types.cc.o CMakeFiles/onnxruntime_test_all.dir/code/onnxruntime/onnxruntime/test/shared_lib/test_model_loading.cc.o CMakeFiles/onnxruntime_test_all.dir/code/onnxruntime/onnxruntime/test/providers/test_main.cc.o CMakeFiles/onnxruntime_test_all.dir/cmake_device_link.o  -o onnxruntime_test_all  -L/code/onnxruntime/build/Linux/Release/mklml/src/project_mklml/lib  -L/code/onnxruntime/build/Linux/Release/dnnl/install/lib  -L/usr/lib/x86_64-linux-gnu/lib64  -L/usr/local/cuda/targets/x86_64-linux/lib -Wl,-rpath,/code/onnxruntime/build/Linux/Release/mklml/src/project_mklml/lib:/code/onnxruntime/build/Linux/Release/dnnl/install/lib:/usr/lib/x86_64-linux-gnu/lib64:/code/onnxruntime/build/Linux/Release libonnxruntime_test_utils.a libonnxruntime_session.a libonnxruntime_providers_cuda.a libonnxruntime_providers_dnnl.so libonnxruntime_providers_tensorrt.a libonnxruntime_optimizer.a libonnxruntime_providers.a libonnxruntime_util.a libonnxruntime_framework.a libonnxruntime_graph.a libonnxruntime_common.a libonnxruntime_mlas.a lib/libgtest.a lib/libgmock.a onnx/libonnx.a onnx/libonnx_proto.a external/protobuf/cmake/libprotobuf.a external/re2/libre2.a -lmklml_intel -ldnnl -lcublas -lcudnn -lcurand -lcufft external/nsync/libnsync_cpp.a -ldl external/onnx-tensorrt/libnvonnxparser_static.a onnx/libonnx_proto.a /usr/lib/x86_64-linux-gnu/libnvinfer.so /usr/lib/x86_64-linux-gnu/libnvinfer_plugin.so /usr/lib/x86_64-linux-gnu/libmyelin.so -lrt lib/libgtest.a -lpthread -lcudadevrt -lcudart
/code/cmake-3.14.3-Linux-x86_64/bin/cmake -E copy_directory /code/onnxruntime/onnxruntime/test/testdata /code/onnxruntime/build/Linux/Release/testdata
make[3]: Leaving directory '/code/onnxruntime/build/Linux/Release'
[100%] Built target onnxruntime_test_all
make[2]: Leaving directory '/code/onnxruntime/build/Linux/Release'
/code/cmake-3.14.3-Linux-x86_64/bin/cmake -E cmake_progress_start /code/onnxruntime/build/Linux/Release/CMakeFiles 0
make[1]: Leaving directory '/code/onnxruntime/build/Linux/Release'

**Comment by xkszltl** [comment] 2020-07-28 19:19
No. I remember having other issue when using trt7 and did not continue. This is my first try with trt8

**Comment by jywu-msft** [comment] 2020-08-03 02:29
can you provide more details on how to reproduce? build command etc.  you mentioned trt8 above, did you mean trt 7.1 ?
one strange thing with the undefined references you observed is those symbols are from cublasLt , not cublas.
onnxruntime itself doesn't directly depend on cublasLt. so we really shouldn't need to link against it for an indirect dependency.
do you happen to have multiple cuda versions installed on your system?

**Comment by xkszltl** [comment] 2020-08-03 16:46
Ah you're right, trt7.1
It's in a docker environment and I only have cuda 11.

My understanding is that ort should link to the entire dependency tree of share libs, not just direct ones.
`.so` doesn't tell you where it's dependencies come from, so you need to craft that by yourselves.
In cmake, there should be something like:
```
add_library(trt IMPORTED)
target_link_libraries(trt PRIVATE cublas)
target_link_libraries(ort trt)
```

**Comment by xkszltl** [comment] 2020-08-17 18:07
Any news about this issue?

**Comment by jywu-msft** [comment] 2020-08-17 23:22
we could never reproduce the issue you reported.
one update.
we added support for TRT 7.1.3 to ORT master and we confirmed https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/Dockerfile.tensorrt works. 
Can you try to build with the latest master with the build.sh script similar to the Dockerfile above? 
If it continues to repro, to help debug, can you provide a Dockerfile which can reproduce the issue?

**Comment by xkszltl** [comment] 2020-08-19 09:01
Same on master, will check about the dockerfile later.

**Comment by xkszltl** [comment] 2020-08-19 13:40
This seems to be CentOS-only issue. Ubuntu 18.04 works

**Comment by xkszltl** [comment] 2020-08-19 13:47
BTW when I try to install on Ubuntu this line failed:
https://github.com/microsoft/onnxruntime/blob/5eec4f66edbfd6441056eed837432a42e191dcd2/cmake/onnxruntime_providers.cmake#L296
Maybe someone forget to check in shared dir?

**Comment by xkszltl** [comment] 2020-08-21 07:08
@jywu-msft
I don't know why it works for you.
Could you check if your link command with `-lnvinfer_plugin` is followed by a cublasLt, or maybe the difference between generated Makefile/Ninja script happen to cover that?
Based on what I found there's no reference to any upstream (w.r.t. trt) dependency in onnx-tensorrt cmake, and `readelf -a` confirmed there's cublasLt symbols in libnvinfer_plugin, so it should not work (and I don't know why it works on your side).

For now the only solution I came up with is `-DCMAKE_{EXE,SHARED}_LINKER_FLAGS='-Xlinker --allow-shlib-undefined'`, which tells the linker to ignore this bug:
https://github.com/xkszltl/Roaster/commit/1c19614d109f2875cb12e626d0b445f11d7837b7

**Comment by jywu-msft** [comment] 2020-08-21 08:22
I had previously posted the full link command above https://github.com/microsoft/onnxruntime/issues/4625#issuecomment-665074722
there is no -lcubasLt
yeah, it's strange why this is encountered on centos but not ubuntu. 
other projects such as onnx-tensorrt directly from nvidia that link against nvinfer_plugin , don't need to additionally link cublasLt
e.g. see https://github.com/onnx/onnx-tensorrt/blob/master/CMakeLists.txt#L125 and https://github.com/onnx/onnx-tensorrt/blob/master/CMakeLists.txt#L138

we'll try to investigate further on centos when we have some spare cycles, but a Dockerfile for repro would definitely help expedite.

**Comment by xkszltl** [comment] 2020-08-21 08:40
Actually so far only ubuntu+master works without the fix, centos+master/centos+1.4/ubuntu+1.4 all failed, not sure if there's any randomness.

**Comment by jywu-msft** [comment] 2020-08-27 13:24
i don't think it's troublesome. i agree it could be hiding some underlying issue and should be investigated further.
we would need to spend some time on it to repro with CentOS, but currently we don't have spare cycles.  
i'm pretty certain it doesn't happen on Ubuntu so we would appreciate any help to repro/debug the issue.

**Comment by xkszltl** [comment] 2020-11-01 12:57
@jywu-msft
Any follow up after previous discussion?

**Comment by jywu-msft** [comment] 2020-11-02 19:00
> @jywu-msft
> Any follow up after previous discussion?

Unfortunately, not much change since my last update about not having had free cycles to investigate.
The issue has been prioritization vs other tasks. 
For Linux support, we rely on combination of official build process (using build.sh) along with Nvidia provided Docker base image (which is only provided for Ubuntu AFAIK)
are you blocked on this? I was under impression you had a workaround for cmake/centos per previous comments? 
We will revisit in next bugfix planning cycle.

**Comment by xkszltl** [comment] 2020-11-03 02:42
The workaround we applied is to force linking cublasLt to everything.
This kind of hotfix is temporary, we're still blocked in the long term.

This is not a "platform support" issue, it just happen to work for a particular linker and, even in this case, the result binary is still incorrect (containing missing symbols).
Given that the way of fix is clear (add cublasLt as dependency of trt), I don't know why it was de-prioritized.

Besides, we are seeing requests to run it on docker other than Ubuntu/CentOS.
I may be a good idea to improve official build/test coverage.

**Comment by xkszltl** [comment] 2020-11-03 03:20
BTW the official cuda docker already shipped to centos 7 and 8

**Comment by jywu-msft** [comment] 2020-11-03 04:19
As I mentioned, our ORT TensorRT EP dockerfile is based on nvidia's tensorrt base image (which is ubuntu)
so having a cuda base image does not help us here.
If nvidia publishes a centos image for TensorRT, then that would quickly change the situation. 
For the short term, we don't have resources to support an ORT TensorRT EP image based on centos cuda image. We can schedule that work if there is demand for it. Sounds like there is based on your comments.
It would be greatly appreciated if you can help contribute to centos efforts.
A repro (Dockerfile) for this issue on centos would be very helpful.

Btw, I'm not so sure the "way of fix is clear."
I provided an example previously from Nvidia's onnx-tensorrt repo where it does not need to explicitly link cublasLt.
Here are some more examples. 
All the TensorRT sample applications don't seem to link cublasLt either. All the other dependencies are same as what we have.
see https://github.com/NVIDIA/TensorRT/blob/master/samples/CMakeSamplesTemplate.txt#L84
interestingly they also have this line: https://github.com/NVIDIA/TensorRT/blob/master/samples/CMakeSamplesTemplate.txt#L113
which is the same as the --allow-shlib-undefined you tried previously.
The comment above it also calls out libnvinfer_plugin library specifically.
I don't know why we don't need this. Maybe because we don't actually use symbols from libnvinfer_plugin.
Again, this is why I am requesting a repro. It feels like our build environments are different and it would help us if we didn't have to reproduce an environment that is not our primary supported setup.

**Comment by jywu-msft** [comment] 2020-11-16 23:01
update on this.  I tested on centos 7 nvidia container and onnxruntime TensorRT EP builds without any issues.
here are the components I used
*  latest ORT master branch
*  nvidia/cuda:11.0-cudnn8-devel-centos7 image
*  TensorRT-7.1.3.4.CentOS-7.6.x86_64-gnu.cuda-11.0.cudnn8.0.tar.gz from nvidia tensorrt download page
*  gcc 8.3.1 from devtoolset-8
*  cmake 3.14.4
*  build command: ./build.sh --config Release --update --build --build_shared_lib --parallel --skip_submodule_sync --use_tensorrt --tensorrt_home /tensorrt/TensorRT-7.1.3.4 --cuda_home /usr/local/cuda --cudnn_home /usr

The old codebase from back in July had tensorrt ep as shared lib, but was implicitly linking tensorrt ep to onnxruntime_test_all
I think that might have caused some problems. with EP as shared lib, ORT will explicitly load EP shared libs.

**Comment by xkszltl** [comment] 2020-11-17 01:33
> Btw, I'm not so sure the "way of fix is clear."

You can blindly link to cublaslt if trt libs ask for it, just as what I did for workaround.
This is static info that you can see with `readelf -a`.
The first line already tells you `libnvinfer_plugin.so` **NEED** `libcublasLt.so`.
```
$ readelf -a /usr/lib/x86_64-linux-gnu/libnvinfer_plugin.so.7.2.1 | grep -i cublaslt
  0x0000000000000001 (NEEDED)       Shared library: [libcublasLt.so.11]
0000000000d61118  0000001900000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulDescSetAttribute@libcublasLt.so.11 + 0
0000000000d61278  0000003600000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatrixLayoutDestroy@libcublasLt.so.11 + 0
0000000000d612a8  0000003e00000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatrixLayoutSetAttribute@libcublasLt.so.11 + 0
0000000000d61358  0000005000000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtCreate@libcublasLt.so.11 + 0
0000000000d613b0  0000005600000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmul@libcublasLt.so.11 + 0
0000000000d61658  0000009900000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulAlgoInit@libcublasLt.so.11 + 0
0000000000d61668  0000009b00000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulAlgoCheck@libcublasLt.so.11 + 0
0000000000d61678  0000009d00000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtDestroy@libcublasLt.so.11 + 0
0000000000d616b8  000000a300000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulAlgoGetIds@libcublasLt.so.11 + 0
0000000000d61858  000000c600000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatrixLayoutCreate@libcublasLt.so.11 + 0
0000000000d618f8  000000d600000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulAlgoConfigGetAttribute@libcublasLt.so.11 + 0
0000000000d61a30  000000ee00000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulDescDestroy@libcublasLt.so.11 + 0
0000000000d61bc0  0000011500000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulPreferenceCreate@libcublasLt.so.11 + 0
0000000000d61c08  0000011a00000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulPreferenceDestroy@libcublasLt.so.11 + 0
0000000000d61c28  0000011e00000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulDescCreate@libcublasLt.so.11 + 0
0000000000d61c78  0000012500000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulAlgoCapGetAttribute@libcublasLt.so.11 + 0
0000000000d61cf0  0000012e00000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulPreferenceSetAttribute@libcublasLt.so.11 + 0
0000000000d61d60  0000013700000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulAlgoConfigSetAttribute@libcublasLt.so.11 + 0
    25: 0000000000000000     0 FUNC    GLOBAL DEFAULT   UND cublasLtMatmulDescSetAttribute@libcublasLt.so.11
    54: 0000000000000000     0 FUNC    GLOBAL DEFAULT   UND cublasLtMatrixLayoutDestroy@libcublasLt.so.11
    62: 0000000000000000     0 FUNC    GLOBAL DEFAULT   UND cublasLtMatrixLayoutSetAttribute@libcublasLt.so.11
    80: 0000000000000000     0 FUNC    GLOBAL DEFAULT   UND cublasLtCreate@libcublasLt.so.11
    86: 0000000000000000     0 FUNC    GLOBAL DEFAULT   UND cublasLtMatmul@libcublasLt.so.11
   153: 0000000000000000     0 FUNC    GLOBAL DEFAULT   UND cublasLtMatmulAlgoInit@libcublasLt.so.11
   155: 0000000000000000     0 FUNC    GLOBAL DEFAULT   UND cublasLtMatmulAlgoCheck@libcublasLt.so.11
   157: 0000000000000000     0 FUNC    GLOBAL DEFAULT   UND cublasLtDestroy@libcublasLt.so.11
   163: 0000000000000000     0 FUNC    GLOBAL DEFAULT   UND cublasLtMatmulAlgoGetIds@libcublasLt.so.11
   198: 0000000000000000     0 FUNC    GLOBAL DEFAULT   UND cublasLtMatrixLayoutCreate@libcublasLt.so.11
   214: 0000000000000000     0 FUNC    GLOBAL DEFAULT   UND cublasLtMatmulAlgoConfigGetAttribute@libcublasLt.so.11
   238: 0000000000000000     0 FUNC    GLOBAL DEFAULT   UND cublasLtMatmulDescDestroy@libcublasLt.so.11
   277: 0000000000000000     0 FUNC    GLOBAL DEFAULT   UND cublasLtMatmulPreferenceCreate@libcublasLt.so.11
   282: 0000000000000000     0 FUNC    GLOBAL DEFAULT   UND cublasLtMatmulPreferenceDestroy@libcublasLt.so.11
   286: 0000000000000000     0 FUNC    GLOBAL DEFAULT   UND cublasLtMatmulDescCreate@libcublasLt.so.11
   293: 0000000000000000     0 FUNC    GLOBAL DEFAULT   UND cublasLtMatmulAlgoCapGetAttribute@libcublasLt.so.11
   302: 0000000000000000     0 FUNC    GLOBAL DEFAULT   UND cublasLtMatmulPreferenceSetAttribute@libcublasLt.so.11
   311: 0000000000000000     0 FUNC    GLOBAL DEFAULT   UND cublasLtMatmulAlgoConfigSetAttribute@libcublasLt.so.11
  018:   5 (GLIBCXX_3.4)   8 (libcublasLt.so.11)   3 (GLIBC_2.2.5)   5 (GLIBCXX_3.4)
  034:   b (GLIBCXX_3.4.21)   0 (*local*)       8 (libcublasLt.so.11)   c (CXXABI_1.3) 
  03c:   3 (GLIBC_2.2.5)   3 (GLIBC_2.2.5)   8 (libcublasLt.so.11)   3 (GLIBC_2.2.5)
  050:   8 (libcublasLt.so.11)   3 (GLIBC_2.2.5)   3 (GLIBC_2.2.5)   0 (*local*)    
  054:   0 (*local*)       3 (GLIBC_2.2.5)   8 (libcublasLt.so.11)   5 (GLIBCXX_3.4)
  098:   5 (GLIBCXX_3.4)   8 (libcublasLt.so.11)  10 (libnvrtc.so.11.1)   8 (libcublasLt.so.11)
  09c:   5 (GLIBCXX_3.4)   8 (libcublasLt.so.11)   3 (GLIBC_2.2.5)   5 (GLIBCXX_3.4)
  0a0:   3 (GLIBC_2.2.5)   5 (GLIBCXX_3.4)  11 (GLIBC_2.2.5)   8 (libcublasLt.so.11)
  0c4:   0 (*local*)       0 (*local*)       8 (libcublasLt.so.11)   6 (libcublas.so.11)
  0d4:   0 (*local*)       3 (GLIBC_2.2.5)   8 (libcublasLt.so.11)  10 (libnvrtc.so.11.1)
  0ec:   3 (GLIBC_2.2.5)  16 (CXXABI_1.3.8)   8 (libcublasLt.so.11)   5 (GLIBCXX_3.4)
  114:   3 (GLIBC_2.2.5)   8 (libcublasLt.so.11)   3 (GLIBC_2.2.5)   3 (GLIBC_2.2.5)
  118:   e (GLIBCXX_3.4.9)   3 (GLIBC_2.2.5)   8 (libcublasLt.so.11)   3 (GLIBC_2.2.5)
  11c:   0 (*local*)       c (CXXABI_1.3)    8 (libcublasLt.so.11)   3 (GLIBC_2.2.5)
  124:   e (GLIBCXX_3.4.9)   8 (libcublasLt.so.11)  18 (GLIBC_2.3)     5 (GLIBCXX_3.4)
  12c:   6 (libcublas.so.11)   0 (*local*)       8 (libcublasLt.so.11)   c (CXXABI_1.3) 
  134:   0 (*local*)       3 (GLIBC_2.2.5)   5 (GLIBCXX_3.4)   8 (libcublasLt.so.11)
  0x0080: Version: 1  File: libcublasLt.so.11  Cnt: 1
  0x0090:   Name: libcublasLt.so.11  Flags: none  Version: 8
```
You don't need to rely on runtime info or repro to figure this out.

> I provided an example previously from Nvidia's onnx-tensorrt repo where it does not need to explicitly link cublasLt.
Here are some more examples.
All the TensorRT sample applications don't seem to link cublasLt either. All the other dependencies are same as what we have.
see https://github.com/NVIDIA/TensorRT/blob/master/samples/CMakeSamplesTemplate.txt#L84
interestingly they also have this line: https://github.com/NVIDIA/TensorRT/blob/master/samples/CMakeSamplesTemplate.txt#L113
which is the same as the --allow-shlib-undefined you tried previously.

They probably massed up.
Or they have some internal knowledge about it why intentionally providing incomplete dependencies.
Maybe they're very sure that it won't be called.

> The old codebase from back in July had tensorrt ep as shared lib, but was implicitly linking tensorrt ep to onnxruntime_test_all
I think that might have caused some problems. with EP as shared lib, ORT will explicitly load EP shared libs.

If it's dynamically loaded, the issue is probably "shadowed" again, since loader doesn't do that symbol check for you.
I didn't see it in v1.5.3.

Note that
- The issue is still there, but delayed to a segfault instead of linking error, if code path to those symbol is ever touched.
- Unlike native loader, dotnet's special loader will treat unresolved symbol as fatal error during loading.

**Comment by xkszltl** [comment] 2020-11-17 03:25
Interesting, trt 7.1 doesn't have the `NEEDED` line as in trt 7.2.
```
$ readelf -a /usr/lib64/libnvinfer_plugin.so.7.1.3 | grep -i cublaslt
0000000000a86148  0000001d00000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulDescCreate + 0
0000000000a86248  0000003400000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulPreferenceSetAttribute + 0
0000000000a86278  0000003d00000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatrixLayoutSetAttribute + 0
0000000000a863e0  0000005f00000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulPreferenceDestroy + 0
0000000000a865d8  0000009300000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulAlgoCheck + 0
0000000000a86828  000000cd00000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulAlgoConfigSetAttribute + 0
0000000000a86838  000000cf00000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatrixLayoutDestroy + 0
0000000000a86998  000000eb00000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulAlgoGetIds + 0
0000000000a869c0  000000ef00000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtCreate + 0
0000000000a869c8  000000f000000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulAlgoInit + 0
0000000000a86b20  0000011600000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulDescDestroy + 0
0000000000a86be8  0000012800000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtDestroy + 0
0000000000a86c58  0000013200000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmul + 0
0000000000a86c88  0000013700000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulPreferenceCreate + 0
0000000000a86ca8  0000013900000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulAlgoConfigGetAttribute + 0
0000000000a86d70  0000014b00000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulAlgoCapGetAttribute + 0
0000000000a86d88  0000014f00000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatmulDescSetAttribute + 0
0000000000a86e00  0000015c00000007 R_X86_64_JUMP_SLOT     0000000000000000 cublasLtMatrixLayoutCreate + 0
    29: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cublasLtMatmulDescCreate
    52: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cublasLtMatmulPreferenceSetAttribute
    61: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cublasLtMatrixLayoutSetAttribute
    95: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cublasLtMatmulPreferenceDestroy
   147: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cublasLtMatmulAlgoCheck
   205: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cublasLtMatmulAlgoConfigSetAttribute
   207: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cublasLtMatrixLayoutDestroy
   235: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cublasLtMatmulAlgoGetIds
   239: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cublasLtCreate
   240: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cublasLtMatmulAlgoInit
   278: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cublasLtMatmulDescDestroy
   296: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cublasLtDestroy
   306: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cublasLtMatmul
   311: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cublasLtMatmulPreferenceCreate
   313: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cublasLtMatmulAlgoConfigGetAttribute
   331: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cublasLtMatmulAlgoCapGetAttribute
   335: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cublasLtMatmulDescSetAttribute
   348: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT   UND cublasLtMatrixLayoutCreate
```

**Comment by xkszltl** [comment] 2020-11-18 10:19
Emmm strange....I cannot repro it with our latest environment either, regardless of which version of trt/cuda I used.

**Comment by jywu-msft** [comment] 2020-11-18 17:18
exactly. if you look at the very first comment of this issue, your output snapshot shows that the build failed for onnxruntime_test_all which is the unit test program. there should be no undefined references to cublasLt there. 
I believe it was due to an overlink issue that created the undefined cublasLt symbols in the main program.
If all the dependent shared libs that need cublasLt symbols are linked correctly, then the main program should not also need to link to cublasLt directly.

**Comment by jywu-msft** [comment] 2020-12-09 04:02
closing issue.

**Closed by jywu-msft** 2020-12-09 04:02 UTC
Labels: ep:TensorRT, type:support
