### ISSUE TITLE
RunOptions with memory.enable_memory_arena_shrinkage throws exception in 32 bit (at least on Windows)

### ISSUE THREAD

**Issue by MaialenUrbieta** [microsoft/onnxruntime#9056] opened 2021-09-14 16:53 UTC
I'm trying to use memory.enable_memory_arena_shrinkage in RunOptions to enable memory arena shrinkage post Run() in both 32-bit and 64-bit Windows. 
While 64-bit dll seems to work (since less memory is used), 32-bit onnxruntime dll throws an exception (ORT_CXX_API_THROW, ORT_INVALID_ARGUMENT(2), with no error message). 
I was expecting to benefit from this option in both platforms but am I missing something?
 
As a simplified example, I have attached the squeezenet example with the following modified lines:

```
  // Enable memory arena shrinkage
  Ort::RunOptions run_option;
  run_option.AddConfigEntry("memory.enable_memory_arena_shrinkage", "cpu:0");
  // score model & input tensor, get back output tensor
  auto output_tensors = session.Run(run_option, input_node_names.data(), &input_tensor, 1, output_node_names.data(), 1);
```
  
As previously mentioned, there is an exception in session.Run in 32-bit.

Note that if AddConfigEntry line is commented, there is no such throw either in 32-bit onnxruntime.dll. 

```
  // Enable memory arena shrinkage
  Ort::RunOptions run_option;
  // run_option.AddConfigEntry("memory.enable_memory_arena_shrinkage", "cpu:0");
  // score model & input tensor, get back output tensor
  auto output_tensors = session.Run(run_option, input_node_names.data(), &input_tensor, 1, output_node_names.data(), 1);
```

Is there something wrong when using run_option.AddConfigEntry("memory.enable_memory_arena_shrinkage", "cpu:0") compiled in 32 bits? 

**System information**
 - Onnxruntime 32-bit dll from: https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime/
 - Tested version is the latest: 1.8.1
 - Environment: PC Win10 64 bit
 - Code of squeezenet modified and attached

**To Reproduce**
-  Compile attached squezenet.cpp into 32-bit exe and run with squeezenet.onnx in the same folder

[squeezenet_modified_code.zip](https://github.com/microsoft/onnxruntime/files/7163785/squeezenet_modified_code.zip)

**Comment by hariharans29** [comment] 2021-09-14 19:38
Dupe of https://github.com/microsoft/onnxruntime/issues/8069

I will look into the empty error message. The C API failure status should have the correct message. I was under the impression the failure status message returned from the C API to the CXX API will manifested as the exception message.

**Comment by hariharans29** [comment] 2021-09-14 19:40
https://github.com/microsoft/onnxruntime/blob/7d28b596f482f70052cc9e58374455bd5af7c92d/onnxruntime/core/session/inference_session.cc#L2071 is the error message that is returned back as arenas are not supported on x86.

**Comment by MaialenUrbieta** [comment] 2021-09-14 20:14
Thanks Hariharans, that makes total sense now. I had also observed that sharing allocators between sessions brought enhanced memory usage in 64-bits but not in 32-bit (because, again, allocators are arena based by default in 64-bits). Got it!

**Closed** 2021-09-14 20:23 UTC
