### ISSUE TITLE
Can't use parent graph's initializer in subgraphs

### ISSUE THREAD

**Issue by lucienwang1009** [microsoft/onnxruntime#729] opened 2019-03-28 09:40 UTC
**Is your feature request related to a problem? Please describe.**
ONNX IR version 4 relaxes the constraint that initializers must be a subset of graph's inputs: https://github.com/onnx/onnx/pull/1718.
While in current onnxruntime, if a subgraph, e.g., the body-graph of If op, refers to an initializer of its parent graph and the initializer isn't amid graph's inputs, the runtime will screw up with a message:

*INVALID_GRAPH : Load model from model.onnx failed:At top level graph without matching NodeArg that subgraph consumes. Name=const_1 Graph may not conform to the ONNX spec and contain initializers that are not graph inputs.*

But if the initializer is in parent graph's inputs, everything will be fine.

Here is a sample model for your reference: 
``` python
import onnx
from onnx import helper, numpy_helper
from onnx import AttributeProto, TensorProto, GraphProto
import numpy as np
import onnxruntime

# The protobuf definition can be found here:
# https://github.com/onnx/onnx/blob/master/onnx/onnx.proto


# Create one input (ValueInfoProto)
initializers = [
    onnx.helper.make_tensor(
     name='cond_1',
     data_type=onnx.TensorProto.BOOL,
     dims=[1],
     vals=[0]
    ),
    onnx.helper.make_tensor(
     name='const_1',
     data_type=onnx.TensorProto.FLOAT,
     dims=[2],
     vals=[1,2]
    ),
    onnx.helper.make_tensor(
     name='const_2',
     data_type=onnx.TensorProto.FLOAT,
     dims=[2],
     vals=[1,2]
    ),
]

# Create one output (ValueInfoProto)
Y = helper.make_tensor_value_info('output', TensorProto.FLOAT, [2])

# then graph
then_graph = helper.make_graph(
    [helper.make_node("Identity", inputs=["const_1"], outputs=["then_graph_out"], name="iden_1")],
    "then_graph",
    [],
    [helper.make_tensor_value_info("then_graph_out", TensorProto.FLOAT, [2])],
    []
)
else_graph = helper.make_graph(
    [helper.make_node("Identity", inputs=["const_2"], outputs=["else_graph_out"], name="iden_2")],
    "else_graph",
    [],
    [helper.make_tensor_value_info("else_graph_out", TensorProto.FLOAT, [2])],
    []
)
# If node
if_node = helper.make_node(
    "If",
    inputs=["cond_1"],
    outputs=["output"],
    else_branch=else_graph,
    then_branch=then_graph,
    name="if"
)

# Create the graph (GraphProto)
graph_def = helper.make_graph(
    [if_node],
    "test-model",
    [],
    [Y],
    initializers
)

# Create the model (ModelProto)
model_def = helper.make_model(graph_def,
                              producer_name='onnx-example')
onnx.save(model_def, "model.onnx")

sess = onnxruntime.InferenceSession("model.onnx")
result = sess.run(['output'], input_feed={})
print(result)
```

**System information**
- ONNX Runtime version (you are using): 0.3.0

**Describe the solution you'd like**
According to ONNX document, subgraphs should be able to use initializers in its parent graph, no matter whether the initializer is the part of inputs.

**Describe alternatives you've considered**

**Additional context**

**Comment by skottmckay** [comment] 2019-03-28 09:51
The Graph constructor need to create a NodeArg for values in the initializer list. The current code assumes that just doing that for graph inputs is sufficient. We could call GetOrCreateNodeArg when iterating the initialziers and adding to the name_to_initial_tensor_ map.

    // Copy initial tensors to a map.
    for (auto& tensor : graph_proto_->initializer()) {
      name_to_initial_tensor_[tensor.name()] = &tensor;
    }

    // Collect all node arg name, type, shape information in the graph.
    // type/shape information will be assigned to each node arg when going
    // thru all nodes later.
    for (auto& graph_input : graph_proto_->input()) {
      if (graph_input.has_name() && graph_input.has_type()) {
        name_to_type_map[graph_input.name()] = graph_input.type();
        // always create a NodeArg for graph input in case its from an initializer
        GetOrCreateNodeArg(graph_input.name(), &graph_input.type());
      }
    }

**Comment by lucienwang1009** [comment] 2019-03-28 10:04
> The Graph constructor need to create a NodeArg for values in the initializer list. The current code assumes that just doing that for graph inputs is sufficient. We could call GetOrCreateNodeArg when iterating the initialziers and adding to the name_to_initial_tensor_ map.
> 
> ```
> // Copy initial tensors to a map.
> for (auto& tensor : graph_proto_->initializer()) {
>   name_to_initial_tensor_[tensor.name()] = &tensor;
> }
> 
> // Collect all node arg name, type, shape information in the graph.
> // type/shape information will be assigned to each node arg when going
> // thru all nodes later.
> for (auto& graph_input : graph_proto_->input()) {
>   if (graph_input.has_name() && graph_input.has_type()) {
>     name_to_type_map[graph_input.name()] = graph_input.type();
>     // always create a NodeArg for graph input in case its from an initializer
>     GetOrCreateNodeArg(graph_input.name(), &graph_input.type());
>   }
> }
> ```

Thanks for quick action! This bug blocked tf2onnx upgrade to IR version 4.

**Comment by lucienwang1009** [comment] 2019-04-08 02:56
New error: 
*RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Exception during initialization: /onnxruntime_src/onnxruntime/core/framework/node_index_info.cc:82 onnxruntime::NodeIndexInfo::Init(const TValidNodes&, onnxruntime::NodeIndex, const onnxruntime::MLValueNameIdxMap&)::<lambda(const onnxruntime::NodeArg&, bool)> [with TValidNodes = onnxruntime::ValidNodes<const std::vector<const onnxruntime::Node*> >] status.IsOK() was false. Could not find MLValue with name 'const_1'*

**Comment by linkerzhang** [comment] 2019-04-18 07:30
This should be related with two issues:
1. One should be known issue in https://github.com/Microsoft/onnxruntime/blob/master/onnxruntime/core/optimizer/optimizer_execution_frame.cc#L53. It does not support control flow ops by design, @weixingzhang 
2. One may be a bug in constant folding https://github.com/Microsoft/onnxruntime/blob/master/onnxruntime/core/optimizer/constant_folding.cc#L26. I believe that for constant folding it should use OpKernelContextInternal. @weixingzhang  @kkaranasos

**Comment by kkaranasos** [comment] 2019-04-22 18:49
Constant folding uses OpKernelContext (and not OpKernelContextInternal) on purpose, so that we don't rely on the InferenceSession in the optimizer.
For now we disabled constant folding for subgraphs (https://github.com/Microsoft/onnxruntime/pull/858) until we provide a proper support for it.

**Comment by skottmckay** [comment] 2019-05-15 01:20
I ran the test code with the latest onnxruntime code and it was successful. @lucienwang1009 can you please check to see if it works for you?

**Comment by skottmckay** [comment] 2019-06-03 21:23
Closing as I can't reproduce. Please re-open if this is still an issue.

**Closed by skottmckay** 2019-06-03 21:23 UTC
Labels: bug

**Comment by lucienwang1009** [comment] 2019-06-04 01:28
@skottmckay It works fine now, Thanks!!
