### ISSUE TITLE
Python3.5 nightly builds failing

### ISSUE THREAD

**Issue by ganik** [microsoft/onnxruntime#5972] opened 2020-11-30 16:41 UTC
Nightly builds are failing due to PEP8 validation failure.
![image](https://user-images.githubusercontent.com/18757686/100637508-d0fce180-32e7-11eb-95e5-3af0fee38a30.png)

**Comment by ganik** [comment] 2020-11-30 16:43
This is caused by this commit: https://github.com/microsoft/onnxruntime/commit/015fbb3dbb8547294171990e1104cdf101be4a7d
Assigning to @ivanst0

**Comment by ivanst0** [comment] 2020-11-30 18:51
Sorry about that. The issue is fixed in PR https://github.com/microsoft/onnxruntime/pull/5874.
@snnn, when do you expect https://github.com/microsoft/onnxruntime/pull/5874 to go in?

**Comment by snnn** [comment] 2020-11-30 20:24
Validating

**Closed** 2020-11-30 21:55 UTC
Labels: type:bug
