### ISSUE TITLE
Error while running the `sklearn-onnx` example model using `onnxruntime-web`

### ISSUE THREAD

**Issue by 0xMartian** [microsoft/onnxruntime#8450] opened 2021-07-21 10:10 UTC
**Describe the bug**
I'm trying to implement this [sklearn-onnx example](https://onnx.ai/sklearn-onnx/) on a [next.js](https://nextjs.org/) project using `onnxruntime-web`.
Running the model results in an error that throws a (random?) number: `error:  8591000`

<details>
<summary>
Code
</summary>

```ts
  const { InferenceSession, Tensor } = await import('onnxruntime-web')

  const arrayBuffer = await fetch(`${process.env.PUBLIC_URL}/rf_iris.onnx`).then((response) => response.arrayBuffer())
  const session = await InferenceSession.create(arrayBuffer, {
    executionProviders: ['wasm'],
  })

  // 38, 4 (X_test from DeepNote example)
  const X = Float32Array.from(
    [
      [6.1, 2.9, 4.7, 1.4],
      [7.4, 2.8, 6.1, 1.9],
      [6.9, 3.2, 5.7, 2.3],
      [6.7, 3.3, 5.7, 2.5],
      [4.5, 2.3, 1.3, 0.3],
      [5, 3.5, 1.3, 0.3],
      [6.1, 3, 4.9, 1.8],
      [6.2, 2.8, 4.8, 1.8],
      [4.4, 3, 1.3, 0.2],
      [5.8, 2.7, 5.1, 1.9],
      [7.7, 3, 6.1, 2.3],
      [5.2, 3.4, 1.4, 0.2],
      [5.1, 3.5, 1.4, 0.3],
      [6, 2.2, 5, 1.5],
      [7.7, 2.8, 6.7, 2],
      [6.4, 2.8, 5.6, 2.2],
      [5.7, 2.6, 3.5, 1],
      [5, 3.5, 1.6, 0.6],
      [5, 3.4, 1.5, 0.2],
      [6.6, 2.9, 4.6, 1.3],
      [5.5, 4.2, 1.4, 0.2],
      [6.7, 3, 5, 1.7],
      [6, 3, 4.8, 1.8],
      [6.1, 2.6, 5.6, 1.4],
      [4.8, 3.4, 1.9, 0.2],
      [6.1, 2.8, 4.7, 1.2],
      [5.4, 3.4, 1.5, 0.4],
      [7.2, 3, 5.8, 1.6],
      [5.5, 2.6, 4.4, 1.2],
      [4.9, 3.1, 1.5, 0.1],
      [6.8, 3, 5.5, 2.1],
      [5.8, 4, 1.2, 0.2],
      [5.5, 2.3, 4, 1.3],
      [6.8, 3.2, 5.9, 2.3],
      [6.5, 3, 5.2, 2],
      [5.7, 3.8, 1.7, 0.3],
      [5.6, 3, 4.1, 1.3],
      [7, 3.2, 4.7, 1.4],
    ].flat()
  )
  const tensor = new Tensor('float32', X, [38, 4])
  const input = session.inputNames[0]
  const feed = { [input]: tensor }
  try {
    console.log('feed', feed)
    const results = await session.run(feed, { logSeverityLevel: 0, logVerbosityLevel: 10 })
    console.log('results', results)
  } catch (error) {
    console.log('error: ', error) // random number (eg. 9062152)
  }
```

</details>

**Urgency**
Some

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Intel Mac running Big Sur
- Browser: Same in Chrome & Safari
- Model generated here: https://deepnote.com/project/ONNX-p3P2bx05T_GzH_MMjDTtmg/%2Fnotebook.ipynb#00005-a6ae32ef-9ff8-4397-b384-f2ddd3a97d9b

**To Reproduce**
1. [Clone this repo](https://github.com/0xMartian/uniswap-interface)
2. Install dependencies: `yarn install`
3. Run and see console: `yarn start`

**Expected behavior**
I expect it to return a tensor while running similar to how it works in the example.
```py
array([1, 2, 2, 2, 0, 0, 2, 1, 0, 2, 2, 0, 0, 1, 2, 2, 1, 0, 0, 1, 0, 2,
       1, 1, 0, 1, 0, 2, 1, 0, 2, 0, 1, 2, 2, 0, 1, 1], dtype=int64)
```

**Screenshots**
<img width="773" alt="Screen Shot 2021-07-21 at 11 53 12" src="https://user-images.githubusercontent.com/87619808/126470063-98887359-386b-4f9c-9b7e-b2f91bba85cc.png">

**Additional context**
 - Issue: https://github.com/Uniswap/uniswap-interface/issues/2086
 - PR: https://github.com/Uniswap/uniswap-interface/pull/2088/files

**Comment by uniyj** [comment] 2021-07-22 15:20
Note that it's branch "feat/onnx" to reproduce the bug. And the problem seems to be the need for outputname to be passed in as a second argument to `session.run`. See: https://github.com/Uniswap/uniswap-interface/pull/2092

Don't think this is an issue on the onnxruntime side. Should be able to close this.

**Closed** 2021-07-22 15:45 UTC
Labels: component:ort-web

**Comment by 0xMartian** [comment] 2021-07-22 15:58
Yep! Although a more helpful error message would be nice for people in the future:)
