### ISSUE TITLE
The program '[30444] dotnet.exe' has exited with code -1066598274 (0xc06d007e) 'Module not found'.

### ISSUE THREAD

**Issue by kamilk91** [microsoft/onnxruntime#1416] opened 2019-07-16 08:14 UTC
**Describe the bug**
When i'am using sample from project README i have an error The program '[30444] dotnet.exe' has exited with code -1066598274 (0xc06d007e) 'Module not found'.

**System information**
- Windows
- ONNX Runtime installed from https://github.com/onnx/onnx-docker/tree/master/onnx-ecosystem docker repo 
- ONNX Runtime version: latest (https://github.com/onnx/onnx-docker/commit/7a3f42e44b15f7bb9eb2e9a17003ce3deb1b7a8a commit)
- Python version: 3.7
- Visual Studio version (if applicable): 2017

**To Reproduce**
```
internal class ONNXPrediction
    {
        public ONNXPrediction()
        {
            using (var session = new InferenceSession("../../Assets/model.onnx"))
            {


                var inputMeta = session.InputMetadata;
                var container = new List<NamedOnnxValue>();
                float[] inputData = LoadTensorFromFile(@"bench.in");








                Tensor<float> t1 = new DenseTensor<float>(100);
                Tensor<float> t2 = new DenseTensor<float>(100);

                var inputs = new List<NamedOnnxValue>()
                {
                NamedOnnxValue.CreateFromTensor<float>("some",t1),
                NamedOnnxValue.CreateFromTensor<float>("thing",t2)
                };

                  foreach (var name in inputMeta.Keys)
                {
                    var tensor = new DenseTensor<float>(inputData, inputMeta[name].Dimensions);
                    container.Add(NamedOnnxValue.CreateFromTensor<float>(name, tensor));
                }


                using (var results = session.Run(inputs))
                {
                    foreach (var r in results)
                    {
                        Console.WriteLine("Output for {0}", r.Name);
                        Console.WriteLine(r.AsTensor<float>().GetArrayString());
                    }
                }
            }






        }

        private static float[] LoadTensorFromFile(string filename)
        {
            var tensorData = new List<float>();

            // read data from file
            using (var inputFile = new System.IO.StreamReader(filename))
            {
                inputFile.ReadLine(); //skip the input name
                string[] dataStr = inputFile.ReadLine().Split(new char[] { ',', '[', ']' }, StringSplitOptions.RemoveEmptyEntries);
                for (int i = 0; i < dataStr.Length; i++)
                {
                    tensorData.Add(Single.Parse(dataStr[i]));
                }
            }

            return tensorData.ToArray();
        }
    }
```

**Comment by gloednieuw** [comment] 2019-07-16 09:40
I have the same issue when trying to run my program in Core 2.2

**Comment by pranavsharma** [comment] 2019-07-18 02:19
@jignparm can you take a look? thx.

**Comment by jignparm** [comment] 2019-07-23 00:57
Looks like this is occurring when using Docker for Windows, as opposed to Linux (@kamilk91 , please correct if wrong). One likely cause could be the docker image for the dotnet libraries -- I'll update shortly after reproducing the error.

**Comment by vinitra** [comment] 2019-07-24 00:22
Hi @kamilk91! The ONNX ecosystem docker container is intended for Python users to get started with a model from a different framework and enables conversion to the ONNX format. It uses a Python ONNX Runtime package instead of C# / .NET nuget for your scenario and does not contain the .NET SDK or dotnet.exe. While using C# and .NET, I would recommend creating a separate docker container or working locally and installing the [ONNX Runtime build from the NuGet Gallery](https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime/).

**Comment by jignparm** [comment] 2019-07-24 01:03
@kamilk91, looks like ONNX ecosystem docker container is not intended for .NET development. What is the use-case? Is it to get the ONNX ecosystem docker container working (for model conversion etc.), or do you just need to score an ONNX model using .Net? 

Outside of the docker image,  the project should compile fine using either .Net Core 2.1 or 2.2.

**Comment by jignparm** [comment] 2019-07-29 22:10
Closing out this issue for now -- please reopen if needed.

**Closed by jignparm** 2019-07-29 22:10 UTC
Labels: bug
