### ISSUE TITLE
Is there an API for multi-GPU inferencing?

### ISSUE THREAD

**Issue by BUAAXZzz** [microsoft/onnxruntime#9998] opened 2021-12-10 02:38 UTC
I have a 3-gpu machine and I want to utilize all of them to inference a model. I am using OrtSessionOptionsAppendExecutionProvider_CUDA to set cuda provider. But in this API, device_id can only set one gpu.

- ONNXRuntime version : 1.6.0
- CUDA version: 10.2
- CuDnn version: 8.1.1
- Platform: Visual Studio 2019 C++

Is there any way for multi-gpu inferencing like nn.DistributedDataParallel in Pytorch?
Thanks!

**Comment by hanbitmyths** [comment] 2021-12-10 05:58
Duplicate of [#8244](https://github.com/microsoft/onnxruntime/issues/8244)

**Closed** 2022-08-12 18:40 UTC
Labels: status:duplicate
