### ISSUE TITLE
ModelMetadata::GetDescription returns empty string  

### ISSUE THREAD

**Issue by efeguney** [microsoft/onnxruntime#6194] opened 2020-12-22 05:39 UTC
**Describe the bug**
ModelMetadata::GetDescription returns empty string even for models with description filed with valid entries. For e.g., I can see the model description filed for efficientnet-lite4-11.onnx in Netron, however, ORT returns empty string for the description of this model.

**Urgency**
Model description contains information important for deployment for certain models that we are working on.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): Source
- ONNX Runtime version: 1.5.2
- Python version: N/A
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 11.1
- GPU model and memory: N/A

**To Reproduce**
Ort::AllocatorWithDefaultOptions allocator;
auto metadata = session.GetModelMetadata();
char* model_desc = metadata.GetDescription(allocator);
std::cout << "Model description = " << model_desc;

You can use the efficientnet model here to reprodice:
https://github.com/onnx/models/blob/master/vision/classification/efficientnet-lite4/model/efficientnet-lite4-11.onnx

**Expected behavior**
A non-empty string with model description. For the example onnx model above, it should be:
Model description = converted from saved_model_lite

**Comment by hariharans29** [comment] 2020-12-22 06:28
We return back this field - https://github.com/onnx/onnx/blob/33fd678c6c38baa3e2d9fd5addf4c56cd681a87a/onnx/onnx.in.proto#L371 as the description for the model. For the provided model, this field is empty - hence this is not a bug.

I did find the string "converted from saved_model_lite" in the doc_string field of the Graph message though - https://github.com/onnx/onnx/blob/33fd678c6c38baa3e2d9fd5addf4c56cd681a87a/onnx/onnx.in.proto#L432.

I don't have proof but my guess is that netron looks at the `doc_string` field of the `ModelProto` first and if it is empty falls back to looking at the `doc_string` field of the `GraphProto` next. This is the cause for the difference. 

We could adopt similar logic but I would guess it is a change in API behavior that would need versioning of the API even if we did adopt a similar approach. Alternatively, you can make sure the `doc_string` field of the ModelProto is set and you wouldn't have this issue.

**Comment by efeguney** [comment] 2020-12-29 08:11
Thank you for the prompt response! What do you think about adding a function to query GraphProto doc_string? We do not always have control over how model or graph descriptions are set.

**Comment by hariharans29** [comment] 2020-12-29 13:18
Sure, I don't see why not. It should be fairly light-weight to introduce it.

**Comment by hariharans29** [comment] 2021-01-06 06:18
Closing this as the feature request as introduced in #6248

**Closed by hariharans29** 2021-01-06 06:18 UTC
Labels: api:C/C++, type:support
