### ISSUE TITLE
PrepareForCompute Non concat axis dimensions must match

### ISSUE THREAD

**Issue by kafan1986** [microsoft/onnxruntime#11672] opened 2022-05-29 21:45 UTC
**Describe the bug**
I converted a pytorch fast_pitch model to onnx and it converted OK. During the inference I get the following error. There seem to be some similar bug raised previously #[8020](https://github.com/microsoft/onnxruntime/issues/8020) 

**Warnings and finally Error message during inference**
```
2022-05-30 02:44:01.501728948 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_2141'
2022-05-30 02:44:01.545423718 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_2141'
2022-05-30 02:44:01.564558336 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_2141'
2022-05-30 02:44:01.896546494 [E:onnxruntime:, sequential_executor.cc:346 Execute] Non-zero status code returned while running ConcatFromSequence node. Name:'ConcatFromSequence_2162' Status Message: concat.cc:156 PrepareForCompute Non concat axis dimensions must match: Axis 1 has mismatched dimensions of 12 and 14
```

**Trace**

```

---------------------------------------------------------------------------
Fail                                      Traceback (most recent call last)
/tmp/ipykernel_258100/3612290811.py in <module>
     13 # # compute ONNX Runtime output prediction
     14 ort_inputs = {'input_tensor': onnx_runtime_input, 'additional_params': params}
---> 15 ort_outs = ort_session.run(['mel_post'], ort_inputs)

~/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py in run(self, output_names, input_feed, run_options)
    190             output_names = [output.name for output in self._outputs_meta]
    191         try:
--> 192             return self._sess.run(output_names, input_feed, run_options)
    193         except C.EPFail as err:
    194             if self._enable_fallback:

Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running ConcatFromSequence node. Name:'ConcatFromSequence_2162' Status Message: concat.cc:156 PrepareForCompute Non concat axis dimensions must match: Axis 1 has mismatched dimensions of 12 and 14
```

**Inference Code**

```
import onnxruntime
onnx_runtime_input = np.array([[ 5, 10, 33, 15, 5, 14, 33, 19, 8, 5, 21, 37, 33, 11, 15, 5, 21, 37, 33, 18, 8]], dtype='int64')
params = np.array([1.15, 1.0, 1.0], np.dtype('float32'))

ort_session = onnxruntime.InferenceSession("fast_pitch.onnx")

# # compute ONNX Runtime output prediction
ort_inputs = {'input_tensor': onnx_runtime_input, 'additional_params': params}
ort_outs = ort_session.run(['mel_post'], ort_inputs)
```

**Input Data**

`tensor([[ 5, 10, 33, 15,  5, 14, 33, 19,  8,  5, 21, 37, 33, 11, 15,  5, 21, 37, 33, 18,  8]])`

**Expected Output Data (Pytorch inference)**

```
Shape: torch.Size([1, 80, 120])

tensor([[[-6.5814, -5.4778, -4.8955,  ..., -5.5355, -5.3995, -5.2439],
         [-6.3145, -5.2096, -4.5703,  ..., -3.6377, -3.7430, -3.7918],
         [-6.2930, -5.0865, -4.1757,  ..., -1.5816, -2.0812, -2.5433],
         ...,
         [-9.0989, -8.6579, -7.7678,  ..., -5.6325, -5.8552, -5.5436],
         [-9.0711, -8.4552, -7.6035,  ..., -6.0442, -6.1953, -5.7863],
         [-9.1945, -8.6019, -7.8147,  ..., -6.0601, -6.1908, -5.7653]]])
```

**Model download link**: 
Link updated to a google drive

https://drive.google.com/file/d/1uzqMLYTLWM-wZKmWRpxpTLv4MEGMvFxD/view?usp=sharing

https://we.tl/t-VjXsSBdwhs

**Urgency**
It is urgent. Production functionality is stuck because of this.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- ONNX Runtime installed from (source or binary): Source
- ONNX Runtime version: Latest
- Python version: 3.8

**To Reproduce**
Download and run inference using the sample code and input provided

**Comment by garymm** [comment] 2022-05-31 19:25
@yuslepukhin why do you think this is a converter issue?

**Comment by kafan1986** [comment] 2022-06-02 21:15
@yuslepukhin and @garymm Any update?

**Comment by yuslepukhin** [comment] 2022-06-03 01:08
It will be some time before I can get to it. However, the link above does not display any files that I could download.

**Comment by kafan1986** [comment] 2022-06-05 20:31
@yuslepukhin I have updated the download link to a public google drive link

**Comment by kafan1986** [comment] 2022-06-07 17:08
> The issue that you referenced is different. What is the commit that you are building? Is it a release tag?

The **pytorch version used for export is 1.10.1+cu102** and **onnxruntime version is 1.10.0**

**Comment by yuslepukhin** [comment] 2022-06-07 17:32
> The **pytorch version used for export is 1.10.1+cu102** and **onnxruntime version is 1.10.0**. Should I update them?

It would be nice if you tried the latest (1.10 is not the latest) and see if this reproduces. Also, do you need to build from source? What are the build arguments?

**Comment by yuslepukhin** [comment] 2022-06-08 22:23
What happens is that that the node attempts to concatenate 21 (in this case) 2-D tensors on `axis=0`.

![image](https://user-images.githubusercontent.com/11303988/172727258-cdd4234d-6151-4c41-936e-de4bbc2f2707.png)

The shapes of the tensors except the axis that the concatenation takes place is supposed to be the same.

Here is the shapes of the first few tensors:

0: {256, 14}
1: {256, 12}
2: {256, 5}
3: {256, 4}

You can see that they all have the same dimensions on axis 0 but axis 1 is different and this is why it is erroring out. So, please, examine the original model to verify the axis it is suppose to concatenate on. If the original model says 0, then it is wrong. If it says 1, then it is a conversion issue.

**Comment by kafan1986** [comment] 2022-06-12 21:41
> What happens is that that the node attempts to concatenate 21 (in this case) 2-D tensors on `axis=0`.
> 
> ![image](https://user-images.githubusercontent.com/11303988/172727258-cdd4234d-6151-4c41-936e-de4bbc2f2707.png)
> 
> The shapes of the tensors except the axis that the concatenation takes place is supposed to be the same.
> 
> Here is the shapes of the first few tensors:
> 
> 0: {256, 14} 1: {256, 12} 2: {256, 5} 3: {256, 4}
> 
> You can see that they all have the same dimensions on axis 0 but axis 1 is different and this is why it is erroring out. So, please, examine the original model to verify the axis it is suppose to concatenate on. If the original model says 0, then it is wrong. If it says 1, then it is a conversion issue.

This seems to be a conversion issue. Below is the neural network module that is throwing the issue. As pad_sequence is not supported in Onnx yet and given that in the inference I don't need batch support. I hard coded the index to zero and then applied unsqueeze to retain the original expected shape.

Even during the conversion, there is some message


```
/home/xxx/TTS_TFLite/ForwardTacotron/models/common_layers.py:20: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  temp_var = torch.Tensor(temp_var)
```


```
class LengthRegulator(nn.Module):

    def __init__(self):
        super().__init__()

    def forward(self, x: torch.Tensor, dur: torch.Tensor) -> torch.Tensor:
        dur[dur < 0] = 0.
        x_expanded = []
        for i in range(x.size(0)):
            x_exp = torch.repeat_interleave(x[i], (dur[i] + 0.5).long(), dim=0)
            x_expanded.append(x_exp)

        temp_var = x_expanded[0]  # hard coded index to 0
        temp_var = torch.Tensor(temp_var)
        temp_var = temp_var.unsqueeze(0)
        # x_expanded = pad_sequence(x_expanded, padding_value=0., batch_first=True) # not supported in Onnx framework yet
        return temp_var
```

**Comment by yuslepukhin** [comment] 2022-06-13 17:04
@garymm mind, taking a look?

**Comment by garymm** [comment] 2022-06-13 21:50
The `TracerWarning` is probably telling you exactly what's going wrong here. I think if you get rid of it, you should be able to export properly.
You could try moving the problematic code into a function or module that is decorated with `torch.jit.script` or `torch.jit.script_if_tracing`.
If that doesn't work, please open an issue in the pytorch/pytorch repo.
(Closing this since exporter issues are tracked in pytorch/pytorch repo, not to dismiss the issue)

**Closed by garymm** 2022-06-13 21:50 UTC
Labels: component:converter, component:coreruntime, component:operator
