### ISSUE TITLE
failed:Type Error: Type parameter (T) bound to different types (tensor(float) and tensor(double) in node ().

### ISSUE THREAD

**Issue by dashesy** [Microsoft/onnxruntime#649] opened 2019-03-18 18:26 UTC
**Describe the bug**
Loading inference session I get an error with not much helpful message

```text
RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Load model from output/some.onnx failed:Type Error: Type parameter (T) bound to different types (tensor(float) and tensor(double) in node ().
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- ONNX Runtime installed from (source or binary): binary (pip)
- ONNX Runtime version: 0.3.0
- Python version: 3.5.2

**To Reproduce**
Load a previously saved model with `sess = rt.InferenceSession("some.onnx")`

**Expected behavior**
To load the model or give more helpful error

**Additional context**
Will share the model offline.

**Comment by dashesy** [comment] 2019-03-18 21:00
To reproduce:

    
```python
import torch
import torch.nn as nn

dummy_input = torch.randn(1, 3, 227, 227, device='cuda')
model = nn.LocalResponseNorm(5, alpha=0.0001, beta=0.75, k=1.0).cuda()
torch.onnx.export(model, dummy_input, "output/some.onnx", verbose=True, input_names=['data'], output_names=['prob'])

```

Then

```python
import numpy as np
import onnxruntime as rt

sess = rt.InferenceSession("output/some.onnx")
```

**Comment by duli2012** [comment] 2019-03-18 23:33
It's converter related bug. Can @spandantiwari take a look?

**Comment by faxu** [comment] 2019-04-24 18:24
Closing, as this is tracked in the referenced Pytorch issue.

**Closed by faxu** 2019-04-24 18:24 UTC
Labels: bug

**Comment by WilliamZhaoz** [comment] 2019-09-20 08:36
Hi, I hit the same bugs, but I did not use LRN, I use a lot of operations, so it is difficult to find the key operation where the problem is. Help. How can I fix this problem.

**Comment by dashesy** [comment] 2019-09-20 17:21
@WilliamZhaoz this is usually a converter bug. The way I handled them was to [give each node a name](https://github.com/pytorch/pytorch/issues/26035) then run with ORT get the node name and find it in [netron](https://github.com/lutzroeder/netron) using `Ctrl+F` to see where it comes from.
I have seen [this issue](https://github.com/pytorch/pytorch/issues/26184) now in Python2 but Python3 export was fine, so try Python3 for exporting it has less bugs.

**Comment by vegetable09** [comment] 2021-02-24 08:01
@dashesy What a great solution! I found the failed operator just in 1 second.

**Comment by zhangjy328** [comment] 2025-03-17 09:30
@dashesy Hello, I have encountered the same problem. I'm still having this issue even though I'm using Python 3. I found the location in Netron, but I didn't find any problems there. are there any other solutions?
