### ISSUE TITLE
 [ONNXRuntimeError] : 1 : FAIL : Type Error: Type parameter (T) of Optype (Add) bound to different types (tensor(float16) and tensor(float) in node ()

### ISSUE THREAD

**Issue by ramkrishna2910** [microsoft/onnxruntime#15241] opened 2023-03-27 19:45 UTC
### Describe the issue

ONNX export of the following model was successful. But unable to run inference using ONNXRuntime.
I hit the ` [ONNXRuntimeError] : 1 : FAIL : Type Error: Type parameter (T) of Optype (Add) bound to different types (tensor(float16) and tensor(float) in node ()` error.

- onnx = 1.11.0
- onnxruntime = 1.14.1
- torch = 1.13.1
- torch-geometric = 2.3.0

### To reproduce

Model generated from:
```

import torch
from torch_geometric.datasets import Planetoid
from torch_geometric.nn import CGConv

dataset = Planetoid(root=".", name="Cora")
data = dataset[0]
edge_index_rows = 2

model = CGConv(dataset.num_features)
inputs = {
    "x": torch.zeros(data.num_nodes, data.num_features, dtype=torch.float),
    "edge_index": torch.zeros(edge_index_rows, data.num_nodes, dtype=torch.int64),
}
model.eval()
torch.onnx.export(model, inputs, "cg.onnx", opset_version=16, do_constant_folding=True, input_names = ['input'], output_names = ['output'])

```

### Platform

Linux

### OS Version

18.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by pranavsharma** [comment] 2023-03-27 21:51
I tried the exact same script and this inferencing code and couldn't repro this.

```
sess = rt.InferenceSession("cg.onnx", providers=["CPUExecutionProvider"])
input_0 = np.random.rand(2708, 1433).astype(np.float32)
input_1 = np.random.rand(2, 2708).astype(np.int64)
out = sess.run(None, {"input": input_0, "edge_index": input_1})
print(out)
```
I've onnxruntime-1.14.1 on Ubuntu 18.04.5 LTS

**Comment by ramkrishna2910** [comment] 2023-03-27 22:55
Thank you for the response. Yes, this version of the model passes as expected. 
The failure was due to the FP16 version of the model, converted through onnxmltools.
I have filed an issue with onnxmltools as well: https://github.com/onnx/onnxmltools/issues/617

**Comment by hariharans29** [comment] 2023-03-28 00:46
This usually means there is an issue with the model itself. The specific complaint means that the two operands of the Add operator are bound to diffrent types (float16 and float32) when the spec mandates that the input types need to be homogeneous (https://github.com/onnx/onnx/blob/main/docs/Operators.md#add)

**Comment by tianleiwu** [comment] 2023-04-20 18:04
Close the issue as the cause is in onnxmltools instead of onnxruntime.

**Closed by tianleiwu** 2023-04-20 18:04 UTC
