### ISSUE TITLE
C# adding option for cudnn_conv_algo_search : DEFAULT

### ISSUE THREAD

**Issue by callbarian** [microsoft/onnxruntime#9730] opened 2021-11-11 05:48 UTC
Platform : Windows, C#
Version : Onnxruntime 1.9.0 Nuget package

Hellow, I am testing the speed of yolov5 model, and it is twice as slow as pytorch version.

after taking a look at issues, I have found Issue [#7212](https://github.com/microsoft/onnxruntime/issues/7212) is related to mine.

Nsight System shows the use of **volta_scudnn kernels,** while running tensorRt shows me **turing kernels.** 

So I believe onnxruntime is not choosing best op.

I am trying to add cuda provider option :  {cudnn_conv_algo_search : DEFAULT}

However, in c#, AppendExecutionProvider_CUDA(int deviceId) does not have parameter to pass cudaprovider options. 

Is this feature availabe in c# version?

I am also referring to these, for they are directly related to my issue.
[#6291](https://github.com/microsoft/onnxruntime/pull/6291)
[#7315](https://github.com/microsoft/onnxruntime/pull/7315)

**What happened to OrtCudaProviderOptions?
Because I don't see this struct in the nuget package.**

Thank you

**Comment by hariharans29** [comment] 2021-11-15 18:16
Yeah, this is an outstanding work-item in our backlog to help users configure the CUDA EP from C#. We will get to it as soon as we can. Marked the issue as an enhancement.

**Comment by vadimkantorov** [comment] 2021-11-15 23:34
@hariharands29 please also consider the root cause of onnxrt picking the wrong cudnn kernels... i guess sth is again wrong about cudnn benchmark setup / workspace...

**Comment by callbarian** [comment] 2021-11-16 00:06
@hariharans29 Understood. I will be waiting for the upcoming package. Until then, guess I will have to wait. Thank you for getting back.

**Comment by hariharans29** [comment] 2021-11-16 00:14
@vadimkantorov: The root cause is this revert: https://github.com/microsoft/onnxruntime/pull/8181. We found that the workspace memory could jump up by GBs when CuDNN is picking the best possible Conv algo. This did not play well with our allocator setup and this was a learning for us and we had to pull out that change that was prompted by your issue.

Subsequently, this change added it back: https://github.com/microsoft/onnxruntime/pull/8613 but we had to gate the algo picking functionality as it seems with it turned on, it improves the perf of your models but causes regressions in some others. So, we need to expose the flag for users to turn it on while inferencing. You can set [this line](https://github.com/microsoft/onnxruntime/blob/ac57afc3a69dfc6a57caeee678966a1fce50bca9/onnxruntime/core/providers/cuda/cuda_execution_provider.h#L85) to return true (by default it is returning false) and build from source if you need it for now. We need to prioritize the work-item to expose a to turn it on.

**Comment by hariharans29** [comment] 2021-11-16 00:20
> @hariharans29 Understood. I will be waiting for the upcoming package. Until then, guess I will have to wait. Thank you for getting back.

@callbarian : The upcoming package is 2 weeks away but this feature will not make it into that. It might make it into one of the releases in the new year though based on other priorities. I will keep the issue open for tracking. FWIW: This is an implicit dupe of this issue: https://github.com/microsoft/onnxruntime/issues/8995 as it is also about configuring the CUDA EP from C#.

**Comment by vadimkantorov** [comment] 2021-11-16 00:24
It would be nice if you had added basic jaspernet conv1d models in your benchmarks, e.g. we found earlier that 1.8.0 worked well, 1.8.1 already had a perf regression

**Comment by hariharans29** [comment] 2021-11-16 00:35
@vadimkantorov: The regression in 1.8.1 was expected as we reverted the change because it caused a memory bloat (It wasn't missed due to lack of benchmarks). To re-introduce the change, we had to re-architect our memory allocation setup for CUDA. 

I just realized though, the flag to use the maximum possible workspace isn't available in C/C++/C# but it is available in Python as the provider options is just a map. See this:

https://github.com/microsoft/onnxruntime/blob/7e207ba3be3620ffbb9f8b8fcffd15e911a744e3/orttraining/orttraining/python/training/ortmodule/_graph_execution_manager.py#L268

If you use Python, you could pass in the provider option to turn the feature ON. See this for an example on how to use the provider options map:

https://github.com/microsoft/onnxruntime/blob/ac57afc3a69dfc6a57caeee678966a1fce50bca9/onnxruntime/test/python/onnxruntime_test_python.py#L154

**Closed** 2022-01-06 19:03 UTC
Labels: type:enhancement, api:CSharp, ep:CUDA
