### ISSUE TITLE
Type of output argument does not match expected type 

### ISSUE THREAD

**Issue by albertkwek92** [microsoft/onnxruntime#2441] opened 2019-11-20 00:27 UTC
**Describe the bug**
I wrote a ML model using ML.net with C# and then exported it using the 
mlc.Model.ConvertToOnnx(model, trainData, destinationStream) method. However the onnx file created was not able to load on onnxruntime. I have tried this on Python, C++ and C# and the same error are given below.

Python:
![image](https://user-images.githubusercontent.com/38019827/69198186-bd217b80-0ae8-11ea-973d-91c08d3266b4.png)
C++:
![image](https://user-images.githubusercontent.com/38019827/69198229-df1afe00-0ae8-11ea-8074-e026cc5fdb79.png)
C#:
![image](https://user-images.githubusercontent.com/38019827/69293170-f4f9f300-0bbc-11ea-8dff-ce3d39c37ff6.png)

It seems that the types are mismatched but there aren't any configuration settings within ConvertToOnnx which allows me to change any of that. and for reference, the model input variables are of string types that are subsequently hot-encoded. I have also tried building a simpler model with DataType.Single and this time the onnx loader worked, so I am guessing the problem has to be with hotencoding + converting to onnx format. I have looked at the ONNX file using the ONNX viewer and saw the following:

![image](https://user-images.githubusercontent.com/38019827/69380274-e9630680-0c66-11ea-8691-3ee75f80cabb.png)

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- ONNX Runtime installed from (source or binary): Installed from Visual Studio
- ONNX Runtime version: 1.0.0
- Python version:
- Visual Studio version (if applicable): 16.3.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
Describe steps/code to reproduce the behavior:
1) Create ML model in C# using ML.net
a) Model uses feature columns of DataKind.String types which are then HotEncoded using OneHotEncoding(outputColumnName, inputColumnName)
2) Export ML model using ConvertToOnnx()
3) Try to load modelfile.onnx on Python/C++ with OnnxRuntime library

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by harishsk** [comment] 2019-11-22 17:42
Can you please share what version of ML.NET you are using?

**Comment by zn16** [comment] 2019-11-24 08:01
Actually I'm facing the similar problem. I was trying to run the ipynb which provided by [](http://onnx.ai/sklearn-onnx/auto_examples/plot_pipeline_lightgbm.html)
However the code will crash on
**sess = rt.InferenceSession("pipeline_lightgbm.onnx")**

**Comment by albertkwek92** [comment] 2019-11-24 19:33
> Can you please share what version of ML.NET you are using?
Its 1.4.0.

The rest of the dependencies are here as well:
![image](https://user-images.githubusercontent.com/38019827/69500234-2ec54500-0eae-11ea-9554-03d55d2f80b9.png)

**Comment by harishsk** [comment] 2019-11-26 17:37
@zn16 Are you using ML.NET anywhere in your scenario? If not, the cause of your issue is likely different.

albertkwek92 Onnx export support in ML.NET is still evolving and some of our work did not make it to v1.4. Can you please try one of the daily build nugets and let me know if that fixes the problem for you?

Daily NuGet builds of ML.NET also are available at
https://pkgs.dev.azure.com/dnceng/public/_packaging/MachineLearning/nuget/v3/index.json

**Comment by albertkwek92** [comment] 2019-11-27 22:53
Hey @harishsk  it seems that after adding this custom feed, I am still seeing the v1.4 in my nuget package manager. I don't see any new daily builds.
![image](https://user-images.githubusercontent.com/38019827/69764563-99cc8100-1125-11ea-9347-4fa34198bdf6.png)

**Comment by harishsk** [comment] 2019-12-17 22:30
Sorry for the delayed response. Can you please try again now and let me know? If you still see the same error, can you please click on the link above let me know if you see a valid json output? If not, can you please share what output you are seeing?

**Comment by faxu** [comment] 2020-02-27 17:49
@albertkwek92 do you still need assistance on this issue? if so, please provide more details as mentioned above; if not, please close this issue. Thanks!

**Closed** 2020-03-05 18:16 UTC
Labels: Converter, pending
