### ISSUE TITLE
Does onnxruntime support inference on a node-by-node and give the output result of each node?

### ISSUE THREAD

**Issue by moonjiaoer** [microsoft/onnxruntime#7723] opened 2021-05-17 06:09 UTC
I found that the output result of each node after an inference can be given through the session.run() function in onnxruntime, but I cannot call the inference process of each node such as the calculation of ‘conv’ .

Someone named ytaous replied as follows #7668：

 There might be a cmake flag you can add when building onnxruntime binary:

./build.sh --cmake_extra_defines onnxruntime_DEBUG_NODE_INPUTS_OUTPUTS=1

(if you are using python, install the whl first.)

To dump the input or output for each op, add env variable when running your command
ORT_DEBUG_NODE_IO_DUMP_INPUT_DATA=1 ORT_DEBUG_NODE_IO_DUMP_OUTPUT_DATA=1 python test.py

I've used it for training, inference should go thru the same code path. You can try and see if it works for you.

code ref: onnxruntime/core/framework/debug_node_inputs_outputs_utils.cc

However，I still don’t quite understand what you mean. What I need is to write code to change the output data of an operation when calling an onnx model, and then load this output data into the model as the input data for the next operation.  Which command should be used to implement operators like ‘conv’ or ‘clip’ separately?

**Comment by moonjiaoer** [comment] 2021-05-18 01:09
Maybe what I said is complicated. I just want to query the individual calling method of each operation such as ‘conv’ or ‘clip’ in the onnx model. Please don’t pay attention to what functions and goals I want to achieve.

**Comment by pranavsharma** [comment] 2021-05-18 06:52
Calling individual kernels is not supported yet in ORT public APIs. There's some [internal code](https://github.com/microsoft/onnxruntime/pull/7473/files) that you can use.

**Comment by mazhongzhong** [comment] 2021-05-19 02:40
> Calling individual kernels is not supported yet in ORT public APIs. There's some [internal code](https://github.com/microsoft/onnxruntime/pull/7473/files) that you can use.

Can you be more specific?

**Comment by hariharans29** [comment] 2021-05-25 00:39
Closing as this is an implicit dupe of https://github.com/microsoft/onnxruntime/issues/7782 which answers your main question

**Closed by hariharans29** 2021-05-25 00:39 UTC
Labels: type:support
