### ISSUE TITLE
C# Inference fails with YOLOv3 model

### ISSUE THREAD

**Issue by brantPTS** [microsoft/onnxruntime#1770] opened 2019-09-06 16:35 UTC
**Describe the bug**
Inference fails in C# .NET console application with YOLOv3 model. 

**Urgency**
Cannot use ONNX runtime without this fixed

**System information**
Windows 10 Pro
- ONNX Runtime 0.5 installed from NuGet
- Visual Studio 2019

**To Reproduce**

Create folder: C:\Temp\OnnxTest
Create Visual Studio 2019 .NET Console application: 
![image](https://user-images.githubusercontent.com/34780180/64444177-629b8600-d088-11e9-854b-8c8bbbc674ac.png)

Add NuGet reference to ONNX runtime (cuda)
![image](https://user-images.githubusercontent.com/34780180/64444198-70510b80-d088-11e9-91bf-8cdd1523ee9b.png)

Copy contents of example c# inference from ONNX source on GitHub: 
onnxruntime\csharp\sample\Microsoft.ML.OnnxRuntime.InferenceSample\Program.cs 
into:  
C:\Temp\OnnxTest\OnnxTest\OnnxTestConsole\Program.cs

Fix compile errors as follows: 

Change:
`using Microsoft.ML.OnnxRuntime.Tensors;
`To: 
`using System.Numerics.Tensors;
`
Change :
`options.GraphOptimizationLevel = GraphOptimizationLevel.ORT_ENABLE_EXTENDED;
`To: 
`options.SetSessionGraphOptimizationLevel(0); 
`
Copy model and data to these paths 

C:\Temp\OnnxTest\bench.in
C:\Temp\OnnxTest\squeezenet.onnx

Update paths in program.cs: 

`string modelPath = @"C:\Temp\OnnxTest\squeezenet.onnx";
`…
…
`float[] inputData = LoadTensorFromFile(@"C:\Temp\OnnxTest\bench.in"); // this is the data for only one input tensor for this model
`
Change platform to x64 in project properties/Build
![image](https://user-images.githubusercontent.com/34780180/64444119-4697e480-d088-11e9-96de-04545ba7dd14.png)

Run program, it should succeed

Now copy Yolo3 onnx model from here: https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov3
to here: 
C:\Temp\OnnxTest\yolov3.onnx
And update model path

`string modelPath = @"C:\Temp\OnnxTest\yolov3.onnx";
`
It will fail:

![image](https://user-images.githubusercontent.com/34780180/64444035-1e0fea80-d088-11e9-9541-2b1340fbc215.png)

It is difficult to guess what sort of input tensors should be fed into network since the dimensions contain negative numbers: 

![image](https://user-images.githubusercontent.com/34780180/64444071-2ec06080-d088-11e9-8a64-ebd5e58d545a.png)

 
A best guess at input tensors is as follows: 

`
int[] dims = new[] {1, 3, 224, 224};
var tensor = new DenseTensor<float>(inputData, dims);
container.Add(NamedOnnxValue.CreateFromTensor<float>("input_1", tensor));

int[] imageDimInputDims = new[] { 1, 2 };
float[] imageDimValues = new[] { 224F, 224F };
var tensorImageDims = new DenseTensor<float>(imageDimValues, imageDimInputDims);
container.Add(NamedOnnxValue.CreateFromTensor<float>("image_shape", tensorImageDims));
`

Will result in error: 
![image](https://user-images.githubusercontent.com/34780180/64444382-e05f9180-d088-11e9-9b9d-540cea63c63f.png)

Please advise on how to run an inference with this model.  A bonus would be a C# example on how to run an inference with this model as well: 
https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/faster-rcnn

**Comment by pranavsharma** [comment] 2019-09-06 17:58
@shahasad can you take a look? thanks!

**Comment by jignparm** [comment] 2019-09-11 20:01
@brantPTS , this error is due to a shape inference bug in OnnxRuntime version 0.5. I was able to reproduce the error as well.

![image](https://user-images.githubusercontent.com/13698702/64729848-df689e80-d492-11e9-87a3-f7a95821cf64.png)


The fix is already checked into the master branch, and the Yolov3 model  runs successfully for me using the  snippet below.

You can build the DLLs from source to get the fix. If you need a NuGet package, you should be able to create one using the same file layout as in version 0.5, but using the bits from your local build. 

[InferenceTest.cs](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs)
``` c#
        [Fact]
        private void mytest()
        {
            var modelsDir = @"D:\modelsyolov3\opset8";
            var modelRoot = new DirectoryInfo(Path.Combine(modelsDir));
            foreach (var modelDir in modelRoot.EnumerateDirectories())
            {
                var onnxModelNames = modelDir.GetFiles("*.onnx");
                var onnxModelFileName = Path.Combine(modelsDir, modelDir.Name, onnxModelNames[0].Name);
                using (var session = new InferenceSession(onnxModelFileName))
                {
                    var testRoot = new DirectoryInfo(Path.Combine(modelsDir, modelDir.Name));
                    var testData = testRoot.EnumerateDirectories("test_data*").First();

                    ///// Load test data
                    var dataIn = LoadTensorFromFilePb(Path.Combine(modelsDir, modelDir.Name, testData.ToString(), "input_0.pb"));

                    ///// Create Inputs
                    var nov = new List<NamedOnnxValue>();
                    nov.Add(
                        NamedOnnxValue.CreateFromTensor<float>
                        ("input_1", new DenseTensor<float>(dataIn, new int[] { 1, 3, 416, 416 })));
                    nov.Add(
                        NamedOnnxValue.CreateFromTensor<float>
                        ("image_shape", new DenseTensor<float>(new float[] { 416, 416 }, new int[] { 1, 2 })));

                    ///// Run Session
                    using (var resnov = session.Run(nov))
                    {
                        var res = resnov.ToArray()[0].AsTensor<float>().ToArray<float>();
                    }
                }
            } //model
        }
```

**Comment by brantPTS** [comment] 2019-09-11 23:26
@jignparm, that is great news - thank you for the prompt fix. I will try to build from source and test.  Any idea when a 0.6 release may be published on NuGet? 

Thanks,
Brant

**Comment by jignparm** [comment] 2019-09-12 00:06
The next release will be end of Oct.

**Closed by jignparm** 2019-09-12 00:06 UTC
Labels: bug

**Comment by BarkenBark** [comment] 2019-10-28 15:29
Any updates on when we can expect a release which includes the fix to this issue?

**Comment by jignparm** [comment] 2019-10-28 22:25
The release branch of v1.0 is cut. The NuGet packages will be available within a few days.


https://github.com/microsoft/onnxruntime/tree/rel-1.0.0

**Comment by hoaquocphan** [comment] 2020-03-04 06:14
Hi Mrs @jignparm 

I'm importing yolov3 to onnx by CPP.
the dimensions is above post.
input_1 : (1, 3, 416, 416)
image_shape: (1, 2, 416, 416)

but it report the error as below:

> Got invalid dimensions for input: input_1 for the following indices
>  index: 1 Got: 2 Expected: 3
>  Please fix either the inputs or the model.

so I fixed it with 2 ways as below:

1/  
input_1 : (1, 3, 416, 416)
image_shape: (1, 3, 416, 416)
2/ 
input_1 : (1, 2, 416, 416)
image_shape: (1, 3, 416, 416)

so which way is correct.
Please let me know.

Thanks

**Comment by jignparm** [comment] 2020-03-05 23:54
>so which way is correct.

It should be  "input_1 =  image_shape: =(1, 3, 416, 416)".  If you copy-paste the code snippet above, it should work.

**Comment by hoaquocphan** [comment] 2020-03-06 01:46
Dear @jignparm 

Thanks for your reply.
>  If you copy-paste the code snippet above, it should work.
But I'm writing CPP code (not C#), so cannot copy that.
Could you help me to share a code snippet of CPP?

I'm not really understand the preprocessing step of yolov3, So could you explain more about it.
As I understanding, this step will resize the freestyle image to 416x416, If I cannot find function to resize the image in CPP, could I fix the image input to 416x416 and skip the preprocessing step?

Thanks
