### ISSUE TITLE
TensorRT EP segfault on model with dynamic shape

### ISSUE THREAD

**Issue by haijieg** [microsoft/onnxruntime#14970] opened 2023-03-08 23:40 UTC
### Describe the issue

The attached ONNX model is a Distilbert implementation and is exported from PyTorch with dynamic axis. Directly running with TRT EP does not work because the lack of shape information. After applying symbolic shape inference, the resulting model causes TRT EP to segfault:

```
2023-03-08 14:36:23.096387222 [E:onnxruntime:Default, tensorrt_execution_provider.h:58 log] [2023-03-08 22:36:23   ERROR] 2: [optimizer.cpp::getFormatRequirements::3103] Error Code 2: Internal Error (Assertion !n->candidateRequirements.empty() failed. No supported formats for /Reshape_3)
Segmentation fault (core dumped)
```

CUDA EP runs fine.

### To reproduce

Download `model.onnx` from https://drive.google.com/file/d/1ZI03nHm_kRG5e-AAcAOk-FlNMGlD7P_Z/view?usp=share_link
Download `external_data` from https://drive.google.com/file/d/1P5ZM_yuRoWuUzzIqwQzAL3NmcSUKOZYg/view?usp=share_link
Download `repro.zip` from attachment and put in the same folder as `model.onnx` and `external_data`

`python trt_repro.py tensorrt` will segfault
`python trt_repro.py cuda` will run successfully

[repro.zip](https://github.com/microsoft/onnxruntime/files/10926255/repro.zip)

The issue is reproducible with both 8.4.3.1 and 8.5.3.1 (latest) version of TensorRT

```
import onnx
import numpy as np
import sys
import onnxruntime
from onnxruntime.tools.symbolic_shape_infer import SymbolicShapeInference
from onnxruntime import InferenceSession


def shape_inference(model):
    return SymbolicShapeInference.infer_shapes(model, auto_merge=True)


def make_feed_dict(seqlen):
    input_ids = np.random.randint(101, 999, (1, seqlen))
    masks = np.ones((1, seqlen), np.int64)
    const = np.array(768)
    numpy_inputs = {
        'input_0': input_ids,
        'input_1': masks,
        'input_2': const,
        'input_3': const,
        'input_4': const,
        'input_5': const,
        'input_6': const,
        'input_7': const,
    }
    return dict((k, onnxruntime.OrtValue.ortvalue_from_numpy(v)) for k, v in numpy_inputs.items())


def run(sess, seqlen):
    feed_dict = make_feed_dict(seqlen)
    output = sess.run(['output_0', 'output_1'], feed_dict)
    print([x.shape for x in output])
    return output


if __name__ == "__main__":
    if len(sys.argv) > 1:
        if sys.argv[1] == 'tensorrt':
            ep = 'TensorrtExecutionProvider'
        elif sys.argv[1] == 'cuda':
            ep = 'CUDAExecutionProvider'
        else:
            ep = 'CPUExecutionProvider'
    else:
        ep = 'CPUExecutionProvider'
    model_path = 'model.onnx'
    model = onnx.load(model_path)
    new_model = shape_inference(model)
    onnx.save(new_model, "new_model.onnx")
    sess = InferenceSession("new_model.onnx", providers=[ep])
    run(sess, 6)
    run(sess, 6)  # works
    run(sess, 8)  # segfault
```

### Urgency

This problem causes segfault on model inference and blocks model from going into production.

### Platform

Linux

### OS Version

Ubuntu 20.04

### ONNX Runtime Installation

pip install

### ONNX Runtime Version or Commit ID

onnxruntime-gpu==1.13.1

### ONNX Runtime API

Python

### Architecture

X86

### Execution Provider

TensorRT

### Execution Provider Library Version

nvidia-cublas-cu11==11.10.3.66 nvidia-cublas-cu117==11.10.1.25 nvidia-cuda-nvrtc-cu11==11.7.99 nvidia-cuda-runtime-cu11==11.7.99 nvidia-cuda-runtime-cu117==11.7.60 nvidia-cudnn-cu11==8.5.0.96 nvidia-cudnn-cu116==8.4.0.27 nvidia-cufft-cu11==2022.4.8 nvidia-cufft-cu117==10.7.2.50 nvidia-curand-cu11==2022.4.8 nvidia-curand-cu117==10.2.10.50 nvidia-pyindex==1.0.9 nvidia-tensorrt==8.4.3.1

**Comment by yf711** [comment] 2023-03-15 00:48
Hi @haijieg Could you try [TensorRT 8.6 EA](https://docs.nvidia.com/deeplearning/tensorrt/release-notes/index.html#rel-8-6-0-EA) on your script and see if it helps?

This seems to be an [existing TensorRT issue](https://github.com/NVIDIA/TensorRT/issues/2751) and get fixed on [TRT 8.6 EA](https://docs.nvidia.com/deeplearning/tensorrt/release-notes/index.html#rel-8-6-0-EA) recently. The issue is reproducible on my side using TRT 8.5 but on TRT 8.6 EA your script works fine.

**Comment by yf711** [comment] 2023-03-27 18:16
Hi @haijieg is your issue fixed? 
I will close this issue for now and feel free to reopen if you have more questions related to that. Thanks!

**Closed by yf711** 2023-03-27 18:16 UTC
Labels: ep:CUDA, ep:TensorRT

**Comment by haijieg** [comment] 2023-05-01 23:14
Sorry for the delay. How do I try TRT 8.6EA? Is it compatible with ORT 1.14 or do I need to build 1.15 from source?

**Comment by yf711** [comment] 2023-05-01 23:21
Hi @haijieg the ORT 1.14 is compatible with TRT8.6EA. 
You can install TRT 8.6EA as Nvidia [suggested](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing) and update environment variable.
