### ISSUE TITLE
quantize to int8:    assert (bias_name not in self.quantized_value_map)

### ISSUE THREAD

**Issue by mathmax12** [microsoft/onnxruntime#7507] opened 2021-04-29 22:26 UTC
**Describe the bug**
Try to convert the model to int8 format

got this issue: 
```
Beginning calibration...
Traceback (most recent call last):
  File "onnx_static_int8_quantize.py", line 114, in <module>
    main()
  File "onnx_static_int8_quantize.py", line 110, in main
    weight_type=weight_type)
  File "C:\Users\.conda\envs\se_demo\lib\site-packages\onnxruntime\quantization\quantize.py", line 224, in quantize_static
    quantizer.quantize_model()
  File "C:\Users\.conda\envs\se_demo\lib\site-packages\onnxruntime\quantization\onnx_quantizer.py", line 196, in quantize_model
    op_quantizer.quantize()
  File "C:\Users\.conda\envs\se_demo\lib\site-packages\onnxruntime\quantization\operators\conv.py", line 94, in quantize
    quantized_bias_name = self.quantizer.quantize_bias_static(node.input[2], node.input[0], node.input[1])
  File "C:\Users\.conda\envs\se_demo\lib\site-packages\onnxruntime\quantization\onnx_quantizer.py", line 572, in quantize_bias_static
    assert (bias_name not in self.quantized_value_map)
AssertionError
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
windows

I have tried to convert another model with my script.  So the function of the script should be correct

**Comment by pranav-prakash** [comment] 2021-04-30 04:38
Can you post the model that you're trying to convert? Are you also using latest build of ORT? I don't see how it's possible to hit that assertion considering that we explicitly guard against it in line 534

```
        # Handle case where bias already in quantizatio map
        if bias_name in self.quantized_value_map:
            return self.quantized_value_map[bias_name].q_name
```

**Comment by mathmax12** [comment] 2021-05-01 05:03
@pranav-prakash 
Thanks for investigating the issue You could access the model from:
https://drive.google.com/file/d/1c9q7nlqRXwr62ko-IvRQgixKUEkTKxM6/view?usp=sharing

**Comment by pranav-prakash** [comment] 2021-05-01 05:09
(I'm not an MS employee, I just happen to use the quantizer heavily).

I'm unable to access the model (requires me to sign in). Also did you double check that you're using the latest build of ORT (1.7 from pypi should work I think) – as mentioned I remember explicitly adding the check for the bias already in quantization map in one of my upstreamed PRs, so  that `bias_name not in self.quantized_value_map` assertion should never fire.

**Comment by mathmax12** [comment] 2021-05-01 05:21
Thanks for the info.
Appreciate your help.
I check my onnxruntime version is 1.7.0
`>>> import onnxruntime
>>> onnxruntime.__version__
'1.7.0'
>>>`

**Comment by pranav-prakash** [comment] 2021-05-01 05:39
Ok it seems the 1.7.0 release did not include commit https://github.com/microsoft/onnxruntime/commit/d5175795d2b7f2db18b0390f394a49238f814668#diff-4485c97118ce24f60eb23e117b4db65319f3000fbb71e639e166c795d4479da5 where I fixed this.

I'm not sure why 1.7.2 is not on pypi yet (even though it's on GH releases). You can either compile and install HEAD manually, install the nightly https://test.pypi.org/project/ort-nightly/ or just manually add that single line to the `onnx_quantizer.py` in your python package install directory.

**Comment by mathmax12** [comment] 2021-05-01 07:04
I tried the nightly build and got a different error:
`Beginning calibration...
ORT Telemetry: Ver = 1.7.0; Event = SessionCreation
ORT Telemetry: Ver = 1.7.0; Event = SessionCreation
ORT Telemetry: Ver = 1.7.0; Event = SessionCreation
Traceback (most recent call last):
  File "onnx_static_int8_quantize.py", line 114, in <module>
    main()
  File "onnx_static_int8_quantize.py", line 110, in main
    weight_type=weight_type)
  File "C:\Users\bigtree\.conda\envs\se_demo\lib\site-packages\onnxruntime\quantization\quantize.py", line 224, in quantize_static
    quantizer.quantize_model()
  File "C:\Users\bigtree\.conda\envs\se_demo\lib\site-packages\onnxruntime\quantization\onnx_quantizer.py", line 196, in quantize_model
    op_quantizer.quantize()
  File "C:\Users\bigtree\.conda\envs\se_demo\lib\site-packages\onnxruntime\quantization\operators\concat.py", line 20, in quantize
    quantized_input_value = self.quantizer.quantized_value_map[node.input[0]]
KeyError: '816'`

I just made the link publicly can you try to access it again?
https://drive.google.com/file/d/1c9q7nlqRXwr62ko-IvRQgixKUEkTKxM6/view?usp=sharing

**Comment by pranav-prakash** [comment] 2021-05-01 20:02
Hm I think that's a separate bug (possibly in the recently introduced `Concat` quantization).@yufenglee is probably more familiar with this.

In the meantime, the quickest and easiest workaround would be to use version 1.7 from pypi but manually edit `site-packages/onnxruntime/quantization/onnx_quantizer.py/` in your python site-packages folder to add the lines
```
        # Handle case where bias already in quantizatio map
        if bias_name in self.quantized_value_map:
            return self.quantized_value_map[bias_name].q_name
```
as seen in commit https://github.com/microsoft/onnxruntime/commit/d5175795d2b7f2db18b0390f394a49238f814668

**Comment by mathmax12** [comment] 2021-05-03 19:07
I changed the \site-packages\onnxruntime\quantization\onnx_quantizer.py by remove the 
`assert (bias_name not in self.quantized_value_map)` and replace it with above.
` # assert (bias_name not in self.quantized_value_map)
  # Handle case where bias already in quantizatio map
  if bias_name in self.quantized_value_map:
      return self.quantized_value_map[bias_name].q_name`

But still got the issue :
"KeyError: '816'`"
Did I miss anything?
Thanks

**Comment by zhanghuanrong** [comment] 2021-05-03 19:27
Yes, this is some bug, it will be fixed soon.
And for your model here, no matter the bug is fixed or not, you'd better add "Concat_323" as black node, so that no extra quantize for the than is made. Could you please try to disable Concat_323 now which I think it could unblock you.

**Comment by mathmax12** [comment] 2021-05-03 19:52
Thanks for that. But where should I disable the Concat_323?

**Comment by zhanghuanrong** [comment] 2021-05-03 22:15
quantized_static method have a parameter black_nodes=["Concat_323"]
not sure the exact name.

**Comment by zhanghuanrong** [comment] 2021-05-03 22:16
https://github.com/microsoft/onnxruntime/pull/7558
is for the fix for this root cause.

**Closed** 2021-05-14 20:53 UTC
Labels: type:bug
