### ISSUE TITLE
onnxruntime slower than scikit in batch predictions

### ISSUE THREAD

**Issue by prabhat00155** [microsoft/onnxruntime#827] opened 2019-04-12 19:58 UTC
onnxruntime outperforms scikit in terms of prediction time in case of atomic predictions but suffers with batch predictions especially with increase in batch size.

Here is a table for some regression pipelines (> 170) and what % of times onnxruntime is faster.
500, 5k, ..., 25k represents the number of test instances.
Regression                 | 500    | 5k      | 10k     | 15k   | 20k      | 25k |  
10 features, batch     | 62.86 | 1.71    | 0         | 0.57 | 2.87    | 1.71  | 
100 features, batch   | 55.43 | 25.29 | 18.29 | 17.14 | 22.86 |  
100 features, atomic | 100     | 96      |  

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 0.3.0
- Python version: 3.6.4
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
Create a Scikit GradientBoostingRegressor (or Classifier) model, convert it into onnx (specify the input size as X_test.shape, where X_test is the input array), and then run prediction using onnxruntime and scikit and compare their prediction time.

**Comment by faxu** [comment] 2019-05-24 19:14
Update: this item is on the backlog and will be investigated in upcoming months.

**Comment by RandySheriffH** [comment] 2019-06-17 20:40
Python 3.7, Scikit 0.19, Onnx 1.5, OnnxRuntime 0.4
Tested GradientBoostingRegressor model with 100 features:
////////////////////////////////////////////////////////////////////////////
25000 scikit batch prediction for 259659 microsecond
25000 onnxruntime batch prediction for 20366 microsecond
////////////////////////////////////////////////////////////////////////////

**Comment by RandySheriffH** [comment] 2019-06-17 20:45
Trained model by:
/////////////////////////////////////////////////////////////////
X = np.random.rand(1000,100)
y = np.random.rand(1000,)
clf = ensemble.GradientBoostingRegressor(**params)
clf.fit(X_train, y_train)
////////////////////////////////////////////////////////////
Any pointers?

**Comment by prabhat00155** [comment] 2019-06-18 23:30
Here is a sample code you could use. I am doing batch predictions 10 times for both scikit and onnx models and calculating the mean prediction times. You could try different models and compare the predictions times.

import time
import numpy as np
import onnxmltools
from onnxruntime import InferenceSession
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType, Int64TensorType


def run_classification(n_features, n_samples, n_classes):
    X, y = make_classification(n_features=n_features, n_samples=n_samples, n_classes=n_classes,
                               n_informative=5, random_state=42)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)
    log_result = []
    res = []
    model = RandomForestClassifier()
    model.fit(X_train, y_train)
    X_test = X_test.astype(np.float32)
    sktime = []
    for i in range(10):
        sk_pred1, sk_pred2 = [], []
        start = time.time()
        sk_pred1.append(model.predict_proba(np.array(X_test))) # run 10 times and calculate mean, std 
        sk_pred2.append(np.argmax(np.array(X_test)))
        end = time.time()
        sktime.append(end - start)
    # Convert model to onnx and predict, run per-instance prediction
    onnx_model = convert_sklearn(model, 'model', [('input_0', FloatTensorType(X_test.shape))])
    onnxmltools.utils.save_model(onnx_model, 'm1.onnx')
    sess = InferenceSession('m1.onnx')
    onnx_time = []
    for i in range(10):
        onnx_result = []
        start = time.time()
        onnx_result.append(sess.run(None, {'input_0': np.array(X_test)}))
        end = time.time()
        onnx_time.append(end - start)
    log_result.append([np.mean(sktime), np.std(sktime), np.mean(onnx_time), np.std(onnx_time)])
    return log_result  

run_classification(1000, 50000, 5)

**Comment by RandySheriffH** [comment] 2019-06-20 18:45
Thanks, now I could reproduce the gap. Investigating...

**Comment by RandySheriffH** [comment] 2019-06-21 21:27
Let's review a fix: https://github.com/microsoft/onnxruntime/pull/1276

**Comment by RandySheriffH** [comment] 2019-06-25 20:15
PR checked in, closing the issue.

**Comment by prabhat00155** [comment] 2019-06-26 22:24
This issue is not just in trees, I found onnxruntime consistently slower accross all classifiers and regressors. Have you checked with other models like linear, MLP, NB, etc?

**Comment by snnn** [comment] 2019-07-25 21:58
Reopen it because the fix got reverted

**Comment by amjbara** [comment] 2019-12-30 04:03
Any update on this?

**Comment by faxu** [comment] 2020-03-10 23:10
@xadupre can you update this with the latest improvements in ORT?

**Comment by faxu** [comment] 2020-05-19 18:44
These should be addressed by the latest updates in 1.3.0

**Closed by faxu** 2020-05-19 18:44 UTC
Labels: enhancement, performance
