### ISSUE TITLE
Resnet50 fails if update submodule to latest ONNX

### ISSUE THREAD

**Issue by BowenBao** [microsoft/onnxruntime#1053] opened 2019-05-16 21:13 UTC
**Describe the bug**

Recent commit in onnx(https://github.com/onnx/onnx/pull/1988) updated shape inference for conv. This bug was discovered from CI for (https://github.com/microsoft/onnxruntime/pull/1052). With failure message 
```1: [  FAILED  ] ONNXModelsTests/ONNXModelsTest.LoadFromProtobuf/9, where GetParam() = "resnet50" (52 ms)```,
and root cause 
```Load model from model.onnx failed:[ShapeInferenceError] Stride is bigger than Kernel shape```.

It seems resnet50 has a convolution node with ```strides=(2,2)``` and ```kernel_shape=(1,1)```.

**Comment by hariharans29** [comment] 2019-05-16 21:28
Hi @stevenlix  - This seems to be a regression introduced in this commit -  https://github.com/onnx/onnx/pull/1988

**Comment by hariharans29** [comment] 2019-05-16 23:19
Hi @stevenlix @BowenBao @linkerzhang -

https://github.com/onnx/onnx/pull/2023 should fix this issue. (It is the output shape computation logic in ORT). 

Please review. Thanks!

**Comment by BowenBao** [comment] 2019-05-17 00:37
@hariharans29  thanks for looking into this so quickly!

**Comment by hariharans29** [comment] 2019-05-17 19:20
@stevenlix's PR should resolve this finally - https://github.com/onnx/onnx/pull/2028. Will close this after the PR is merged.

**Closed** 2019-05-20 18:16 UTC
