### ISSUE TITLE
[Mobile] onnxruntime-react-native app crashes during session.run

### ISSUE THREAD

**Issue by seuklee1025** [microsoft/onnxruntime#17623] opened 2023-09-20 04:59 UTC
### Describe the issue

I am using onnxruntime-react-native. There is an issue where the app crashes during session.run. 

This happens consistently with any ORT model and across various versions.

We created a blank array to match the shape of the input and challenged many of the models released in the port file.

The problem is that the app turns off as soon as you infer without errors

I want to know the solution.

### To reproduce

all ort inference code

### Platform

Android

### OS Version

1.16

### ONNX Runtime Installation

Built from Source

### Package Name (if 'Released Package')

None

### ONNX Runtime Version or Commit ID

1.16

### ONNX Runtime API

JavaScript

### Architecture

ARM64

### Execution Provider

Default CPU

**Comment by seuklee1025** [comment] 2023-09-20 05:05
```
import { Asset } from "expo-asset";
import React, { useEffect } from "react";
import * as ort from 'onnxruntime-react-native'
import { Alert, View, Text } from "react-native";

const App = () => {

  useEffect(() => {
    initLoadModel();
  }, [])

  const initLoadModel = async () => {
    try {
      const assets = await Asset.loadAsync(require('../assets/models/mnist.ort'));
      const modelUri = assets[0].localUri;
      if (!modelUri) {
        Alert.alert('failed to get model URI', `${assets[0]}`);
      } else {
        const myModel = await ort.InferenceSession.create(modelUri);
        Alert.alert(
          'model loaded successfully',
          `input names: ${myModel.inputNames}, output names: ${myModel.outputNames}`);


        const inputData = new Float32Array(28 * 28);
        const feeds: Record<string, ort.Tensor> = {};
        feeds[myModel.inputNames[0]] = new ort.Tensor(inputData, [1, 28, 28]);


        console.log("feeds :: ", feeds)


        const fetches = await myModel.run(feeds,);

        console.log("run 후에")
        const output = fetches[myModel.outputNames[0]];
        console.log(output)
        if (!output) {
          Alert.alert('failed to get output', `${myModel.outputNames[0]}`);
        } else {
          Alert.alert(
            'model inference successfully',
            `output shape: ${output.dims}, output data: ${output.data}`);
        }
      }
    } catch (e) {
      Alert.alert('failed to load model', `${e}`);
      throw e;
    }

  }
  return (
    <View>
      <Text>테스트 진행중입니다!</Text>
    </View>
  )
}
export default App;
```

**Comment by seuklee1025** [comment] 2023-09-20 05:06
The code died in run and was tested with a poco phone.

**Comment by YUNQIUGUO** [comment] 2023-09-20 05:47
Just to confirm, you are using onnxruntime-react-native 1.16.0 (released couple hours ago)?

Also, does the crash only happen on real device or does it also happen in simulator?

**Comment by seuklee1025** [comment] 2023-09-20 05:51
The simulator did not conduct the test, but proceeded with the pocophone.

1.14, 1.15, and 1.16, which came out about five hours ago, all proceeded.

**Comment by skottmckay** [comment] 2023-09-20 06:24
What shape input does the model require? Most often I've seen mnist take a 4D input with shape {1, 1, 28, 28} and `run` will fail if there's a shape mismatch. I would have expected an error message to be available somewhere though.

**Comment by seuklee1025** [comment] 2023-09-20 06:59
@skottmckay 

Although we did not check what the exact input of the mnist was, we found that other models (1, 3, 224, 224) that knew the exact input were also interrupted by session.run.

We also found that if the input is different, the model outputs an input shape related error.

**Comment by seuklee1025** [comment] 2023-09-20 07:34
If the input is different, the app will not die. 
In other words, the app dies only when inference is performed in session.run

**Comment by seuklee1025** [comment] 2023-09-20 09:16
I'm uploading the library in case it's a library problem
```
{
  "name": "tugboatrn",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@tensorflow/tfjs": "3.7.0",
    "@tensorflow/tfjs-backend-webgl": "3.7.0",
    "@tensorflow/tfjs-converter": "3.7.0",
    "@tensorflow/tfjs-core": "3.7.0",
    "@tensorflow/tfjs-react-native": "0.8.0",
    "expo": "^49.0.0",
    "expo-asset": "^8.10.1",
    "install-expo-modules": "^0.6.3",
    "onnxruntime-react-native": "1.16.0", 
    "react": "18.2.0",
    "react-native": "0.72.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.8",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "engines": {
    "node": ">=16"
  },
  "main": "index.js",
  "license": "MIT"
}
```

**Comment by bartproo** [comment] 2023-09-21 00:26
I have the same issue as mentioned here #17541

**Comment by saeu5407** [comment] 2023-09-21 07:35
I hope the problem is solved quickly!

**Comment by skottmckay** [comment] 2023-10-03 08:01
Can you try using the XNNPACK execution provider to see if that avoids the issue? Requires onnxruntime 1.16. 

Details on how to enable that in this comment: https://github.com/microsoft/onnxruntime/issues/17541#issuecomment-1742396276

**Comment by skottmckay** [comment] 2023-10-09 21:58
Closing. Issue is covered in more detail in #17541 and #17647

**Closed by skottmckay** 2023-10-09 21:58 UTC
Labels: platform:mobile, api:Javascript
