### ISSUE TITLE
Onnx runtime gpu usage

### ISSUE THREAD

**Issue by ahmad4633** [microsoft/onnxruntime#8171] opened 2021-06-28 07:34 UTC
**Describe the bug**
Onnxruntime is allocating 3.5GB of my gpu memory on onnxruntime version 1.8 with cuda provider, almost all my gpu memory, while onnxruntime version 1.7.1 is allocating 0.4GB. This is happening on the C# API.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- ONNX Runtime installed from (source or binary): nuget 
- ONNX Runtime version: 1.8
- Python version:
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2
- GPU model and memory: gtx 1050ti

**To Reproduce**
- any inference for any model will generate this usage difference,

**Expected behavior**
inference run on onnxruntime 1.7.1 will take much less than the usage of the onnxruntime 1.8 inference.

**Comment by boenshao** [comment] 2021-06-28 09:15
Can confirm similar issue with Python API, onnxruntime v1.8.0 always allocate all the available GPU memory (24GB on 3090).
Revert back to v1.7.0 produce expected behavior.

**Comment by yuslepukhin** [comment] 2021-06-28 16:47
Can either of you share a repro case with a small script and a model?

**Comment by boenshao** [comment] 2021-06-29 09:22
Minimal reporduce: https://drive.google.com/file/d/12Zo_4L6OxQzS-oriIFkClC7xLwB7v_b0/view?usp=sharing

A basic CUDA session is sufficient to trigger the bug, it happened to two of our in-house detection model (not tested on other models yet), so it may (full speculation) due to the system environment or an operator that we use across models.

Our system configuration...

- Ubuntu 20.04 LTS (kernel 5.4.0, x86_64)
- NVIDIA-driver 455.32
- CUDA 11.1
- cudnn 8.1.1
- single RTX3090

**Comment by yuslepukhin** [comment] 2021-06-30 17:11
This is a repro and is being addressed.

**Comment by pranavsharma** [comment] 2021-06-30 21:06
The fix for this will be released as part of 1.8.1 patch release. Thanks.

**Closed** 2021-07-15 18:59 UTC
Labels: component:coreruntime, ep:CUDA, type:bug, type:support
