### ISSUE TITLE
OpenVINO Execution Provider is broken?

### ISSUE THREAD

**Issue by GuanLuo** [microsoft/onnxruntime#2169] opened 2019-10-18 03:23 UTC
**Describe the bug**
We build ORT with OpenVINO EP almost daily, and the build suddenly failed to load a model with OpenVINO EP. The model was working before. The error message is the following:
```
2019-10-17 22:44:23.566342379 [W:onnxruntime:Default, openvino_execution_provider.cc:495 GetCapability] [OpenVINO-EP] Rejecting as Model Optimizer cannot convert this model.Python function call failure
```
I looked into the provider implementation and ran the Python part directly, the detailed error message is
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/openvino_mo.py", line 316, in driver_R1
    graph = protobuf2nx(model_proto)
  File "/data/dldt/openvino_2019.1.144/deployment_tools/model_optimizer/mo/front/onnx/loader.py", line 65, in protobuf2nx
    initializers = create_graph_with_nodes(pb.graph.initializer, get_id=lambda pb: pb.name, get_attrs=protobuf_attrs)
  File "/data/dldt/openvino_2019.1.144/deployment_tools/model_optimizer/mo/graph/graph.py", line 722, in create_graph_with_nodes
    graph.add_node(get_id(node), **get_attrs(node))
  File "/data/dldt/openvino_2019.1.144/deployment_tools/model_optimizer/mo/graph/graph.py", line 439, in add_node
    in_ports_count = node.in_ports_count if node.has_valid('in_ports_count') else None
  File "/data/dldt/openvino_2019.1.144/deployment_tools/model_optimizer/mo/graph/graph.py", line 120, in has_valid
    return self.has(k) and not self.graph.node[self.node][k] is None
  File "/data/dldt/openvino_2019.1.144/deployment_tools/model_optimizer/mo/graph/graph.py", line 117, in has
    return k in self.graph.node[self.node]
AttributeError: 'Graph' object has no attribute 'node'
```

**Urgency**
None.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: post rel-0.5.0 (c24d7a8a0a95002cfde70db8ffdac1a1d95b3ca7)
- Python version: 3.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
- CUDA/cuDNN version: 
- GPU model and memory:

**To Reproduce**
* The model is normal resnet model, you can get it here: https://drive.google.com/open?id=1_ks9WMyDx1b1KzuucpzHBDGbvG6TTbYK
* build the ORT with OpenVINO docker image with helper script
```
mkdir -p `pwd`/build
tools/ci_build/github/linux/run_dockerbuild.sh -o ubuntu16.04 -p 3.6 -r `pwd`/build -d openvino -x "--use_openvino CPU_FP32 --build_wheel"
```
* Run the docker image with build directory mounted (/tmp is where I put the model) `docker run -it --volume `pwd`/build:/build --volume /tmp:/tmp/host onnxruntime-ubuntu16.04-openvino`
* Install the wheel file in `/build/Release/dist` and run Python with the following
```
import onnxruntime
onnxruntime.InferenceSession("/tmp/host/resnet50-1.2.onnx")
```
* Using Python just because it is easy to reproduce, the same issue happens with C library

**Expected behavior**
The model can be loaded with OpenVINO execution provider.

**Additional context**
It may be irrelavant, but I noticed that the version of Python dependencies installed by OpenVINO for ONNX is different (networkx and numpy to be precise):
```
Successfully installed decorator-4.4.0 defusedxml-0.6.0 networkx-2.4 numpy-1.17.3 onnx-1.6.0 protobuf-3.10.0 six-1.12.0 test-generator-0.1.1 typing-extensions-3.7.4
```
In the previous working build:
```
Successfully installed decorator-4.4.0 defusedxml-0.6.0 networkx-2.3 numpy-1.17.2 onnx-1.6.0 protobuf-3.10.0 six-1.12.0 test-generator-0.1.1 typing-extensions-3.7.4
```

**Comment by jywu-msft** [comment] 2019-10-18 19:56
@smkarlap , @suryasidd  do you guys have any idea?

**Comment by suryasidd** [comment] 2019-10-18 22:44
The cause of this error is networkx version. In version 2.4, they removed Graph.node function and changed it to Graph.nodes. This will be fixed in the upcoming version. As a temporary workaround i would suggest to uninstall networkx 2.4 and install networkx 2.3 to run this model. Thank you for getting this to our attention.

**Comment by jywu-msft** [comment] 2019-10-21 22:01
Since the issue has been identified, I'm going to close this issue.

**Closed by jywu-msft** 2019-10-21 22:01 UTC
Labels: OpenVINO
