### ISSUE TITLE
Python: Inconsistent error behavior when creating sessions for different providers

### ISSUE THREAD

**Issue by paradigmn** [microsoft/onnxruntime#9747] opened 2021-11-12 20:24 UTC
**Describe the bug**
This issue concerns python wheels with support for multiple providers. When creating an inference session, a list of providers can be provided. The behavior for different providers is not consistent:
- If the provider can be loaded without issue, the session is created as expected.
- If the CUDA provider fails, a low level error message is printed and CPU is used as fallback (although not in provider list)
- If the TensorRT provider fails,  a low level error message is printed and python crashes with segfault
- If the OpenVINO provider fails, a low level error message is printed and python crashes with segfault

**Urgency**
Medium 

**System information**
- OS Platform and Distribution: Debian
- ONNX Runtime installed from: Source
- ONNX Runtime version: 1.9.1
- Python version: 3.8
- Visual Studio version (if applicable): -
- GCC/Compiler version (if compiling from source): 9.3
- CUDA/cuDNN version: 11.4.0/8.2.2.26
- GPU model and memory: V100@32GB
- OpenVINO: 2021.4.1
- TensorRT: 8.0.1.6

**To Reproduce**
- Build onnxruntime from tag v1.9.1 for Linux x64 with CUDA, TensorRT and OpenVino provider
- Install onnxruntime in an environment without CUDA, TensorRT and OpenVino available
- Create session in Python:
`sess = ort.InferenceSession("model.onnx", providers=[provider])` 
where provider = CUDAExecutionProvider/TensorrtExecutionProvider/OpenVINOExecutionProvider

**Expected behavior**
A Python warning should be printed, if first provider in list failed. Subsequently the next provider should be used. If no provider in list is usable, an exception should be raised. No auto fallback to CPU should be used if not explicitly requested.

**Additional context**
Error messages for different providers:
`2021-11-12 20:21:14.665899104 [E:onnxruntime:Default, provider_bridge_ort.cc:940 Get] Failed to load library libonnxruntime_providers_cuda.so with error: libcublas.so.11: cannot open shared object file: No such file or directory
build session`
`2021-11-12 20:45:13.119746126 [E:onnxruntime:Default, provider_bridge_ort.cc:940 Get] Failed to load library libonnxruntime_providers_tensorrt.so with error: libcudart.so.11.0: cannot open shared object file: No such file or directory`
`2021-11-12 20:58:23.981654616 [E:onnxruntime:Default, provider_bridge_ort.cc:940 Get] Failed to load library libonnxruntime_providers_openvino.so with error: libonnx_importer.so: cannot open shared object file: No such file or directory`

**Comment by yuslepukhin** [comment] 2021-11-15 18:33
CPU provider is always on the list and serves as a fallback for ops that may not be supported by the target providers.
You just need to make sure that the executable that loads ORT can find all the libraries. In this case, it is obvious that NVIDIA libraries are either not installed or not in the LD_LIBRARY_PATH. Either way, the system loader can not find it. We do not distribute NVIDIA libraries.
[This page can be helpful](https://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html#:~:text=On%20Linux%20systems%2C%20this%20loader%20is%20named%20%2Flib%2Fld-linux.so.X,be%20searched%20is%20stored%20in%20the%20file%20%2Fetc%2Fld.so.conf.)

**Comment by hariharans29** [comment] 2021-11-15 18:44
Starting v1.9, ORT's Python GPU package is capable of running on non-GPU machines in addition to machines with GPUs.  Also, in Python there is an "implicit" registration of EPs (i.e.) the CUDA EP is registered by default in the GPU package. So, when the CUDA EP fails to load, this is a taken as the binary trying to run on a non-GPU machine and hence this behavior. Obviously, there is some ambiguity here as the user's intent is not taken into consideration. Does the user expect to be using the CUDA EP and is the CUDA EP failing to load because of missing Nvidia libs (in which case the user might expect that the session just not load successfully) or does the user expect that loading the CUDA EP is going to fail because there are no GPUs and hence the fallback to CPU is acceptable ? 

Starting ORT v1.10, the users are expected to [explicitly register the EPs in Python](https://github.com/microsoft/onnxruntime/pull/9712) they would like to use for their session. Perhaps now, the intent will be clear enough if we see the CUDA EP as part of the provider list to be used for the session (no implicit registration of EPs will ensure that the CUDA EP won't show up in the provider list unless the user provided it). If we see the CUDA EP as part of the provider list AND the CUDA EP fails to load, we could make the session construction error-out (just like the TensorRT and OpenVINO EPs). Does this sound like a good plan ?

**Comment by Fettstorch** [comment] 2021-11-16 09:03
@hariharans29 "_...session construction error-out (just like the TensorRT and OpenVINO EPs)_" - currently the behaviour results in a segfault, wouldn't it be beneficial/an option to soften this by raising an exception on Python-side? That might imply to implement a more robust lazy loading of the EP libs and forwarding an error indicator to the Python binding and I'm not sure if this might feasible.

**Comment by hariharans29** [comment] 2021-11-16 18:16
> @hariharans29 "_...session construction error-out (just like the TensorRT and OpenVINO EPs)_" - currently the behaviour results in a segfault, wouldn't it be beneficial/an option to soften this by raising an exception on Python-side? That might imply to implement a more robust lazy loading of the EP libs and forwarding an error indicator to the Python binding and I'm not sure if this might feasible.

For the TensorRT/OpenVINO enhancement request: tagging @jywu-msft 

For CUDA: @RyanUnderhill is planning to take a look when he has a chance

**Comment by jywu-msft** [comment] 2021-11-16 18:18
other customers are already building TensorRT EP and OpenVINO EP together so it's not clear what issue you are encountering.
which version of onnxruntime are you building. you do need to match onnxruntime version with the tensorrt/openvino version it supports.

**Comment by Fettstorch** [comment] 2021-11-16 19:06
> other customers are already building TensorRT EP and OpenVINO EP together so it's not clear what issue you are encountering. which version of onnxruntime are you building. you do need to match onnxruntime version with the tensorrt/openvino version it supports.

We do the same and highly appreciate the dynamic loading of EP dependencies (introduced in 1.8.0), so that we do not have to compile different ORT flavors. What we are asking for is actually a consistent behavior when certain EP dependcies are not available. As mentioned by @paradigmn, missing CUDA currently resolves in a fallback with a warning message, whereas TensorRT and OpenVINO provider are causing segfaults that cannot be handled in the Python applications. Whereas latter (OpenVINO) is definitely a more user caused issue (often caused by forgetting to activate the OpenVINO environment), TensorRT can have the following implication: building only one ORT now for all our different edge devices (mainly NVIDIA Jetson family, Raspberry PI 4, Coral Dev Board) and deploy it via Docker, TensorRT and CUDA libs are mounted by the NVIDIA Docker runtime (which I think is now directly integrated to Docker). Accordingly, on devices that are lacking GPU, Cuda EP is valid and works (internally falling back to CPU), whereas TensorRT exits with the segfault -> inconsistency?.

**Comment by jywu-msft** [comment] 2021-11-16 22:56
thanks for the valuable feedback. agreed that we shouldn't have segfaults at all in the runtime and we should look into fixing that. +@chilo-ms to look into that for TensorRT.

btw, on the topic of fallback behavior, would fallback behavior for incorrect OpenVINO environment be desirable? How does one distinguish between an inactivated openvino environment vs deployment target that doesn't support OpenVINO devices?
i.e. if we fallback to cpu, the inference would silently succeed vs the desired result of running inference on an Intel VPU?
since we are enforcing explicit provider registrations starting ORT 1.10, if the user specifies they want to use a particular EP, should we treat it as failure/invalid param if it doesn't work?

**Comment by paradigmn** [comment] 2021-11-18 09:17
We tested the behavior for different configurations on a Raspberry Pi 4 with an additional Intel Movidius VPU stick. Depending on the situation, four different outcomes are possible (success, fallback, exception and segfault). The matter of a fallback could be deemed acceptable since `sess.get_providers()` can be used to evaluated if the desired provider was loaded successfully or not. As already stated the segfault behavior should be avoided. It is a bit peculiar that both exceptions and fallbacks can occur in case of a provider error. This should probably be unified (either one or the other).

| Provider List           | Scenario                            | Behavior         | Note                 |
|-------------------------|-------------------------------------|------------------|----------------------|
| CUDA, OpenVINO, CPU     | VPU plugged in, ENV initialized     | Fallback         | CUDA lib warning     |
| TensorRT, OpenVINO, CPU | VPU plugged in, ENV initialized     | Segfault         | TensorRT lib missing |
| OpenVINO, CPU           | VPU not plugged in, ENV initialized | Python Exception | NC_ERROR             |
| OpenVINO, CPU           | VPU plugged in, ENV not initialized | Segfault         | OpenVINO lib missing |

**Comment by jywu-msft** [comment] 2021-11-19 01:09
thanks. @chilo-ms has been investigating and we've identified the source of the segfault behavior. we will update it to be consistent with the CUDA EP behavior.

**Comment by askhade** [comment] 2021-11-29 17:40
Closing this issue now since the PR has been merged.

**Closed by askhade** 2021-11-29 17:40 UTC
Labels: api:Python

**Comment by hariharans29** [comment] 2021-11-29 17:57
I think the issue with the CUDA EP still exists (and that is why the issue was left open). IIRC @RyanUnderhill planned to add some logic in python to error out if the CUDA EP wasn't loaded and the user added it to the provider list.

**Comment by jywu-msft** [comment] 2021-11-29 18:02
> I think the issue with the CUDA EP still exists (and that is why the issue was left open). IIRC @RyanUnderhill planned to add some logic in python to error out if the CUDA EP wasn't loaded and the user added it to the provider list.

the issue was addressed with recent PR's.  
https://github.com/microsoft/onnxruntime/pull/9814  addresses the segfaults reported and adds warning messages
https://github.com/microsoft/onnxruntime/pull/9872  adds additional warning messages to cover all paths.

**Comment by hariharans29** [comment] 2021-11-29 18:08
> > I think the issue with the CUDA EP still exists (and that is why the issue was left open). IIRC @RyanUnderhill planned to add some logic in python to error out if the CUDA EP wasn't loaded and the user added it to the provider list.
> 
> the issue was addressed with recent PR's. #9814 addresses the segfaults reported and adds warning messages #9872 adds additional warning messages to cover all paths.

Thanks , I had seen these PRs. I was still wondering if erroring out (as opposed to emitting a warning and then falling back to CPU) might have been an option considering that the user now needs to explicitly provide the EP of interest in the provider list (making the intent much clearer from from previous releases). But we can address this is the future (if need be).

**Comment by jywu-msft** [comment] 2021-11-29 18:23
> > > I think the issue with the CUDA EP still exists (and that is why the issue was left open). IIRC @RyanUnderhill planned to add some logic in python to error out if the CUDA EP wasn't loaded and the user added it to the provider list.
> > 
> > 
> > the issue was addressed with recent PR's. #9814 addresses the segfaults reported and adds warning messages #9872 adds additional warning messages to cover all paths.
> 
> Thanks , I had seen these PRs. I was still wondering if erroring out (as opposed to emitting a warning and then falling back to CPU) might have been an option considering that the user now needs to explicitly provide the EP of interest in the provider list (making the intent much clearer from from previous releases). But we can address this is the future (if need be).

yes, for now we made OPENVINO and TensorRT consistent with the CUDA behavior.
but what you suggest is something I had been thinking about as well.
instead of warning, we can throw exception rather than warn/fall back. but we also want to make it consistent across all language bindings. do you know what happens for other bindings currently?

**Comment by hariharans29** [comment] 2021-11-29 19:33
> > > > I think the issue with the CUDA EP still exists (and that is why the issue was left open). IIRC @RyanUnderhill planned to add some logic in python to error out if the CUDA EP wasn't loaded and the user added it to the provider list.
> > > 
> > > 
> > > the issue was addressed with recent PR's. #9814 addresses the segfaults reported and adds warning messages #9872 adds additional warning messages to cover all paths.
> > 
> > 
> > Thanks , I had seen these PRs. I was still wondering if erroring out (as opposed to emitting a warning and then falling back to CPU) might have been an option considering that the user now needs to explicitly provide the EP of interest in the provider list (making the intent much clearer from from previous releases). But we can address this is the future (if need be).
> 
> yes, for now we made OPENVINO and TensorRT consistent with the CUDA behavior. but what you suggest is something I had been thinking about as well. instead of warning, we can throw exception rather than warn/fall back. but we also want to make it consistent across all language bindings. do you know what happens for other bindings currently?

That is a good point about keeping it consistent across language bindings. Atleast for the C API, it does look like we throw if we aren't able to load the CUDA EP - https://github.com/microsoft/onnxruntime/blob/6284cbe833bc47eb90ed4082ff2ae015b8e5c004/onnxruntime/core/session/provider_bridge_ort.cc#L1303

**Comment by jywu-msft** [comment] 2021-11-30 20:58
> > > > > I think the issue with the CUDA EP still exists (and that is why the issue was left open). IIRC @RyanUnderhill planned to add some logic in python to error out if the CUDA EP wasn't loaded and the user added it to the provider list.
> > > > 
> > > > 
> > > > the issue was addressed with recent PR's. #9814 addresses the segfaults reported and adds warning messages #9872 adds additional warning messages to cover all paths.
> > > 
> > > 
> > > Thanks , I had seen these PRs. I was still wondering if erroring out (as opposed to emitting a warning and then falling back to CPU) might have been an option considering that the user now needs to explicitly provide the EP of interest in the provider list (making the intent much clearer from from previous releases). But we can address this is the future (if need be).
> > 
> > 
> > yes, for now we made OPENVINO and TensorRT consistent with the CUDA behavior. but what you suggest is something I had been thinking about as well. instead of warning, we can throw exception rather than warn/fall back. but we also want to make it consistent across all language bindings. do you know what happens for other bindings currently?
> 
> That is a good point about keeping it consistent across language bindings. Atleast for the C API, it does look like we throw if we aren't able to load the CUDA EP -
> 
> https://github.com/microsoft/onnxruntime/blob/6284cbe833bc47eb90ed4082ff2ae015b8e5c004/onnxruntime/core/session/provider_bridge_ort.cc#L1303

thanks. will make a note to check other language bindings and behavior for TensorRT and OpenVINO EP's as well.
