### ISSUE TITLE
[Build] onnxruntime v1.15.0 with --enable_memory_profile fails

### ISSUE THREAD

**Issue by barnou-psee** [microsoft/onnxruntime#16190] opened 2023-06-01 09:28 UTC
### Describe the issue

I want to have a build with memory profiling enabled, but the build fails at some point because it looks for the attribute `name` in the structure `OrtDevice` which doesn't exist. 

### Urgency

Not very urgent.

### Target platform

x86

### Build script

./build.sh --config Release --build_shared_lib --use_cache  --parallel 8 --skip_tests --enable_memory_profile --compile_no_warning_as_error

### Error / output

```
.../onnxruntime/onnxruntime/core/framework/execution_frame.cc:424:73: error: ‘const struct OrtDevice’ has no member named ‘name’
  424 |                   static_activation_memory_sizes_in_byte_.find(location.name) ==
      |                                                                         ^~~~
.../onnxruntime/include/onnxruntime/core/common/common.h:174:11: note: in definition of macro ‘ORT_ENFORCE’
  174 |     if (!(condition)) {                                                                  \
      |           ^~~~~~~~~
.../onnxruntime/onnxruntime/core/framework/execution_frame.cc:427:28: error: ‘const struct OrtDevice’ has no member named ‘name’
  427 |                   location.name,
      |                            ^~~~
.../onnxruntime/include/onnxruntime/core/common/common.h:176:75: note: in definition of macro ‘ORT_ENFORCE’
  176 |                                                 ::onnxruntime::MakeString(__VA_ARGS__)); \
      |                                                                           ^~~~~~~~~~~
.../onnxruntime/onnxruntime/core/framework/execution_frame.cc:431:64: error: ‘const struct OrtDevice’ has no member named ‘name’
  431 |               static_activation_memory_sizes_in_byte_[location.name] = peak_size;
```

### GCC / Compiler Version

9.4.0

**Comment by edgchen1** [comment] 2023-06-01 16:21
duplicate of https://github.com/microsoft/onnxruntime/issues/16124.

this should be fixed in main now.

**Closed by edgchen1** 2023-06-01 16:21 UTC
Labels: build
