### ISSUE TITLE
CUDA kernel not found in registries for Op type: CustomOpOne

### ISSUE THREAD

**Issue by CoderHam** [microsoft/onnxruntime#6388] opened 2021-01-20 05:17 UTC
**Describe the bug**
CUDA kernel not found in registries for Op type: CustomOpOne
CUDA kernel not found in registries for Op type: CustomOpTwo

**Urgency**
Blocking support for custom op models ([Tritonserver](https://github.com/triton-inference-server/server))

**System information**
OS Platform and Distribution: Linux Ubuntu 20.04
ONNX Runtime installed from (source or binary): source
ONNX Runtime version: 1.6.0 (Works fine in 1.5.3)
Python version: 3.8.7
CUDA/cuDNN version: 11.1 / 8.0.5
GPU model and memory: NVIDIA TITAN V (12G)

**To Reproduce**
- Copy libcustom_op_library.so and custom_op_model.onnx built [here](https://github.com/microsoft/onnxruntime/tree/v1.6.0/onnxruntime/test/testdata/custom_op_library)
- Run the model. 

**Expected behavior**
- The log will slow the following. When unloading the model/exiting the program you will see a segfault. 
```
2021-01-20 04:50:33.052875467 [W:onnxruntime:log, cuda_execution_provider.cc:1885 GetCapability] CUDA kernel not found in registries for Op type: CustomOpOne node name: 
2021-01-20 04:50:33.052881055 [W:onnxruntime:log, cuda_execution_provider.cc:1885 GetCapability] CUDA kernel not found in registries for Op type: CustomOpTwo node name: 
```

**Screenshots**
![image](https://user-images.githubusercontent.com/11223643/105130309-a0415900-5a9b-11eb-9914-bcc204c1d65c.png)

**Comment by pranavsharma** [comment] 2021-01-20 22:38
It doesn't look like you've implemented GetExecutionProviderType() in your custom op. If you don't implement it, the default is CPU. See this as an example: https://github.com/microsoft/onnxruntime/blob/d761571afcbc50be94b2ffdfcaa09cfd9e2eaf5e/onnxruntime/test/shared_lib/test_inference.cc#L271.

**Comment by pranavsharma** [comment] 2021-01-21 09:17
So, the warning regarding cuda kernels not found in registries is expected since no execution provider was provided and it defaulted to CPU. As for the segfault, at what point are you dlclosing libcustom_op_library.so? If you're calling dlclose() before the session is destructed, you'll get a segfault with stack trace like below. As stated in the [documentation](https://github.com/microsoft/onnxruntime/blob/d42399e1b07ce61e95aae88bc6b6ea5dcaae2011/include/onnxruntime/core/session/onnxruntime_c_api.h#L421) you should call it after session destruction.
```
Thread 1 "t-ort" received signal SIGSEGV, Segmentation fault.
0x00007fffee3815d6 in onnxruntime::CustomOpKernel::~CustomOpKernel (this=0x41609e0, __in_chrg=<optimized out>)
    at /bert_ort/pranav/onnxruntime/onnxruntime/core/session/custom_ops.cc:82
82        ~CustomOpKernel() override { op_.KernelDestroy(op_kernel_); }
(gdb) bt
#0  0x00007fffee3815d6 in onnxruntime::CustomOpKernel::~CustomOpKernel (this=0x41609e0, __in_chrg=<optimized out>)
    at /bert_ort/pranav/onnxruntime/onnxruntime/core/session/custom_ops.cc:82
#1  0x00007fffee381628 in onnxruntime::CustomOpKernel::~CustomOpKernel (this=0x41609e0, __in_chrg=<optimized out>)
    at /bert_ort/pranav/onnxruntime/onnxruntime/core/session/custom_ops.cc:82
#2  0x00007fffee3acde5 in onnxruntime::SessionState::~SessionState (this=0x3fcc090, __in_chrg=<optimized out>)
    at /bert_ort/pranav/onnxruntime/onnxruntime/core/framework/session_state.h:98
#3  0x00007fffee3d0de4 in std::default_delete<onnxruntime::SessionState>::operator() (this=0xd226a0, __ptr=0x3fcc090) at /usr/include/c++/5/bits/unique_ptr.h:76
#4  0x00007fffee3c775b in std::unique_ptr<onnxruntime::SessionState, std::default_delete<onnxruntime::SessionState> >::~unique_ptr (this=0xd226a0,
    __in_chrg=<optimized out>) at /usr/include/c++/5/bits/unique_ptr.h:236
#5  0x00007fffee3b6606 in onnxruntime::InferenceSession::~InferenceSession (this=0xd22090, __in_chrg=<optimized out>)
    at /bert_ort/pranav/onnxruntime/onnxruntime/core/session/inference_session.cc:354
#6  0x00007fffee3b6840 in onnxruntime::InferenceSession::~InferenceSession (this=0xd22090, __in_chrg=<optimized out>)
    at /bert_ort/pranav/onnxruntime/onnxruntime/core/session/inference_session.cc:378
#7  0x00007fffee3498dc in OrtApis::ReleaseSession (value=0xd22090) at /bert_ort/pranav/onnxruntime/onnxruntime/core/session/onnxruntime_c_api.cc:2103
#8  0x0000000000401f58 in Ort::OrtRelease(OrtSession*) ()
#9  0x000000000040285d in Ort::Base<OrtSession>::~Base() ()
#10 0x00000000004027ba in Ort::Session::~Session() ()
#11 0x0000000000401bee in main ()
```

**Comment by CoderHam** [comment] 2021-01-21 21:48
@pranavsharma in 1.5.3 we did not need to dlclose the library handle. Thanks for helping me understand that it is needed. I have a follow up question: If I am loading multiple instances of the model that uses a custom op does the dlclose need to be done after ALL instances of the model have been unloaded?

**Comment by pranavsharma** [comment] 2021-01-21 22:13
You don't *have* to dlcose the custom op library handle. But if you choose to do so, you should do it after all sessions (that are using this custom op) have been destructed. This behavior has not changed between release 1.5.3 and today.

**Comment by deadeyegoodwin** [comment] 2021-01-23 01:07
We believe the problem is related to general issues with dlopen/dlclose and C++ apps that we have seen before. We have an fix implemented and just waiting for final testing to complete.

**Comment by pranavsharma** [comment] 2021-01-25 19:47
Closing as per comment above. Please re-open if needed.

**Closed by pranavsharma** 2021-01-25 19:47 UTC
Labels: ep:CUDA, feature:custom ops
