### ISSUE TITLE
CUDA kernel not found in registries for Op type: ScatterND

### ISSUE THREAD

**Issue by polar99** [microsoft/onnxruntime#6300] opened 2021-01-11 06:24 UTC
**Describe the bug**
CUDA kernel not found in registries for Op type: ScatterND

**System information**
- OS Platform and Distribution: Linux Ubuntu 20.04
- ONNX Runtime installed from (source or binary): pip install onnxruntime-gpu
- ONNX Runtime version: 1.6.0
- Python version: 3.8.7
- CUDA/cuDNN version: 10.2 / 8
- GPU model and memory: NVIDIA Tesla T4 (16G)

**To Reproduce**
- Describe steps/code to reproduce the behavior.
```
import onnxruntime

onnx_path = './yolov5s.onnx'
onnxruntime.InferenceSession(onnx_path, providers=['CUDAExecutionProvider'])
```
[code](https://github.com/polar99/onnxruntime-gpu-test/blob/main/exp_yolov5.py)

- Attach the ONNX model to the issue (where applicable) to expedite investigation.
ONNX file [yolov5s.zip](https://github.com/polar99/onnxruntime-gpu-test/blob/main/yolov5s.zip)

**Expected behavior**
CUDA kernel not found in registries for Op type: ScatterND node name: ScatterND_995

**Screenshots**
![image](https://user-images.githubusercontent.com/23132594/104151404-e9e4d080-5417-11eb-8f25-c63ddb5ddff1.png)

**Comment by hariharans29** [comment] 2021-01-11 07:01
Dupe of https://github.com/microsoft/onnxruntime/issues/5958
Fixed by https://github.com/microsoft/onnxruntime/pull/6184

Will be available in the next release

**Closed by hariharans29** 2021-01-11 07:01 UTC

**Comment by polar99** [comment] 2021-01-11 07:07
Thanks! Hope soon!

**Comment by polar99** [comment] 2021-01-13 06:09
@hariharans29  I have built onnxruntime from master with CUDA11.0 cudnn8 (cuda-devel) . I found that onnxruntime-gpu works well on  cuda-devel environment,  but it failed on cuda-runtime when running onnxruntime.InferenceSession() with yolov5 model.
The [code](https://github.com/polar99/onnxruntime-gpu-test/blob/main/exp_yolov5.py) 
The onnxfile [yolov5s.zip](https://github.com/polar99/onnxruntime-gpu-test/blob/main/yolov5s.zip) 

(1)**cuda-devel** environment:     docker pull nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04
The onnxruntime is built from master on this environment.
When running
 `python exp_yolov5.py`
onnxruntime works well.
 
(2)**cuda-runtime** environment: docker pull nvidia/cuda:11.0-cudnn8-runtime-ubuntu18.04
The onnxruntime is built from master on cuda-devel environment.
When running
 `python exp_yolov5.py`
onnxruntime will cause fatal error.
**Segmentation fault (core dumped)**

The following is my building cmd:
`./build.sh --build_shared  --parallel  --use_cuda --enable_pybind --build_wheel  --config Release  --cudnn_home /usr/lib/x86_64-linux-gnu/ --cuda_home /usr/local/cuda  --cmake_extra_defines PYTHON_LIBRARIES=/usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 PYTHON_EXECUTABLE=/usr/local/bin/python3.8 PYTHON_INCLUDE_DIRS=/usr/local/include/python3.8`

**Comment by hariharans29** [comment] 2021-01-13 06:30
Hi @polar99 ,

This doesn't seem to be related to this specific issue of ScatterND support on CUDA EP. Someone in #5958 already confirmed that yolov5 seems to use ScatterND CUDA kernel after building master.

Please open a separate issue for this `cuda-devel` vs `cuda-runtime` problem you are facing and we would have to triage and look into it. Possibly running it through `gdb` and providing more debug info will help the investigator.

Thanks.

**Comment by polar99** [comment] 2021-01-13 08:01
Thanks!
I have opened a new issue for this problem in [issues/6339](https://github.com/microsoft/onnxruntime/issues/6339).
