### ISSUE TITLE
[release:1.14] Split(18) is not covered everywhere inside ORT

### ISSUE THREAD

**Issue by xiaowuhu** [microsoft/onnxruntime#14523] opened 2023-02-01 09:20 UTC
### Describe the feature request

Due to Split(18) signature changed, some references of this operator didn't add 'num_outputs' as input.

### Describe scenario use case

Although Split(18) not in particular ONNX model, but the optimizers may use it inside ort code.
So does ReduceMean(18) and other Op(18).

**Comment by pranavsharma** [comment] 2023-02-01 18:02
@liqunfu can you please check?

**Comment by liqunfu** [comment] 2023-02-01 21:46
https://github.com/microsoft/onnxruntime/pull/14015

**Comment by faxu** [comment] 2023-02-02 21:39
#14015 should already be in the release candidate build that was tested. @xiaowuhu, please follow up with @liqunfu on repro steps

**Comment by borg323** [comment] 2023-02-03 01:00
I just tried the release candidate and the DirectML execution provider with a model that uses several split operators, and found out that he ones with `num_outputs=2` were placed on the CPU. I assume it is related to this issue as this was the only change for opset 18.

**Comment by pranavsharma** [comment] 2023-02-03 21:58
This is not a bug or a regression introduced in 1.14.0. Let us know if there's a failure. In the absence of that it might just be a missed optimization opportunity.

**Comment by borg323** [comment] 2023-02-03 22:45
To me it looks like a regression as it is working fine with 1.13.1 and 1.14.0 with opset 17 (all nodes were placed on the DirectML execution provider), but not in 1.14.0, with opset 18. I modified the model to remove all splits with `num_outputs` and it still happens with the single remaining one. I can open a separate issue for this if you want.

**Comment by pranavsharma** [comment] 2023-02-03 22:49
@borg323 The original issue lacked any repro. Can you attach the model and repro? Let's just track it here.

**Comment by borg323** [comment] 2023-02-03 23:21
Here are two versions of the same model, after removing the splits that would require `num_outputs` with opset 18 and cutting out several layers to bring the size down. They are exactly identical, just one is for opset 17 and the other for opset 18. With the opset 17 one I get no warnings, with the opset 18 one I get:
```
2023-02-04 00:54:27.2877303 [W:onnxruntime:, session_state.cc:1136 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-02-04 00:54:27.2916389 [W:onnxruntime:, session_state.cc:1138 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
``` 
Is there anything else you need?

[models.zip](https://github.com/microsoft/onnxruntime/files/10583487/models.zip)

**Comment by fdwr** [comment] 2023-02-04 00:05
@borg323 / @xiaowuhu : The DML EP currently support opsets 1-15 (see [operator kernels list](https://github.com/microsoft/onnxruntime/blob/main/docs/OperatorKernels.md#dmlexecutionprovider)). Technically the EP has very partial 16 support (for operators whose signature didn't change functionally and just added additional data types) and the DFT-17 op, but officially opset 15 is the last supported opset. Because DirectML.dll is a separate component on its own schedule (and is also an operating system component), it has a longer lead time than ORT's regular quarterly cadence. It's on the roadmap though... (FYI @martinb35 for future feature requests)

**Comment by borg323** [comment] 2023-02-04 00:28
So you mean it is a missed optimization, failing to detect that Split is not using `num_outputs` and is thus compatible with the previous version?

**Comment by pranavsharma** [comment] 2023-02-04 00:39
If you're not using any ops that require opset 18, don't stamp your model with opset 18.

**Comment by borg323** [comment] 2023-02-04 01:02
I wanted to use `Mish`, which is why I tried opset 18, but I removed it from the models I showed to make them identical. This is not critical for us, we can keep using our opset 17 version with DML EP for now.

**Comment by RyanUnderhill** [comment] 2023-02-04 01:20
Sounds like we should give a better warning here:
"Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf."

We should be able to detect the latest opset that the preferred providers supports, and say exactly that in the output, like:

(in addition to the above):
"The provider DML supports up to opset 17, but the model is using opset 18."

@borg323 would this have helped your case? (It's still an issue that it doesn't support opset 18, but at least you'd know why)

**Comment by borg323** [comment] 2023-02-04 01:35
Sure, that would have been clearer, but since this is not a regression I'm happy with it staying as is for the release.

**Closed** 2023-02-09 05:57 UTC
Labels: feature request, release:1.14
