### ISSUE TITLE
Segmentation fault with zero-batch intermediate tensor

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#1879] opened 2019-09-19 23:01 UTC
**Describe the bug**
When the first stage network creates zero batch tensor, I get segmentation fault.

**Urgency**
This is necessary to handle the case when the first stage (detection) finds no results

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 1604
- ONNX Runtime installed from (source or binary): master
- ONNX Runtime version: 0.5.0 (master)
- Python version: 3.6
- GCC/Compiler version (if compiling from source): 5.4.0

**To Reproduce**
Run with an input that generates zero batch intermediate tensor

**Expected behavior**
No segmentation fault

**Additional context**
I will send the generated onnx file to repro. This is against master because I want to see verbose logs.

**Comment by dashesy** [comment] 2019-09-19 23:19
This is also reproduced in ORT 0.5.0 release)

**Comment by ybrnathan** [comment] 2019-09-19 23:48
So, is the expected result to fail the session.run() without seg fault, or you actually expect the session.run() to be successful?

**Comment by dashesy** [comment] 2019-09-20 00:19
It should succeed, and that output should have zero size

**Comment by hariharans29** [comment] 2019-09-30 18:28
Thanks @dashey for the explanation in #1909.

Since @dashesy notes that issue it is a duplicate of this issue, and that issue has been resolved with explanation, closing this out.

**Comment by dashesy** [comment] 2019-09-30 18:36
@hariharans29 please re-open. I closed that issue because this one was open.

**Comment by hariharans29** [comment] 2019-09-30 19:06
Chatted offline with @dashey. Apparently, there is a node in the model that segfaults even after setting max_output_boxes = 0 in NMS (valid input). The other issue was with max_output_boxes = -1 in NMS (probably not valid input - spec in unclear)

**Closed** 2019-10-25 19:39 UTC
Labels: bug
