### ISSUE TITLE
Providing fewer tensor inputs to Java API than model declares as inputs

### ISSUE THREAD

**Issue by danielphil** [microsoft/onnxruntime#2878] opened 2020-01-21 15:15 UTC
If an ONNX model declares 10 inputs, is it valid to provide 9 instead?

I've been using the Java API and found that `OrtSession.run()` will accept fewer inputs in the input map than the model requires. This results in a crash in `Java_ai_onnxruntime_OrtSession_run()` (see `java/src/main/native/ai_onnxruntime_OrtSession.c`) when building the `inputNames` array because the `for` loop uses the number of inputs declared by the model as the limit for the loop instead of the number of elements in `inputNamesArr`.

**Comment by Craigacp** [comment] 2020-01-21 19:01
Ooops. Line 213 in `OrtSession.java` should use `inputNamesArray.length` and `outputNamesArray.length` rather than `numInputs` and `numOutputs`. I'll make up a PR.

**Comment by Craigacp** [comment] 2020-01-21 19:03
I believe it is valid if you supply all the inputs required by the requested outputs, and that's the way the Java code is supposed to work (though the Java code can only validate that all the required inputs are supplied by calling the run method in the native code). I would appreciate someone more familiar with the ONNX spec confirming that though.

**Comment by danielphil** [comment] 2020-01-21 21:47
Thanks for clarifying. 🙂 I was assuming that I'd need to provide all the inputs the model declares, but I forgot an input and got the crashing bug. I wanted to check this was the intended behavior though before I changed anything. Let me know if I can help out by creating a PR to fix.

**Comment by Craigacp** [comment] 2020-01-24 02:24
I have a patch for this, but I won't have time to write a unit test for it until next week which I'd like to do before making the PR. It's a one line fix you can see [here](https://github.com/Craigacp/onnxruntime/commit/ab31bcafbc9f20aa342f8dfaa4ee8c9bd66fd99e).

**Comment by Craigacp** [comment] 2020-02-03 15:49
@snnn after writing a unit test, it seems like onnx-runtime throws an error if I don't supply all the inputs even when they are not used by the requested outputs. I have a simple graph which accepts scalars a,b,c, and computes ab, bc, and ab + bc as separate outputs. When asking for the ab output I get an exception thrown out of the native runtime with the text:
```
2020-02-03 10:31:07.363937739 [E:onnxruntime:, sequential_executor.cc:183 Execute] Non-zero status code returned while running Mul node. Name:'bc' Status Message: /local/ExternalRepositories/onnxruntime/include/onnxruntime/core/framework/op_kernel.h:90 const T* onnxruntime::OpKernelContext::Input(int) const [with T = onnxruntime::Tensor] Missing Input: c:0
```
plus a stack trace. The test fails in Java on this [line](https://github.com/Craigacp/onnxruntime/blob/2b66aeb350f93487ab88c9d8ef35e28d693d2688/java/src/test/java/ai/onnxruntime/InferenceTest.java#L237). The model is checked in [here](https://github.com/Craigacp/onnxruntime/blob/java-num-inputs-fix/onnxruntime/test/testdata/partial-inputs-test.onnx). I built it using TF 1.15 and tf2onnx 1.5.4.

I wouldn't have expected it to work this way, is this a bug in the library, or did I misunderstand the spec? I can't see a specific test in either the C# or Python bindings which check this behaviour.

**Comment by mina-asham** [comment] 2020-02-12 15:38
@Craigacp did you also test if an input is completely unused? (e.g. inputs: a, b output: c = a, i.e. b is unused)

**Comment by Craigacp** [comment] 2020-02-12 16:26
@mina-asham, that works. I made a smaller version of my test that accepts a,b,c and only outputs ab. There supplying c or not is irrelevant to the output. It's on the same branch.

**Comment by Craigacp** [comment] 2020-02-13 15:27
A little more investigation (i.e. turning on the execution plan printing) shows that it doesn't change the execution plan based upon the outputs requested as I thought.
```Execution Plan:
[0] Mul (ab)
[1] Identity (ab_graph_outputs_Identity__4)
[2] Mul (bc)
[3] Add (abc)
Free ml-values: (5) ab_raw_output___3:0
[4] Identity (abc_graph_outputs_Identity__8)
Free ml-values: (6) abc_raw_output___7:0
[5] Identity (bc_graph_outputs_Identity__6)
Free ml-values: (3) bc_raw_output___5:0
```
It always uses the above execution plan no matter what outputs are requested, hence the failure. I can easily change the Java API to ensure all the inputs are required, but this still feels like an issue in the native library, as I would expect it to not do unnecessary potentially expensive computation.

**Comment by mina-asham** [comment] 2020-02-13 21:02
> A little more investigation (i.e. turning on the execution plan printing) shows that it doesn't change the execution plan based upon the outputs requested as I thought.
> 
> ```
> [0] Mul (ab)
> [1] Identity (ab_graph_outputs_Identity__4)
> [2] Mul (bc)
> [3] Add (abc)
> Free ml-values: (5) ab_raw_output___3:0
> [4] Identity (abc_graph_outputs_Identity__8)
> Free ml-values: (6) abc_raw_output___7:0
> [5] Identity (bc_graph_outputs_Identity__6)
> Free ml-values: (3) bc_raw_output___5:0
> ```
> 
> It always uses the above execution plan no matter what outputs are requested, hence the failure. I can easily change the Java API to ensure all the inputs are required, but this still feels like an issue in the native library, as I would expect it to not do unnecessary potentially expensive computation.

Thanks for the detailed analysis, that explains it, I think we can split this into two bits:
* There is a bug in the Java code (the one you fixed on your branch), and that bug affects models with "unconnected" inputs (i.e. completely non-required inputs)
* There is a potential bug in the native code where the request outputs are only used post evaluation to select specific outputs rather than limit the graph from the beginning

I think this issue was opened for the first point, I would suggest we submit that fix and open another issue for the native code that links to this one. Does that sound okay?

**Comment by Craigacp** [comment] 2020-02-13 21:19
Well it depends if the native library is working as intended or not. If it's not then the code I have is correct and when the native library is fixed everything will work. If it is working as intended then I think the Java API should check that all inputs are present before calling the native code.

**Comment by Craigacp** [comment] 2020-02-21 17:05
I've made a PR for the Java fix, I agree we should open another issue for the native library behaviour.

**Closed** 2020-02-21 21:13 UTC
Labels: bug
