### ISSUE TITLE
 Non-zero status code returned while running ScatterND node. Name:'ScatterND@1' Status Message: updates tensor should have shape equal to indices.shape[:-1] + data.shape[indices.shape[-1]:]. updates shape: {1}, indices shape: {1}, data shape: {3}

### ISSUE THREAD

**Issue by yongxin3344520** [microsoft/onnxruntime#7038] opened 2021-03-17 03:38 UTC
sequential_executor.cc:339 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running ScatterND node. Name:'ScatterND@1' Status Message: updates tensor should have shape equal to indices.shape[:-1] + data.shape[indices.shape[-1]:]. updates shape: {1}, indices shape: {1}, data shape: {3}

plat：win10  ， cuda11.0， java  
 After careful investigation, it was caused by  “paddle. lstm”  on 1.7.0 , 
but No problem on 1.6.0

**Comment by snnn** [comment] 2021-03-18 23:46
Excuse me, how to reproduce this bug? Do you think it is a bug for the ScatterND kernel?

**Comment by znsoftm** [comment] 2021-03-20 01:44
it's happening when referencing PaddlOCR recognition model which is a converted model from PaddlePaddle.

You can download or test it from the github repo:  https://github.com/znsoftm/RapidOCR

**Comment by yongxin3344520** [comment] 2021-03-25 08:03
> Excuse me, how to reproduce this bug? Do you think it is a bug for the ScatterND kernel?


Eh......... ,   I  think  it is onnxruntime's bug .  
Because,  have much bug  like  'Non-zero status code returned while running Reshape node. Name:'Reshape_502' , I do not know how to solve 。

**Comment by yongxin3344520** [comment] 2021-03-25 08:09
> it's happening when referencing PaddlOCR recognition model which is a converted model from PaddlePaddle.
> 
> You can download or test it from the github repo: https://github.com/znsoftm/RapidOCR


I use pytorch rewrite  discern model of  PaddleOcr , it can run on onnxruntime 。
But new bug happen ， like  ' Non-zero status code returned while running Reshape node. Name:Reshape_502  ' or 
' Non-zero status code returned while running Add node.  ' 

Use pytorch and export onnx :
=================
code:   y[:, :, ::2, ::2] = x
error:  Non-zero status code returned while running Reshape node. Name:Reshape_502

=================
code :   in4 + F.upsample(in5, scale_factor=2, mode="nearest")
error  :  Non-zero status code returned while running Add node.

**Comment by znsoftm** [comment] 2021-03-27 00:30
Please look back to our github, yes , it's RapidOCR, we  released a version of new Paddle2Onnx ( from original author)

**Comment by znsoftm** [comment] 2021-03-27 00:31
It's only a bug of Paddle2Onnx. Please add me into you wechat, 364479

**Comment by snnn** [comment] 2021-03-27 03:39
I'll close it because it is more likely a converter bug. If @znsoftm were wrong, please reopen.

**Closed by snnn** 2021-03-27 03:39 UTC
Labels: component:coreruntime, status:more-info-needed

**Comment by yongxin3344520** [comment] 2021-03-30 08:33
> I'll close it because it is more likely a converter bug. If @znsoftm were wrong, please reopen.

Ok , Thank you!

**Comment by yongxin3344520** [comment] 2021-03-30 08:34
> Please look back to our github, yes , it's RapidOCR, we released a version of new Paddle2Onnx ( from original author)

Ok , Thank you !

**Comment by Liujingxiu23** [comment] 2021-09-09 04:24
@yongxin3344520  How did you solve the problem?
I meet similar problem when convert torch model to onnx.
my key code :  c = c[:, :-1]
