### ISSUE TITLE
SliceElimination transformer causes shape inference error

### ISSUE THREAD

**Issue by lucienwang1009** [Microsoft/onnxruntime#885] opened 2019-04-23 08:25 UTC
**Describe the bug**

I'd like to test some object detection model on the latest runtime when it runs into a shape inference exception with the message:
`RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : [TypeInferenceError] Graph attribute inferencing failed: [ShapeInferenceError] Incompatible dimensions`.
If I change back to runtime 0.3.0, everything will be fine.

You can find the model here: [model](https://www.dropbox.com/s/sfdwnd6zyq52hf2/faster_rcnn_resnet50_coco.onnx?dl=0). It's a part of Faster-RCNN model.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- ONNX Runtime installed from (source or binary): source or from https://test.pypi.org/project/ort-nightly/
- ONNX Runtime version: 0.3.1
- Python version: 3.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
Describe steps/code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by snnn** [comment] 2019-04-23 15:52
For any shape inference error, it's either a converter bug, or an ONNX bug. It's unlikely caused by onnxruntime code (unless the TypeInferenceError was thrown from a custom op node)

Do you know which op caused this error?

**Comment by RyanUnderhill** [comment] 2019-04-24 00:55
The issue doesn't look like it's an Onnx issue. The inference error was in a 'Div' op (which is confusing since there is no 'Div' in the graph). When I disable the graph transform 'EliminateSlice' it works without error.

Adding Ashwini since she knows about transforms and helped me to narrow it down.

**Comment by askhade** [comment] 2019-04-24 01:06
Konstantinos is already looking into this

**Comment by askhade** [comment] 2019-04-24 01:19
@lucienwang1009 you can turn off the transformers by setting the level to 0. Which API are you using?
CAPI:     OrtSetSessionGraphOptimizationLevel(session_options, 0);
c# api:  options.SetSessionGraphOptimizationLevel(0);
python: options.set_graph_optimization_level(0)

**Comment by kkaranasos** [comment] 2019-04-25 15:39
From an initial investigation, Slice Elimination is indeed causing the problem. As @askhade says, you can bypass this by setting the optimization level to 0.
Interestingly, the problem is not caused by the "visible" Slice in the top-level graph (this cannot be eliminated actually), but by a Slice that appears in a 74-node sub-graph (if I disable elimination in the subgraphs, it works). I will debug it later today.

**Comment by kkaranasos** [comment] 2019-04-26 18:27
PR https://github.com/Microsoft/onnxruntime/pull/918 fixes the issue.

**Comment by kkaranasos** [comment] 2019-04-27 04:06
Issue fixed with #918.

**Closed by kkaranasos** 2019-04-27 04:06 UTC
Labels: bug
