### ISSUE TITLE
[dynamo][float16] Type (seq(tensor(float16))) of output arg ... does not match expected type (seq(tensor(float))).

### ISSUE THREAD

**Issue by BowenBao** [microsoft/onnxruntime#18481] opened 2023-11-17 00:13 UTC
```
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Type Error: Type (seq(tensor(float16))) of output arg (_val_2) of node () does not match expected type (seq(tensor(float))).
```

Repro:

```python
model_text = '''
<
   ir_version: 8,
   opset_import: ["pkg.onnxscript.torch_lib" : 1, "" : 18, "pkg.onnxscript.torch_lib.common" : 1],
   producer_name: "pytorch",
   producer_version: "2.2.0"
>
main_graph (float16[3,4] l_x_) => (float16[1,4] getitem, float16[2,4] getitem_1)
   <float16[1,4] getitem, float16[2,4] getitem_1, float16[3,4] l_x_, float16[1,4] getitem, float16[2,4] getitem_1, int64[2] _val_1, seq(float16[unk__0,4]) _val_2, int64 _val_3, int64 _val_5>
{
   _val_1 = Constant <value: tensor = int64[2] {1,2}> ()
   _val_2 = pkg.onnxscript.torch_lib.aten_split_with_sizes <dim: int = 0> (l_x_, _val_1)
   _val_3 = Constant <value: tensor = int64 {0}> ()
   getitem = pkg.onnxscript.torch_lib.aten_getitem (_val_2, _val_3)
   _val_5 = Constant <value: tensor = int64 {1}> ()
   getitem_1 = pkg.onnxscript.torch_lib.aten_getitem (_val_2, _val_5)
}
<
  domain: "pkg.onnxscript.torch_lib",
  opset_import: ["" : 18]
>
aten_split_with_sizes (self, split_sizes) => (return_val)
{
   return_val = SplitToSequence <axis: int = @dim> (self, split_sizes)
}
<
  domain: "pkg.onnxscript.torch_lib",
  opset_import: ["" : 18]
>
aten_getitem (self, i) => (return_val)
{
   return_val = SequenceAt (self, i)
}
<
  domain: "pkg.onnxscript.torch_lib.common",
  opset_import: ["" : 18]
>
Rank (input) => (return_val)
{
   tmp = Shape (input)
   return_val = Size (tmp)
}
<
  domain: "pkg.onnxscript.torch_lib.common",
  opset_import: ["" : 18]
>
IsScalar (input) => (return_val)
{
   tmp = Shape (input)
   tmp_0 = Size (tmp)
   tmp_1 = Constant <value_int: int = 0> ()
   return_val = Equal (tmp_0, tmp_1)
}
'''

import onnx
import onnxruntime
import numpy

model_proto = onnx.parser.parse_model(model_text)

x = numpy.random.randn(3, 4).astype(numpy.float16)

sess = onnxruntime.InferenceSession(model_proto.SerializeToString(), providers=["CUDAExecutionProvider"])
sess.run(None, {sess.get_inputs()[0].name: x})
```

From https://github.com/microsoft/onnx-converters-private/issues/196

        jx_nest_base
        DebertaForQuestionAnswering
        coat_lite_mini
        botnet26t_256
        shufflenet_v2_x1_0
        gmixer_24_224
        AlbertForQuestionAnswering
        DistilBertForQuestionAnswering
        DebertaForMaskedLM
        DistillGPT2
        RobertaForQuestionAnswering
        ElectraForQuestionAnswering
        ... 1 more lines
        mixnet_l
        eca_botnext26ts_256
        sam
        MobileBertForQuestionAnswering
        BertForQuestionAnswering
        eca_halonext26ts
        levit_128
        GPT2ForSequenceClassification
        DebertaV2ForQuestionAnswering
        gmlp_s16_224
        cspdarknet53
        MegatronBertForQuestionAnswering

**Comment by yuslepukhin** [comment] 2023-11-21 22:53
This issue is due to `insert_cast_transformer` inability to deal with anything but tensor input and outputs. 

In particular, it is confused by the fact that the input is a `tensor(float16)` and the output is a sequence. Thus, it fails to replace the output `seq(tensor(float16))` to `seq(tensor(float))`. Then the ORT errors out due to the type mismatch. Had we fixed this, we would have make `Cast` support casting sequences.

The root cause for this model, is that `SplitToSequence` is just about the only sequence operation that does not support `tensor(float16)`. The other two nodes ``SequenceAt` support it. Thus, adding a `tensor(float16)` support for `SplitToSequence` would be a natural fix for this.

**Comment by yuslepukhin** [comment] 2023-11-22 19:04
How important to support this kind of model? Do we have/foresee a use case for it?

**Comment by pranavsharma** [comment] 2023-11-22 19:05
Is this a 1P or one of the models we're tracking for dynamo support? If it's a random model I would stay away from adding one more type.

**Comment by BowenBao** [comment] 2023-11-22 19:09
The list of affected model is listed above. We can(will) take care of the pattern in the aot optimizer, however before we integrate the optimizer into the exporter, we will see this break.

Maybe adding fp16 cuda impl for SplitToSequence is less concerning regarding binary size increase? CUDA should be the main usecase here.

**Closed** 2023-12-12 06:10 UTC
Labels: converter:dynamo
