### ISSUE TITLE
[quantization] Output is 'None' again after converting onnx float32 model through quantize_static to int8.

### ISSUE THREAD

**Issue by vonJJ** [microsoft/onnxruntime#15093] opened 2023-03-17 02:51 UTC
### Describe the issue

Similar to the issue I have raised last month (https://github.com/microsoft/onnxruntime/issues/14501), but this time the onnxruntime version I used was the one given after that issue (e2190ec85c45dc36162751fa0d4f6dfaeb260da9, build from source), and the model is a new one.

### To reproduce

import onnxruntime as ort
import numpy as np
import tensorflow as tf

model_path = 'static_quant.onnx'

ort_session = ort.InferenceSession(model_path)
input_feature_name_1 = ort_session.get_inputs()[0].name
input_feature_name_2 = ort_session.get_inputs()[1].name
feature1 = np.random.rand(1, 22, 29, 36).astype(np.float32)
feature2 = np.random.rand(1, 7).astype(np.float32)
feed_dict = {input_feature_name_1: feature1.astype(np.float32), input_feature_name_2: feature2.astype(np.float32)}
result_prob = ort_session.run(None, input_feed=feed_dict)
print(result_prob)

# then you can see output[2] is None

### Urgency

To be solved within 2 days better.

### Platform

Linux

### OS Version

gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

e2190ec85c45dc36162751fa0d4f6dfaeb260da9

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

### Execution Provider Library Version

Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz

### Model File

[models.zip](https://github.com/microsoft/onnxruntime/files/10997358/models.zip)

### Is this a quantized model?

Yes

**Comment by skottmckay** [comment] 2023-03-17 07:05
`result_prob = ort_session.run([], input_feed=feed_dict)` looks like it's asking for none of the outputs as you're providing an empty list of output names.

`result_prob = ort_session.run(None, input_feed=feed_dict)` is the usual way to let it return them all.

**Comment by vonJJ** [comment] 2023-03-17 08:09
> `result_prob = ort_session.run([], input_feed=feed_dict)` looks like it's asking for none of the outputs as you're providing an empty list of output names.
> 
> `result_prob = ort_session.run(None, input_feed=feed_dict)` is the usual way to let it return them all.

Yes, but it doesn't work as well when I use in the second format.

**Comment by jchen351** [comment] 2023-03-24 20:53
Hi @vonJJ 
I got following result when I run your code 
```
[array([[ 0.12247294,  0.08243371,  0.11305195, ..., -0.06359172,
         0.2261039 , -0.03061824]], dtype=float32), array([[0.24188054, 0.3047695 , 0.25155577, 0.42329094, 0.41119692,
        0.3555644 , 0.33621395, 0.34588918, 0.3120259 , 0.26123098,
        0.36523962, 0.3531456 , 0.32895753, 0.35072678, 0.3676584 ,
        0.3047695 , 0.3047695 , 0.2709062 , 0.32895753, 0.17415398,
        0.29025665, 0.24671815, 0.32411993, 0.39426526, 0.2757438 ,
        0.32411993, 0.273325  , 0.3144447 , 0.29509425, 0.3168635 ,
        0.33137634, 0.3217011 , 0.3096071 , 0.3265387 , 0.24188054,
        0.34105155, 0.21769248, 0.33621395, 0.29751307, 0.39184648,
        0.34588918, 0.37007722, 0.40635931, 0.25397456, 0.32895753,
        0.33621395, 0.3096071 , 0.1789916 , 0.32411993, 0.3047695 ,
        0.2636498 , 0.4450602 , 0.3579832 , 0.29267547, 0.23704293,
        0.38459006, 0.45957303, 0.29025665, 0.33863276, 0.24429934,
        0.43296617, 0.36523962, 0.37491482, 0.41361573, 0.3144447 ,
        0.46199182, 0.37975246, 0.24913695, 0.2709062 , 0.3555644 ,
        0.28783783, 0.3676584 , 0.37733364, 0.39426526, 0.37975246,
        0.2684874 , 0.4547354 , 0.3265387 , 0.30718827, 0.23946173,
        0.28541905, 0.21043606, 0.27816263, 0.        , 0.24429934,
        0.3168635 , 0.37733364, 0.3531456 , 0.3120259 , 0.34347036,
        0.33621395, 0.23462412, 0.2588122 , 0.2201113 , 0.21527368,
        0.29751307, 0.38217124, 0.3555644 , 0.32895753, 0.30235067,
        0.35072678, 0.3047695 , 0.33137634, 0.24671815, 0.25397456,
        0.34347036, 0.33379513, 0.33379513, 0.25639337, 0.3120259 ,
        0.18866682, 0.3579832 , 0.360402  , 0.41361573, 0.41361573,
        0.3217011 , 0.28300023, 0.23704293, 0.27816263, 0.33621395,
        0.3531456 , 0.31928232, 0.36523962, 0.24671815, 0.28541905,
        0.4039405 , 0.20076084, 0.40152168, 0.33863276, 0.34105155,
        0.39426526, 0.28783783, 0.19592324, 0.31928232, 0.32411993,
        0.36523962, 0.32411993, 0.2201113 , 0.23462412, 0.3120259 ,
        0.32411993, 0.3096071 , 0.3096071 , 0.34347036, 0.15238474,
        0.29751307, 0.2709062 , 0.3096071 , 0.37733364, 0.30235067,
        0.08465819, 0.3628208 , 0.273325  , 0.3144447 , 0.3991029 ,
        0.38217124, 0.27816263, 0.34105155, 0.25155577, 0.40152168,
        0.24913695, 0.34588918, 0.32895753, 0.3217011 , 0.29993185,
        0.3217011 , 0.28300023, 0.29267547, 0.2757438 , 0.25155577,
        0.21527368, 0.43780378, 0.29509425, 0.3168635 , 0.30718827,
        0.41603452, 0.29267547, 0.24913695, 0.273325  , 0.273325  ,
        0.3628208 , 0.34588918, 0.32895753, 0.31928232, 0.38459006,
        0.25397456, 0.35072678, 0.3168635 , 0.42329094, 0.2684874 ,
        0.29509425, 0.33137634, 0.2709062 , 0.3676584 , 0.360402  ,
        0.24671815, 0.21527368, 0.38942766, 0.3144447 , 0.32895753,
        0.20076084, 0.13303429, 0.3676584 , 0.3144447 , 0.19108562,
        0.18866682, 0.32411993, 0.3555644 , 0.29993185, 0.34105155,
        0.3991029 , 0.447479  , 0.32411993, 0.34105155, 0.38942766,
        0.28783783, 0.3676584 , 0.39426526, 0.2709062 , 0.27816263,
        0.3047695 , 0.42570975, 0.28541905, 0.2201113 , 0.29751307,
        0.23946173, 0.30235067, 0.2757438 , 0.3217011 , 0.        ,
        0.23220532, 0.36523962, 0.28300023, 0.2757438 , 0.3144447 ,
        0.28541905, 0.34588918, 0.25155577, 0.12094027, 0.16931638,
        0.23946173, 0.2636498 , 0.3265387 , 0.30718827, 0.3531456 ,
        0.33379513, 0.24188054, 0.26123098, 0.3217011 , 0.20317966,
        0.29993185, 0.35072678, 0.3555644 , 0.38942766, 0.38217124,
        0.20559846, 0.39668408, 0.37007722, 0.2273677 , 0.1789916 ,
        0.        , 0.33137634, 0.37007722, 0.38459006, 0.29025665,
        0.30235067, 0.33379513, 0.14512832, 0.3531456 , 0.29025665,
        0.3047695 , 0.42087212, 0.3579832 , 0.37733364, 0.30235067,
        0.2225301 , 0.34830797, 0.23946173, 0.27816263, 0.3047695 ,
        0.41119692, 0.273325  , 0.26606858, 0.2757438 , 0.3096071 ,
        0.51278675, 0.28300023, 0.32411993, 0.37733364, 0.23946173,
        0.3676584 , 0.34830797, 0.20317966, 0.3217011 , 0.21043606,
        0.2757438 , 0.2225301 , 0.23462412, 0.2805814 , 0.3047695 ,
        0.360402  , 0.24913695, 0.6119578 , 0.40635931, 0.29267547,
        0.33621395, 0.4402226 , 0.        , 0.37491482, 0.37249604,
        0.25639337, 0.29025665, 0.22978652, 0.25639337, 0.2225301 ,
        0.25155577, 0.32411993, 0.32895753, 0.        , 0.3579832 ,
        0.21043606, 0.3144447 , 0.33137634, 0.3120259 , 0.3217011 ,
        0.32411993, 0.38459006, 0.30235067, 0.37249604, 0.2249489 ,
        0.2588122 , 0.08465819, 0.21769248, 0.34347036, 0.34588918,
        0.2805814 , 0.15238474, 0.34347036, 0.2225301 , 0.17173518,
        0.3096071 , 0.21043606, 0.27816263, 0.2684874 , 0.25397456,
        0.1838292 , 0.29751307, 0.35072678, 0.37491482, 0.23946173,
        0.37249604, 0.38217124, 0.35072678, 0.34347036, 0.3096071 ,
        0.3579832 , 0.26606858, 0.3579832 , 0.39668408, 0.24429934,
        0.28300023, 0.2588122 , 0.27816263, 0.31928232, 0.29993185,
        0.41603452, 0.30235067, 0.2273677 , 0.37975246, 0.28541905,
        0.26606858, 0.3531456 , 0.2805814 , 0.39668408, 0.28541905,
        0.273325  , 0.        , 0.22978652, 0.360402  , 0.3265387 ,
        0.29509425, 0.35072678, 0.30718827, 0.40635931, 0.2201113 ,
        0.25639337, 0.33863276, 0.360402  , 0.3217011 , 0.26123098,
        0.3628208 , 0.3096071 , 0.21285488, 0.21769248, 0.36523962,
        0.2225301 , 0.43054736, 0.31928232, 0.34105155, 0.3144447 ,
        0.15238474, 0.3217011 , 0.26606858, 0.39426526, 0.34105155,
        0.2709062 , 0.447479  , 0.17415398, 0.3217011 , 0.36523962,
        0.35072678, 0.29751307, 0.32895753, 0.42329094, 0.23220532,
        0.30235067, 0.29025665, 0.33379513, 0.28541905, 0.32411993,
        0.23946173, 0.30235067, 0.11610266, 0.26123098, 0.360402  ,
        0.3217011 , 0.3096071 , 0.28541905, 0.24429934, 0.29509425,
        0.37975246, 0.28300023, 0.273325  , 0.33863276, 0.32895753,
        0.28783783, 0.2805814 , 0.2249489 , 0.273325  , 0.35072678,
        0.28783783, 0.25639337, 0.16689757, 0.3555644 , 0.3144447 ,
        0.34105155, 0.33137634, 0.25155577, 0.34105155, 0.1814104 ,
        0.28541905, 0.2757438 , 0.35072678, 0.34105155, 0.23220532,
        0.3628208 , 0.2684874 , 0.3628208 , 0.22978652, 0.28783783,
        0.360402  , 0.33621395, 0.41603452, 0.34347036, 0.2709062 ,
        0.28541905, 0.33137634, 0.2273677 , 0.38700885, 0.21527368,
        0.20076084, 0.34830797, 0.28783783, 0.30235067, 0.41119692,
        0.33621395, 0.3168635 , 0.360402  , 0.32895753, 0.360402  ,
        0.18866682, 0.37975246, 0.33379513, 0.37007722, 0.28541905,
        0.39668408, 0.30235067, 0.2757438 , 0.32411993, 0.28541905,
        0.2805814 , 0.24671815, 0.28541905, 0.3676584 , 0.32895753,
        0.29751307, 0.43538496, 0.2757438 , 0.19350442, 0.28300023,
        0.29993185, 0.37491482, 0.28541905, 0.21769248, 0.36523962,
        0.21769248, 0.33137634, 0.2273677 , 0.32411993, 0.3531456 ,
        0.28300023, 0.32895753]], dtype=float32), None, array([[0.00390625, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.00390625,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.00390625, 0.        , 0.00390625, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.00390625, 0.00390625, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.00390625, 0.        , 0.00390625,
        0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.00390625,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.00390625, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.00390625,
        0.00390625, 0.01171875, 0.0078125 , 0.0078125 , 0.00390625,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00390625, 0.00390625, 0.        , 0.        , 0.        ,
        0.        , 0.00390625, 0.        , 0.        , 0.        ,
        0.00390625, 0.015625  , 0.00390625, 0.00390625, 0.0078125 ,
        0.0078125 , 0.00390625, 0.00390625, 0.00390625, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.01171875,
        0.00390625, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.00390625,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.00390625,
        0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.00390625, 0.        , 0.00390625, 0.        ,
        0.        , 0.        , 0.00390625, 0.00390625, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.00390625, 0.        , 0.00390625,
        0.        , 0.00390625, 0.        , 0.00390625, 0.00390625,
        0.00390625, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.00390625, 0.        , 0.00390625,
        0.        , 0.00390625, 0.00390625, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.00390625, 0.        , 0.        , 0.00390625,
        0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.00390625,
        0.        , 0.        , 0.        , 0.        , 0.00390625,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00390625, 0.00390625, 0.        , 0.00390625, 0.00390625,
        0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.00390625,
        0.        , 0.        , 0.        , 0.00390625, 0.        ,
        0.00390625, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.00390625, 0.00390625, 0.0078125 , 0.        ,
        0.00390625, 0.00390625, 0.        , 0.        , 0.        ,
        0.00390625, 0.00390625, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.0078125 , 0.        ,
        0.        , 0.00390625, 0.        , 0.        , 0.00390625,
        0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.00390625,
        0.0078125 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.00390625, 0.        , 0.        , 0.        ,
        0.        , 0.00390625, 0.        , 0.00390625, 0.00390625,
        0.        , 0.        , 0.00390625, 0.        , 0.        ,
        0.        , 0.        , 0.00390625, 0.00390625, 0.00390625,
        0.00390625, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.00390625,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00390625, 0.        , 0.00390625, 0.        , 0.        ,
        0.00390625, 0.        , 0.        , 0.        , 0.        ,
        0.00390625, 0.01171875, 0.00390625, 0.        , 0.        ,
        0.00390625, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.00390625, 0.        , 0.00390625, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00390625, 0.        , 0.        , 0.00390625, 0.        ,
        0.00390625, 0.        , 0.00390625, 0.        , 0.        ,
        0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.0078125 ,
        0.        , 0.        , 0.00390625, 0.00390625, 0.00390625,
        0.0078125 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00390625, 0.        , 0.        , 0.00390625, 0.        ,
        0.0078125 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.00390625, 0.        , 0.00390625, 0.        ,
        0.        , 0.        , 0.        , 0.00390625, 0.00390625,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00390625, 0.00390625, 0.00390625, 0.00390625, 0.00390625,
        0.00390625, 0.        , 0.        , 0.00390625, 0.00390625,
        0.0078125 , 0.00390625, 0.        , 0.00390625, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00390625, 0.        , 0.00390625, 0.00390625, 0.0078125 ,
        0.        , 0.00390625, 0.01953125, 0.01171875, 0.0078125 ,
        0.0078125 , 0.00390625, 0.00390625, 0.00390625, 0.00390625,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00390625, 0.        , 0.00390625, 0.        , 0.        ,
        0.00390625, 0.0078125 , 0.00390625, 0.        , 0.00390625,
        0.        , 0.        , 0.00390625, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.00390625,
        0.        , 0.0078125 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.00390625, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ]], dtype=float32)]
```
I don't see any none. Can you verify your script can reproduce the  bug correctly? Also can you check if you are linked to the lastest changes.

Thanks,

Jian Chen

**Comment by vonJJ** [comment] 2023-03-27 08:29
> 
Actually there is a "None" output in the output you have given. Maybe it's because the 'None' output is the third output, so it is difficult to find out. You can search "None" in this page or you can print in the way of result_prob[0], result_prob[1], result_prob[2], result_prob[3] and then you can find that result_prob[2] is None.

**Comment by skottmckay** [comment] 2023-03-27 11:07
> Yes, but it doesn't work as well when I use in the second format.

Can you please clarify? 

Can you also try explicitly requesting the outputs by name so it's clear which one returns None? 

e.g. 
```py
result_prob = ort_session.run(['output_1', 'output_2', 'output_3', 'output_4'], input_feed=feed_dict)
```

There could be a bug where it's converting the DQ -> fp32 op -> Q group of nodes into a single node for the quantized operation without checking if the DQ produces a graph output.

**Comment by vonJJ** [comment] 2023-03-27 12:24
> > Yes, but it doesn't work as well when I use in the second format.
> 
> Can you please clarify?
> 
> Can you also try explicitly requesting the outputs by name so it's clear which one returns None?
> 
> e.g.
> 
> ```python
> result_prob = ort_session.run(['output_1', 'output_2', 'output_3', 'output_4'], input_feed=feed_dict)
> ```
> 
> There could be a bug where it's converting the DQ -> fp32 op -> Q group of nodes into a single node for the quantized operation without checking if the DQ produces a graph output.

In your code the is output_3 which produces None.

**Comment by skottmckay** [comment] 2023-03-31 08:21
Should be resolved by https://github.com/microsoft/onnxruntime/pull/15145 by either the check for a DQ node producing a graph output in the DropDQ selector, or by duplicating the DQ node with two consumers (one graph output, one downstream node).

**Closed by skottmckay** 2023-03-31 08:21 UTC
Labels: quantization
