### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by dashesy** [Microsoft/onnxruntime#510] opened 2019-02-22 02:04 UTC
**Describe the bug**
After pip install onnxruntim

import onnxruntime

ModuleNotFoundError                       Traceback (most recent call last)
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): pip install onnxruntime
- ONNX Runtime version: 0.2.1
- Python version: 3.7
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
import onnxruntime

**Additional context**
Fresh Anaconda3
pip install onnxruntime

**Comment by skottmckay** [comment] 2019-02-22 02:08
What numpy version are you using, and how was it installed (conda or pip)? The output from 'conda list' would be helpful to determine this.

**Comment by dashesy** [comment] 2019-02-22 02:25
This was fresh install of Anaconda3 I also updated numpy with the same error. This is from conda list:

```
numpy                     1.15.4           py37h19fb1c0_0
numpy-base                1.15.4           py37hc3f5095_0
```

Also, I have not install `onnx` itself because it is giving me error:

```
$ pip install onnx
Collecting onnx
  Using cached https://files.pythonhosted.org/packages/59/09/61f817a530cd9b9bd0e289bc9cda46f662fcda4dc1bd687b36d45365e3ea/onnx-1.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    fatal: not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ehazar\AppData\Local\Temp\pip-install-sopv5lb_\onnx\setup.py", line 71, in <module>
        assert CMAKE, 'Could not find "cmake" executable!'
    AssertionError: Could not find "cmake" executable!

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ehazar\AppData\Local\Temp\pip-install-sopv5lb_\onnx\
```

Tries to compile (perhaps no wheel for Windows?)

**Comment by skottmckay** [comment] 2019-02-22 02:28
> I also updated numpy with the same error.

That would strongly suggest it's an issue with the numpy install. You could try uninstalling and reinstalling numpy. If you can't import numpy into python, the issue is below onnxruntime.

**Comment by dashesy** [comment] 2019-02-22 02:31
I can import numpy fine

```
$ ipython
Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy as np
```

What about `onnx`? isn't that a dependency? I guess it has no wheels installs for Windows

**Comment by skottmckay** [comment] 2019-02-22 02:35
I believe there's a binary install. 
`conda install -c conda-forge onnx`

**Comment by dashesy** [comment] 2019-02-22 02:36
Ok I did `pip install --upgrade numpy` and now I have `numpy-1.16.1` and that fixed the issue. I think you should add `numpy >= 1.16` to your requirements

**Comment by dashesy** [comment] 2019-02-22 02:39
`conda install -c conda-forge onnx` does install onnx, but it also downgrades numpy to 1.15, I wonder why there is a hard requirement to 1.15

**Comment by dashesy** [comment] 2019-02-22 02:45
huh it also downgraded the entire python to py36 (I wonder why conda even allows that!) and installs conda-forge/win-64::onnx-1.1.1-py36_0 

What is a working environment to try onnxruntime in Python? what is the suggested Python version, ...?

**Comment by raymondxyang** [comment] 2019-02-22 03:38
hi sorry for replying late:
1. for onnxruntime numpy issue: yes it is a known issue. upgrading to latest numpy version will solve it. we are looking it.
2. for onnx: currently conda-forge did not have a 3.7 protobuf package. We suggest u working on python 3.6 with conda installed 3.5.2 version protobuf. 3.6.1 protobuf for python 3.6 is also missing some symbols. We are thinking of building protobuf on the fly instead of using shipped binary soon.

**Comment by akavalar** [comment] 2019-02-24 20:41
I had the same problem. Uninstalling numpy 1.15.3 and installing numpy 1.16.1 solved it for me (it also solved the segfault issue I was having).

**Comment by dashesy** [comment] 2019-02-28 19:21
Started with a miniconda
Installed a py36 conda environment, 

    conda create --name py36 python=3.6 anaconda

and upgraded numpy 
   
    pip install --upgrade numpy

Then I can install and import both

    pip install onnx
    pip install onnxruntime

**Comment by pranavsharma** [comment] 2019-03-08 04:11
This will get resolved in the latest release coming out soon (few days). Stay tuned.

**Closed by pranavsharma** 2019-03-08 04:11 UTC
Labels: bug
