### ISSUE TITLE
TopK not supported?

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#2849] opened 2020-01-16 09:34 UTC
```
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node TopK(11)

```

```
onnxruntime                   1.1.0                  

```

Doesn't TopK supported for now?

**Comment by jywu-msft** [comment] 2020-01-16 18:06
it may be due to the same issue https://github.com/microsoft/onnxruntime/issues/2814
which was recently fixed in master with
https://github.com/microsoft/onnxruntime/pull/2833
can you confirm if your model has topK which requires int64 type support?

**Comment by pranavsharma** [comment] 2020-01-16 22:03
There's a followup PR that makes it easy to add more types here - https://github.com/microsoft/onnxruntime/pull/2842

**Comment by jinfagang** [comment] 2020-01-17 03:13
@jywu-msft @pranavsharma  thanks for your response. From onnx documentation:

```
Type Constraints
T : tensor(uint8), tensor(uint16), tensor(uint32), tensor(uint64), tensor(int8), tensor(int16), tensor(int32), tensor(int64), tensor(float16), tensor(float), tensor(double)
```

https://github.com/onnx/onnx/blob/master/docs/Operators.md#TopK

It should support input with type int64.

Actually, what surprise me is that I remmber I successfully forwarded such as likely model with TopK node. But now it fails, so strange.

**Comment by pranavsharma** [comment] 2020-01-17 20:24
Which opset are you using? Can you share the model? I just updated topk to support int64_t for opset 11 only.

**Comment by jinfagang** [comment] 2020-01-19 03:39
@pranavsharma  I am using opset 11.

the model is here https://drive.google.com/open?id=1CegIKH7PF_HzGpzXuTkQ4r38cMyKIG5H

**Comment by cjermain** [comment] 2020-02-23 21:42
I am also seeing this in opset 11 with onnxruntime 1.1.1, when trying to sort a Tensor of int64.

**Comment by pranavsharma** [comment] 2020-02-24 20:43
> @pranavsharma I am using opset 11.
> 
> the model is here https://drive.google.com/open?id=1CegIKH7PF_HzGpzXuTkQ4r38cMyKIG5H

This is an invalid model.

```
PS C:\Users\prs\work_projects\onnxruntime> .\build\Windows\Debug\Debug\onnx_test_runner.exe -vv C:\Users\prs\Downloads\centermask
2020-02-24 12:42:14.5223945 [E:onnxruntime:Default, runner.cc:185 RunTests] Test centermask failed:This is an invalid model. Type Error: Type 'tensor(bool)' of input parameter (1203) of operator (ReduceSum) in node () is invalid.
result:
        Models: 1
        Total test cases: 0
                Succeeded: 0
                Not implemented: 0
                Failed: 0
        Stats by Operator type:
                Not implemented(0):
                Failed:
Failed Test Cases:
```

**Comment by cjermain** [comment] 2020-03-01 22:45
The following model reproduces the error with onnxruntime 1.1.2.

https://drive.google.com/file/d/1Vgj_evFx2mvUBIf3713OpKWnifpX7HlV/view?usp=drivesdk
(md5sum is `c60f5519f3a6a8e0fc5a7c98641179c1`)

I produced it with the below PyTorch 1.4.0 code, exporting to opset 11. I ran `onnx.checker.check_model` and did no see any errors (using onnx 1.6.0).

```python
import torch
import torch.nn as nn

class SortNet(nn.Module):
    
    def forward(self, X):
        values, indices = X.sort(descending=True)
        return indices

net = SortNet()
X = torch.arange(10)

torch.onnx.export(
    net,
    X,
    'sort.onnx',
    export_params=True,
    do_constant_folding=True,
    opset_version=11,
    input_names=['input'],
    output_names=['output'],
    dynamic_axes={
        'input': {0: 'batch'},
        'output': {0: 'batch'},
    },
    verbose=True
)
```

**Comment by pranavsharma** [comment] 2020-03-02 02:03
See https://github.com/microsoft/onnxruntime/issues/3092#issuecomment-593073730.

**Closed by pranavsharma** 2020-03-02 02:03 UTC
Labels: enhancement
