### ISSUE TITLE
"Kernel died, restarting" everytime the session.run([], {input:value}) function from onnx runtime is called

### ISSUE THREAD

**Issue by mahdouch550** [Microsoft/onnxruntime#552] opened 2019-03-06 10:28 UTC
I have an ONNX object detection model from CNTK. I create a session instance using the onnxruntime.InferenceSession(onnxModelFilePath), I set the input as described. The problem is when I call the session.run([], {input:value}) function to save the result, I get the "Kernel died, restarting" error message. I tried it with Spyder, Jupyter, and Powershell, I keep getting the same error message. Any help would be appreciated. Apologies for any inaccuracy.

**Comment by snnn** [comment] 2019-03-06 19:21
Hi,

Thanks for reporting the bug.

I guess the error message was from Spyder. We need more information to help you. We need the error messages from ONNX Runtime itself.

**Comment by mahdouch550** [comment] 2019-03-06 19:26
Hi,

I had the same issue on jupyter notebook and on the powershell as well.
and there is no error message at all.
I first thought it was a Spyder bug but it is not.
You can refer to #8890.

**Comment by snnn** [comment] 2019-03-06 19:30
Could you run the script directly from python.exe? Without Spyder and jupyter.
You can get the latest Python from https://www.python.org/downloads/ .

**Comment by mahdouch550** [comment] 2019-03-06 19:34
I did, that's what I meant with "Powershell", I'm sorry if I'm not using the correct words, I am new to all this.
I appreciate your help.

**Comment by pranavsharma** [comment] 2019-03-06 20:39
Please paste the screenshot of your powershell run so that we can take a look at the error reported by onnxruntime.

**Comment by mahdouch550** [comment] 2019-03-06 20:41
I apologize I don't have the computer now, I will do that first thing in the morning tomorrow.

**Comment by mahdouch550** [comment] 2019-03-07 09:35
![image](https://user-images.githubusercontent.com/45071146/53946670-2331b400-40bc-11e9-93c2-d5d5dc14ac4d.png)

If I hit enter after typing 'session.run([],{"data":img})' the powershell windows wait a couple of seconds than exits python automatically.

![image](https://user-images.githubusercontent.com/45071146/53946798-63913200-40bc-11e9-9076-d30f7eba6450.png)

**Comment by mahdouch550** [comment] 2019-03-07 09:42
this is what I get when using Jupyter notebook:

![image](https://user-images.githubusercontent.com/45071146/53947242-4b6de280-40bd-11e9-9c5d-1e9b47f6578e.png)

**Comment by pranavsharma** [comment] 2019-03-08 04:06
I can't reproduce the problem. See below.

![image](https://user-images.githubusercontent.com/2732907/54006968-85b69e80-4114-11e9-9f42-f26adb5e76bf.png)

**Comment by snnn** [comment] 2019-03-08 04:58
You two have different numpy version.

**Comment by pranavsharma** [comment] 2019-03-08 05:12
Ah, this issue will be fixed in the upcoming release (in a few days). Stay tuned. The current version of onnxruntime (0.2.1) depends on numpy 1.16. The new one (0.3.0) will use 1.15 as the dependency.

**Closed by pranavsharma** 2019-03-08 05:12 UTC
