### ISSUE TITLE
Describe outputs sequence / map

### ISSUE THREAD

**Issue by XciD** [microsoft/onnxruntime#2334] opened 2019-11-06 16:11 UTC
**Is your feature request related to a problem? Please describe.**

I'm using the Java api that is linked with the C api trough #2215 
When we describe output, the java api calls `onnxruntime_c_api.cc` and method `SessionGetOutputTypeInfo`

The problem is that `OrtTypeInfo` don't tell us much about Sequence and Maps.

**System information**
- ONNX Runtime version (you are using): 0.5.0

**Describe the solution you'd like**
More information about the seq/map outputs in the c api

**Describe alternatives you've considered**
For now, the best solution I’ve found is to call the model with empty array and iterate through results.

**Comment by pranavsharma** [comment] 2019-11-14 03:15
Duplicate of https://github.com/microsoft/onnxruntime/issues/1747

**Closed** 2019-11-14 06:49 UTC
Labels: enhancement
