### ISSUE TITLE
[BUILD/Visual 2017/ort1.7] compilation issue \onnxruntime\core\providers\cpu\math\element_wise_ops.cc error C2514 class has no constructors

### ISSUE THREAD

**Issue by ThomasRetornaz** [microsoft/onnxruntime#6912] opened 2021-03-05 18:18 UTC
**Describe the bug**
Hi we currently want to migrate our system to ort 1.7. 
When i made the migration some compilation issue occurs on Visual Studio 15 2017 Win64 around Eigen integration in element_wise_ops.

Mainly some 
error C2514: 'Eigen::Map<const Eigen::Matrix<T,-1,1,,-1,1>,0,Eigen::Stride<0,0>>': class has no constructors

Then template nightmare occurs and we reach to 
fatal error C1003: error count exceeds 100; stopping compilation

I follow the guidelines of https://www.onnxruntime.ai/docs/how-to/build.html to be sure the problem doesn't come from our integration.

**Urgency**
We could keep ort1.6 for a while

**System information**
- Windows 10 Pro 20H2
-  from source
- ONNX Runtime version: 1.7.0
- Python version: 3.8amd64
- Visual Studio 15 Microsoft Visual Studio Professional 2017  Version Release/15.9.33+28307.1401

**To Reproduce**
- I follow the steps from https://www.onnxruntime.ai/docs/how-to/build.html 
git clone --recursive https://github.com/Microsoft/onnxruntime -b v1.7.0
in visual prompt 
.\build.bat --config Release --build_shared_lib --parallel
- Attach the ONNX model to the issue (where applicable) to expedite investigation.
Not applicable
**Expected behavior**
Build success

**Screenshots**
Not applicable

**Additional context**
I could share the complete build log

**Comment by jcwchen** [comment] 2021-03-05 18:53
Duplicate of https://github.com/microsoft/onnxruntime/issues/6752

**Comment by sharvin-vittappan** [comment] 2021-04-13 08:18
I am also facing the same issue with VS2017.

**Comment by ytaous** [comment] 2021-08-10 06:37
please try vs2019, thx

**Closed by ytaous** 2021-08-10 06:37 UTC
Labels: status:contributions-welcome
