### ISSUE TITLE
[Build] dockerfile CPU fail with document

### ISSUE THREAD

**Issue by foxnight2** [microsoft/onnxruntime#17810] opened 2023-10-06 01:57 UTC
### Describe the issue

Follow this   
https://github.com/microsoft/onnxruntime/tree/main/dockerfiles#cpu

```
cd onnxruntime
docker build -t onnxruntime-source -f Dockerfile.source ..
```

### Target platform

linux

### Build script

```
docker build -t onnxruntime-source -f Dockerfile.source ..

```

### Error / output

```
[+] Building 14.6s (9/12)                                                                                docker:default
 => [internal] load build definition from Dockerfile.source                                                        0.0s
 => => transferring dockerfile: 1.32kB                                                                             0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 72B                                                                                   0.0s
 => [internal] load metadata for mcr.microsoft.com/cbl-mariner/base/python:3                                       1.4s
 => CACHED [stage-0 1/5] FROM mcr.microsoft.com/cbl-mariner/base/python:3@sha256:6a1b03924d60b6de208e26a398887974  0.0s
 => [internal] load build context                                                                                  0.5s
 => => transferring context: 704.25kB                                                                              0.5s
 => CACHED [stage-0 2/5] ADD . /code                                                                               0.0s
 => CACHED [stage-0 3/5] RUN tdnf install -y tar ca-certificates build-essential python3-numpy cmake python3-setu  0.0s
 => CACHED [stage-0 4/5] RUN /code/dockerfiles/scripts/install_cmake.sh                                            0.0s
 => ERROR [stage-0 5/5] RUN cd /code && python3 -m pip install -r tools/ci_build/github/linux/docker/inference/x  12.7s
------
 > [stage-0 5/5] RUN cd /code && python3 -m pip install -r tools/ci_build/github/linux/docker/inference/x64/python/cpu/scripts/requirements.txt && /bin/bash ./build.sh --allow_running_as_root --skip_submodule_sync --config Release --build_wheel --update --build --parallel --cmake_extra_defines ONNXRUNTIME_VERSION=$(cat ./VERSION_NUMBER):
2.434 Ignoring numpy: markers 'python_version >= "3.11"' don't match your environment
2.440 Collecting onnx
2.441   Cloning http://github.com/onnx/onnx.git (to revision fdefbe85ed9c362b95b9b401cd19db068a76141f) to /tmp/pip-install-t_76hx51/onnx_d3f1decb10aa42c79cda277bf2287f7c
2.445   ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version
2.445 ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
------
Dockerfile.source:15
--------------------
  13 |
  14 |     # Prepare onnxruntime repository & build onnxruntime
  15 | >>> RUN cd /code && python3 -m pip install -r tools/ci_build/github/linux/docker/inference/x64/python/cpu/scripts/requirements.txt && /bin/bash ./build.sh --allow_running_as_root --skip_submodule_sync --config Release --build_wheel --update --build --parallel --cmake_extra_defines ONNXRUNTIME_VERSION=$(cat ./VERSION_NUMBER)
  16 |
  17 |     FROM mcr.microsoft.com/cbl-mariner/base/python:3
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /code && python3 -m pip install -r tools/ci_build/github/linux/docker/inference/x64/python/cpu/scripts/requirements.txt && /bin/bash ./build.sh --allow_running_as_root --skip_submodule_sync --config Release --build_wheel --update --build --parallel --cmake_extra_defines ONNXRUNTIME_VERSION=$(cat ./VERSION_NUMBER)" did not complete successfully: exit code: 1
```

**Comment by wschin** [comment] 2023-10-06 16:17
Looks like a duplicate of #17781.

**Closed** 2023-10-06 16:19 UTC
Labels: build
