### ISSUE TITLE
ONNX inference session consumes too much memory

### ISSUE THREAD

**Issue by shengyfu** [Microsoft/onnxruntime#677] opened 2019-03-21 22:01 UTC
**Describe the bug**
We have a LSTM model trained in Tensorflow and quantized with onnx format.
-	the model is 39 MB on disk.
-	Using C-API, it consumes 44 MB after loading
-	Using  C#-API,
-	        Consumes 48 MB to load the model
-	        Consumes 396 MB after scoring 1 small tensor    // what is using up this much  memory?
-	        Reduces down to 22 MB after unloading the model (disposing the inference session)
-	        Disposing the resulting tensors don’t seem to decrease memory consumption either.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64-bit
- ONNX Runtime installed from (source or binary): 
- ONNX Runtime version:0.3.0
- Python version:
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
Replace Program.cs in https://github.com/Microsoft/onnxruntime/tree/master/csharp/sample/Microsoft.ML.OnnxRuntime.InferenceSample with the file contained in following zip:
[Program.zip](https://github.com/Microsoft/onnxruntime/files/2994115/Program.zip)
You can get the model file from me offline.

**Expected behavior**
Low memory consumption comparable to the model size

**Screenshots**

**Additional context**

**Comment by jignparm** [comment] 2019-03-22 23:28
The large memory consumption is reproducible using C-API (not isolated to C# API). Most likely some operator is maintaining state information (either by design, or by error).

**Comment by jignparm** [comment] 2019-03-27 21:33
Update: The large memory consumption is tracked to the quantization of the model. Newer version of OnnxRuntime should apply constant folding and only 48MB will be used when full quantization support is available.

**Comment by askhade** [comment] 2019-04-05 00:50
Closing this issue... @jignparm already summarized the it above.

**Closed by askhade** 2019-04-05 00:50 UTC
Labels: performance
