### ISSUE TITLE
[web] feature request: support WebGL inside web worker 

### ISSUE THREAD

**Issue by amanraja** [microsoft/onnxruntime#9458] opened 2021-10-19 19:13 UTC
`WebGLBackend 2021-10-19T19:05:16.905Z|Unable to initialize WebGLBackend. ReferenceError: document is not defined`

Is there any other way we can initialize WebGL ? 

maybe by using `OffscreenCanvas` ?

**Comment by dzhen19** [comment] 2021-10-29 20:58
Any updates on this? Does anyone know if there's a way to run an inference session without causing the UI thread to hang?

**Comment by fs-eire** [comment] 2021-11-01 01:24
> Any updates on this? Does anyone know if there's a way to run an inference session without causing the UI thread to hang?

I tried to compile ort.min.js targeting web worker. However that causes multiple errors in webpack. It may take more efforts than expected to make the whole ort web to work in web worker.

there is a workaround for now. use [this](https://github.com/microsoft/onnxruntime/blob/master/js/common/lib/env.ts#L84) flag to make the texture download async. It is not an official flag yet as we need more testing and may make changes to it in future.

**Comment by 101arrowz** [comment] 2022-06-25 19:27
This is very, very easy to make work in modern Chrome (and Firefox after you turn on a flag). [These lines](https://github.com/microsoft/onnxruntime/blob/4ebc9c3b5e4cbdd4cdf3e08906fef7ea49fed508/js/web/lib/onnxjs/backends/webgl/webgl-context-factory.ts#L86-L91) that instantiate a canvas element with the DOM can simply be replaced with the following:
```ts
declare var OffscreenCanvas: {
  new(width: number, height: number): HTMLCanvasElement;
}

function createCanvas(): HTMLCanvasElement {
  if (typeof document == 'undefined') {
    return new OffscreenCanvas(1, 1);
  }
  const canvas: HTMLCanvasElement = document.createElement('canvas');
  canvas.width = 1;
  canvas.height = 1;
  return canvas;
}
```

This actually works almost flawlessly, I'm able to run the entirety of ORT Web in a web worker. @fs-eire if you're able I would really appreciate if you could bring this functionality into ONNX Runtime Web with a `.proxy` flag to automatically use web workers with the WebGL backend - I think that would involve sending the full graph to the web worker and using a `env.webgl.workerPath` option of some kind to construct the worker (since it's probably going to be way too big to inline).

If you can't do that I can just submit a PR with this patch.

**Comment by Amadeuy** [comment] 2022-07-16 22:54
> `WebGLBackend 2021-10-19T19:05:16.905Z|Unable to initialize WebGLBackend. ReferenceError: document is not defined`
> 
> 
> 
> Is there any other way we can initialize WebGL ? 
> 
> 
> 
> maybe by using `OffscreenCanvas` ?

**Comment by Amadeuy** [comment] 2022-07-16 22:54
> `WebGLBackend 2021-10-19T19:05:16.905Z|Unable to initialize WebGLBackend. ReferenceError: document is not defined`
> 
> 
> 
> Is there any other way we can initialize WebGL

**Comment by Amadeuy** [comment] 2022-07-17 00:00
> > `WebGLBackend 2021-10-19T19:05:16.905Z|Unable to initialize WebGLBackend. ReferenceError: document is not defined`
> > 
> > 
> > 
> > Is there any other way we can initialize WebGL
> 
>

**Comment by fs-eire** [comment] 2022-07-20 21:07
the issue is closed automatically by merging the PR.

I reopen this issue because we didn't validate whether it is working in web worker now

**Comment by 101arrowz** [comment] 2022-07-27 17:44
I've been using the same patch in my own fork and it works well, but I also need #11990 to be merged before I can fully switch back to original ORT Web and test fully.

**Comment by guschmue** [comment] 2023-02-13 19:28
should be fixed.

**Closed by guschmue** 2023-02-13 19:28 UTC
Labels: feature request, platform:web
