### ISSUE TITLE
Exception while initializing OpenVINO provider 

### ISSUE THREAD

**Issue by smartnet-club** [microsoft/onnxruntime#18876] opened 2023-12-19 16:09 UTC
### Describe the issue

Problem with commit 0723dcb8b591a559db60885ff2cad610fd989ad4
provider_bridge_ort.cc 
OrtOpenVINOProviderOptionsToOrtOpenVINOProviderOptionsV2

**incorrect reinterpret_cast** from _unsigned char_ to _const char*_
std::string enable_dynamic_shapes = reinterpret_cast<const char*>(legacy_ov_options->enable_dynamic_shapes);

while
OrtOpenVINOProviderOptions
unsigned char enable_dynamic_shapes;     ///< 0 = disabled, nonzero = enabled

### To reproduce

api.SessionOptionsAppendExecutionProvider_OpenVINO(session_options, &openvinoOptions)

### Platform

Linux

### OS Version

22.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

0723dcb8b591a559db60885ff2cad610fd989ad4

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

OpenVINO

### Execution Provider Library Version

2023.2.0

**Comment by jywu-msft** [comment] 2023-12-19 16:35
+@sfatimar

**Comment by jywu-msft** [comment] 2024-01-19 20:15
> +@sfatimar

+@preetha-intel FYI

**Comment by preetha-intel** [comment] 2024-01-20 16:06
The issue is fixed in latest master. 
[pull/19023] (https://github.com/microsoft/onnxruntime/pull/19023)

**Comment by preetha-intel** [comment] 2024-01-30 05:45
@smartnet-club  Can we verify the fix

**Closed** 2024-05-30 12:11 UTC
Labels: ep:OpenVINO
