### ISSUE TITLE
[Build] Failed to compile against TensoRT 10.5

### ISSUE THREAD

**Issue by mc-nv** [microsoft/onnxruntime#22387] opened 2024-10-10 14:51 UTC
### Describe the issue

Recent build of ONNX Runtime 1.19.2 against TensorRT 10.5.0.18 was unsuccessful, due to an API deprecation.
|  |   |        
| :---: | :---: |
| BUILDTOOLS_VERSION |17.12.35323.107 |  
| CMAKE_VERSION| 3.30.0 |
| CUDA_VERSION| 12.5.1|
| CUDNN_VERSION|9.5.0.50|
 |PYTHON_VERSION|3.10.11| 
|TENSORRT_VERSION|10.5.0.18|
|VCPGK_VERSION|2024.03.19|

Here is a documentation reference:
https://docs.nvidia.com/deeplearning/tensorrt/release-notes/index.html
https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_builder.html#a5758c218e1d9f36bea5b9f7bc63b9ca9

### Urgency

Could you please prioritize it for next release.

### Target platform

Windows, haven't test against Linux

### Build script

```powershell
${env:ONNXRUNTIME_TAG}="v1.19.2"
${env:CUDAARCHS}= "60;61;70;75;80;86;90"
git clone --recursive --single-branch -b ${env:ONNXRUNTIME_TAG} https://github.com/microsoft/onnxruntime.git onnxruntime
onnxruntime\tools\ci_build\build.py --cmake_generator "Visual Studio 17 2022" --config Release --cmake_extra_defines "CMAKE_CUDA_ARCHITECTURES=${env:CUDAARCHS}" --skip_submodule_sync --parallel --build_shared_lib --compile_no_warning_as_error --skip_tests --update --build --build_dir /workspace/build --use_cuda --cuda_home "$env:CUDA_PATH" --cudnn_home "$env:CUDA_PATH" --use_tensorrt --tensorrt_home "/tensorrt"
```

### Error / output

-----
Error ouptut:
```
C:\workspace\onnxruntime\onnxruntime\core\providers\tensorrt\tensorrt_execution_provider.cc(3547,50): error C4996: 'nvinfer1::IBuilder::platformHasFastInt8': was declared deprecated [C:\workspace\build\Release\onnxruntime_p
roviders_tensorrt.vcxproj]
C:\workspace\onnxruntime\onnxruntime\core\providers\tensorrt\tensorrt_execution_provider.cc(2910,23): error C4996: 'nvinfer1::IBuilder::platformHasFastFp16': was declared deprecated [C:\workspace\build\Release\onnxruntime_p
roviders_tensorrt.vcxproj]
C:\workspace\onnxruntime\onnxruntime\core\providers\tensorrt\tensorrt_execution_provider.cc(2917,23): error C4996: 'nvinfer1::IBuilder::platformHasFastInt8': was declared deprecated [C:\workspace\build\Release\onnxruntime_p
roviders_tensorrt.vcxproj]
C:\workspace\onnxruntime\onnxruntime\core\providers\tensorrt\tensorrt_execution_provider.cc(3134,42): error C4996: 'nvinfer1::IBuilder::platformHasFastInt8': was declared deprecated [C:\workspace\build\Release\onnxruntime_p
roviders_tensorrt.vcxproj]
```

### Visual Studio Version

17.12.35323.107

**Comment by jywu-msft** [comment] 2024-10-10 15:45
@jingyanwangms can you help?

**Comment by edgchen1** [comment] 2024-10-10 16:00
https://github.com/microsoft/onnxruntime/pull/22374 was just merged, can you try again with main?

**Comment by snnn** [comment] 2024-10-22 02:41
@mc-nv , could you please help confirm if the problem is solved?  We are preparing a new release. We hope the issue can be addressed in the release.

**Comment by mc-nv** [comment] 2024-10-22 03:28
In our build scenario change https://github.com/microsoft/onnxruntime/pull/22374 has been cherry-picked into `rel-1.19.2` and it help us to compile project.

**Comment by snnn** [comment] 2024-10-22 04:37
Thanks!

**Closed by snnn** 2024-10-22 04:37 UTC
Labels: build, ep:TensorRT
