### ISSUE TITLE
Thread affinity mask does not seem to have any effect, leading to inconsistent performance

### ISSUE THREAD

**Issue by chausner** [microsoft/onnxruntime#10104] opened 2021-12-21 22:44 UTC
**Describe the bug**
I am seeing inconsistent performance when benchmarking a CNN model. I have been able to trace the variation in performance to different assignment of threads to processor cores by the OS scheduler. Even though onnxruntime [should automatically set](https://github.com/microsoft/onnxruntime/blob/4e9e01cb3c008335a2471c27dbdf7dd5d12e4224/onnxruntime/core/session/inference_session.cc#L292) the processor affinity mask to restrict threads to the first half of logical cores, it apparently does not have an effect. If I do the same via `numactl`, I do see consistent performance but not when onnxruntime sets the affinity mask. I have checked with a debugger that onnxruntime is indeed setting the affinity mask for all 4 thread pool threads by setting a breakpoint on `pthread_setaffinity_np`.

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- ONNX Runtime installed from (source or binary): Official Python pip package
- ONNX Runtime version: 1.10.0
- Python version: 3.8
- CPU: Intel® Core™ i7-7700HQ (4 physical cores, 8 logical cores)

**To Reproduce**
Run the following benchmark multiple times:
```python
import onnxruntime as ort
import numpy as np
import time
session = ort.InferenceSession('model.onnx')
input = np.array(shape=(1, 60000), dtype=np.float32)
for i in range(100):
    start = time.time()
    outputs = session.run(['output'], {'input': input})
    print(f'Iteration: {it}, Elapsed: {time.time() - start}')
```
It will show different elapsed times between runs, e.g. sometimes
```
Iteration: 0, Elapsed: 0.223
Iteration: 1, Elapsed: 0.231
Iteration: 2, Elapsed: 0.230
...
Iteration: 99: Elapsed: 0.219
```
and sometimes:
```
Iteration: 0, Elapsed: 0.147
Iteration: 1, Elapsed: 0.145
Iteration: 2, Elapsed: 0.152
...
Iteration: 99: Elapsed: 0.148
```

If running long enough and initial thread assignment is suboptimal, it appears the OS scheduler after some time reassigns affinity to the faster configuration automatically which can be seen as e.g.:
```
Iteration: 1, Elapsed: 0.226
...
Iteration: 73, Elapsed: 0.224
Iteration: 74, Elapsed: 0.178
Iteration: 75, Elapsed: 0.152
Iteration: 76, Elapsed: 0.151
...
Iteration: 99: Elapsed: 0.149
```

The performance is consistently good (around 0.15s) when running
```
numactl --physcpubind=0,1,2,3 python3 test.py
```
and consistently bad (around 0.23s) when running
```
numactl --physcpubind=0,2,4,6 python3 test.py
```

It appears as if the Ubuntu scheduler does not honor what applications set via `pthread_setaffinity_np` but it does honor the affinity set by `numactl`.

**Expected behavior**
When running the benchmark without `numactl`, I would expect the results to always match the fast case because onnxruntime should itself set the thread affinity mask appropriately to 0,1,2,3 (half of logical cores).

**Comment by chausner-audeering** [comment] 2021-12-23 14:56
I cannot reproduce this issue with onnxruntime 1.6.0. There, performance is consistently good. Version 1.7.0 is the first version where it occurs.

**Comment by chausner-audeering** [comment] 2021-12-23 18:40
I looked into this further and noticed that the affinity mask that onnxruntime sets by default is not equivalent to `numactl --physcpubind=0,1,2,3`. onnxruntime assigns each thread to one single core while `numactl` assigns every thread to the same subset of cores. E.g.:
```
onnxruntime:
thread 0: cpu 0
thread 1: cpu 1
thread 2: cpu 2
thread 3: cpu 3

numactl --physcpubind=0,1,2,3:
thread 0: cpus 0,1,2,3
thread 1: cpus 0,1,2,3
thread 2: cpus 0,1,2,3
thread 3: cpus 0,1,2,3
```

It appears the latter leads to better/more consistent performance in my case.

I experimentally changed the behavior in https://github.com/chausner-audeering/onnxruntime/commit/1f6fb8b1b507541e09d978a1a8a46768b8e946eb to match the `numactl` command. Maybe this is something we want to consider to change?

**Comment by chausner-audeering** [comment] 2021-12-23 23:55
I'll close this issue as the title has become misleading and my initial understanding of the issue was wrong. I will do some more benchmarks and might open a new issue instead.

**Closed** 2021-12-23 23:56 UTC
Labels: type:performance, component:coreruntime
